### ISSUE TITLE
Only one image allowed in live example

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#10287]
### Summary

I created a live sample for clipboard that had two images loaded as `<img>` elements from the same folder. The first image displays. The second image displays locally but is returns a 404 on PR preview. 

I thought the issue might be a bad image, so I tried another one, I also tried copying the image that works and renaming, and that also isn't displayed. 

### URL

There is a test PR here: https://github.com/mdn/content/pull/31592

The final/second `read()` example shows the problem: https://pr31592.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Clipboard/read#result_2 (screenshot below)

### Reproduction steps

1. Open https://pr31592.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Clipboard/read#result_2 in any browser.
2. Look at it :-)

### Expected behavior

Given those images are valid and display locally, and that (some of them) are the same image copied, and all are in the same folder, I'd expect those images to download.

### Actual behavior

See screenshot. Images get 404 from network.

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://github.com/mdn/yari/assets/5368500/8ce2d504-c94d-43e4-8b3c-6c9fad2dfa52)

Note the images that are shown vs missing. The images that are shown are the same image. The missing images are other images that are in the same folder. Some of them are direct copies of the one that is being displayed.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
Reported in #9579

**Comment by wbamberg** [comment]
> Reported in #9579

I'm not saying you're wrong :) but in this issue the first image _is_ being shown, and in the linked issue it looks like none of the images are being shown??

**Comment by yin1999** [comment]
> I'm not saying you're wrong :) but in this issue the first image _is_ being shown, and in the linked issue it looks like none of the images are being shown??

The problem is that the images in live samples for PR review are hosted on `live.mdnyalp.dev` (the hosted files will only be freshed after a ["stage build"](https://github.com/mdn/yari/actions/workflows/stage-build.yml)). Therefore, the images can only be "seen" in the PR review after the relevant files have been committed to the main branch and subsequently run the stage build workflow.

The first image are _not_ newly added, which means it's already in the main branch and has been hosted on `live.mdnyalp.dev` by the previous run of stage build workflow.

But this won't impact the production (`https://developer.mozilla.org/`), we have the option to review such PRs (which has added new images for live samples) locally for now and can then merge them to the main branch safely.

**Comment by wbamberg** [comment]
Ah, thank you for the clarification @yin1999 ! <3

**Comment by hamishwillee** [comment]
Thanks! 

Closing as a duplicate of #9579
