### ISSUE TITLE
Integrate Search with Yari

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#1058]
# Description

Search previously indexed from MySQL and now needs to index from Yari's Git repo.

# Acceptance Criteria

- [ ] ES indexes based on docs Yari/Git Repo

**Comment by peterbe** [comment]
First and foremost is getting the built HTML (+ metadata) into Elasticsearch. The `yari-search` prototype already does this by simply needing an Elasticsearch URL. 

Keep this one in mind: https://github.com/mdn/yari/issues/1226
Instead of using Kuma at all, for reads, we might write a Lambda function (Python or JavaScript) that takes a query string input, makes an Elasticsearch query, and returns JSON. This can be deployed directly in Lambda with the API Gateway as all it needs is an Elasticsearch URL (secret) and some lightweight business logic to execute the ES query.
