### ISSUE TITLE
Decide on policy for reviewing/merging mdn content repo PR's

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1097]
Need to determine a policy for `mdn/mdn-content` repo's PR's given that we no longer have the content team. For example, perhaps we should simply auto-merge a PR if the linters/tests pass?

**Comment by peterbe** [comment]
We don't really have linters yet. ...on the content. 

At the moment, we disable flaw checking in PR Builds because there's sooo many flaws. That'll be significantly reduced once we have done a manual mass-cleanup using the fixable flaws. 
But there's still a large number of flaws that are not fixable. For example, use of remote images that 404. If someone wants to fix a typo in a paragraph far away from the `<img>` tag, should that block her PR?

I do wonder if we should let @chrisdavidmills own this and give him time to perhaps formulate a policy *after* the Yari1 launch. Then he can make it up based on what actually happens. 

I for one would love it if there's a document to point to. One that says some basic writing rules (e.g. no swear words, American English spelling, no aggressive tone, consistency over perfection) and also basic stuff such as one PR per topic, don't rebase your own PRs, merge in upstream master yourself if there are conflicts, etc.

**Comment by escattone** [comment]
We've got the [`CODEOWNERS` file in place](https://github.com/mdn/content/blob/main/.github/CODEOWNERS) as well a contribution guide. We can work from there in terms of tweaking the contribution guide going forward.
