### ISSUE TITLE
Resolve all file-attachment URL's and download their documents in the mdn/content repo

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1103]
Resolve all file-attachment URL's within documents to their final form, and download their corresponding content into the `mdn-content` repo. NOTE: I think @peterbe is already planning to add this feature to his flaw fixer.

Here are the signatures of the file-attachment URL's that we'll need to resolve:
- [ ] `/files/<file-id>/<filename>`
- [ ] `/@api/deki/files/<file-id>/<filename>`
- [ ] `https://mdn.mozillademos.org/files/<file-id>/<filename>`
- [ ] `https://media.prod.mdn.mozit.cloud/attachments/...`
- [ ] `/<locale>/docs/...$samples/<sample-name>/files/<file-id>/<filename>` **(NOTE: I don't see any instances of this type within our non-archived content)**

**Comment by peterbe** [comment]
Note-to-self; here's an example of a page that uses `/@api/...` http://localhost:3000/en-US/docs/Web/HTML/Element/blink#_flaws

So in these you need to assume a base URL of `https://developer.mozilla.org` and it probably will be fixable:

```
▶ c https://developer.mozilla.org/@api/deki/files/247/=HTMLBlinkElement.gif 2>&1 | rg location:
< location: https://mdn.mozillademos.org/files/490/HTMLBlinkElement.gif
```

**Comment by peterbe** [comment]
I'm tempted to remove this from the `Yari1` milestone because I don't think it needs to get done for Yari1 to launch. 
Old URLs will continue to work just fine. It's nice that Yari considers it a flaw and we already ([almost](https://github.com/mdn/yari/pull/1188)) have a solution to deal with external images as a flaw. 

But if we can find any blocker-fat to trim from the Yari1 launch the better. 

So, what I propose is that we turn this issue into a stretch-goal and let [my PR](https://github.com/mdn/yari/pull/1188) just be a part of this issue. I would also remove the estimate considering that it's no longer immediately actionable.

**Comment by peterbe** [comment]
We did it!
