### ISSUE TITLE
Write Admin/Contribution Guide for Yari

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1113]
For each item in the current Wiki-focused MDN admin guide and contribution guide, we need a corresponding item in the Yari admin guide, so that writers can look up common and uncommon steps they need to do their job. Includes tagging, the summary and all other front-matter, renaming and redirecting, on how to create the TOC (manually inserting IDs?).

Side benefit: this will allows us to be aware of any dissonance between Yari/Kuma and whether workarounds are available, or new features required.

NOTE: @tobinmori and @atopal started on this, but it needs to be completed.

**Comment by atopal** [comment]
The documents are here: https://docs.google.com/document/d/1SYuuCHrO0T9lYuI9AwcEA0R6bY6hVWd89VZJ_LqQWn8/edit#
and here: https://docs.google.com/document/d/1p7omstmMRW0WxT_uS6m8qS-B-kMl9nRCC9NW6ctTwSo/edit#

There is surprisingly little missing, but that might also be because the Kuma admin guide was not complete.

**Comment by escattone** [comment]
After taking a quick look at the admin guide, I think it's a fairly small task to update it to reflect the current plan for Yari.

**Comment by escattone** [comment]
Much of this doesn't or won't make sense any longer.
