### ISSUE TITLE
Link styles

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1173]
Implement consistent in-page link styling which includes:

- Colour
- Iconography  and styling for special link types such as `external` and `mailto`
- Interaction style

All of this to be [driven from `mdn-minimalist`](https://github.com/mdn/mdn-minimalist)

**Comment by peterbe** [comment]
@escattone @schalkneethling Is it just me? The fact that `code` is black and underlined whereas regular links are blue and not-underlined. It looks inconsistent and weird. The blue links existing trains my mind to think that they are clickable. Then, that makes me think that anything that isn't blue isn't clickable. That's why it's surprising when you hover over the `<code>` tags that they are actually links. 
<img width="1708" alt="Screen Shot 2020-12-02 at 8 35 33 AM" src="https://user-images.githubusercontent.com/26739/100879764-d68a3100-3479-11eb-80a2-a5af09a73b08.png">


I think we should do like Kuma and GitHub Docs does. Consistency between `<a>` and `<a><code>`. Always blue and underlined when you hover over them. 
<img width="765" alt="Screen Shot 2020-12-02 at 8 40 32 AM" src="https://user-images.githubusercontent.com/26739/100879914-0b968380-347a-11eb-8b7e-d87d4fa3d67d.png">

On Web.dev they're also consistent. 
<img width="851" alt="Screen Shot 2020-12-02 at 8 40 51 AM" src="https://user-images.githubusercontent.com/26739/100879936-17824580-347a-11eb-907b-bc7a7984d84e.png">

Unlike Kuma and GitHub Docs, Web.dev uses blue *and* underline and when you hover over the underline disappears. 
I'm not in a position to back a design choice on that dimension but I definitely think we should fix our `<a><code>` so they are consistent.

**Comment by mattiapontonio** [comment]
I like web.dev.
I thing the selector should be
`pre code a`

So theorically: 
- `font-family` comes from `pre`
- `color` comes from `a`
- `text-decoration` comes from `a` 

Even without indenting them in Sass, a general style for the tag and the right HTML should works.
