### ISSUE TITLE
IncludeSubnav MacroExecutionError

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1187]
On http://localhost:3000/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript#_flaws
<img width="1147" alt="Screen Shot 2020-08-27 at 2 22 13 PM" src="https://user-images.githubusercontent.com/26739/91480276-bcd0c080-e870-11ea-9664-2ea6fa02be1f.png">

It just says `{{IncludeSubnav("/en-US/docs/Games")}}` in the rendered output.

**Comment by peterbe** [comment]
Seems to happen on any of the Games subpages. E.g. http://localhost:3000/en-US/docs/Games/Techniques#_flaws

**Comment by escattone** [comment]
@peterbe I'm finally looking at this one again, and I remember it. This is a content problem, because the `/en-US/docs/Games` page doesn't have an element with an `id` of `Subnav`. It's also failing in Kuma, but silently, since the `IncludeSubnav` macro in Kuma just returns an empty string. This is another case where Yari is better, because it doesn't hide the problem, but on the downside, we need to address it since the failure leaves the failed macro call as residue in the document.

I'm almost certain the solution for this one is to delete all of the `{{IncludeSubnav("/en-US/docs/Games")}}` macro calls across all pages, because:
1. They always fail. They literally do nothing.
2. They're meant to include the sidebar from the `/en-US/docs/Games` page, but that's already being generated by each page's call to `{{GamesSidebar}}`.

cc'ing @chrisdavidmills to confirm

**Comment by chrisdavidmills** [comment]
@escattone yeah, this sounds like the correct fix to me. I don't recall why we have both of those macro calls on the page.

I've tried removing the includesubnav call from the page in question (https://wiki.developer.mozilla.org/en-US/docs/Games/Techniques), and Ryan is correct, it makes no diffrence.

**Comment by escattone** [comment]
Thanks for the feedback @chrisdavidmills!

**Comment by escattone** [comment]
FYI. I just removed all `{{IncludeSubnav("/en-US/docs/Games")}}` macro calls within the MDN Wiki. I also updated the content repository as well (https://github.com/mdn/content/pull/61), just so we don't have to wait for a refresh from the Wiki to get rid of this error. This is therefore resolved.

**Comment by chrisdavidmills** [comment]
@escattone rar, top macro massacring action ;-)
