### ISSUE TITLE
Styling links in sidebar

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#122]
In the `related_content` from the packaged JSON from `stumptown-content` you get things like this:
```
    {
      "title": "<table>: The Table element",
      "mdn_url": "https://developer.mozilla.org/docs/Web/HTML/Element/table"
    },
```
On the site, in the side bar, it appears like this:
<img width="323" alt="Screen Shot 2019-09-18 at 10 33 42 AM" src="https://user-images.githubusercontent.com/26739/65158120-d716e300-d9ff-11e9-9a3d-d6002cd6fe60.png">

On developer.mozilla.org it appears like this:
<img width="499" alt="Screen Shot 2019-09-18 at 10 34 59 AM" src="https://user-images.githubusercontent.com/26739/65158238-0168a080-da00-11e9-88a1-cb84a1110762.png">

It's basically stripping everything after the `>`  character. **Is that a safe assumption?**

The other noticeable difference is that `stumptown-content` comes with 0 styling preferences. It's just text. 

It would be easy to write something like this:

```javascript
if (/^<[\w-]+>:/.test(node.title)) {
  // Drop everything except the "<tag>" and display as <code>
  return <Link to={node.uri}><code>{node.title.match(/^(<[\w-]+>):/)[1]}</code></Link>
} else {
  // Leave as is
  return <Link to={node.uri}>{node.title}</Link>
}
```

But that feels "oversteppingly" simplified and just a single solution for the HTML elements.

**Comment by peterbe** [comment]
Another option, other than the regex hack, would be that stumptown does something like this in `related_content`:

```
    {
      "long_title": "<table>: The Table element",
      "title": "<table>",
      "is_code": true,
      "mdn_url": "https://developer.mozilla.org/docs/Web/HTML/Element/table"
    },
```

And the renderer...
```jsx
<Link to={node.uri} title={node.long_title || node.title}>
  {node.is_code ? <code>{node.title}</code> : node.title}
</Link>
```

But should `stumptown-content` get that involved in the styling?  

Thoughts @wbamberg ?

**Comment by wbamberg** [comment]
There are a couple of bits to this which I'd like us to treat separately:

1. titles that are too long to fit in the sidebar
2. code formatting for titles

First is the issue that titles are too long to work well in the sidebar.

> It's basically stripping everything after the > character. Is that a safe assumption?

I don't think we should do this. I think stumptown-content should give you `title` and `short_title` or something. Probably `short_title` should be optional, and you should use it in sidebars (and possibly other suitable contexts) if it is present, and fall back to `title` otherwise. We have an issue for this: https://github.com/mdn/stumptown-content/issues/76 and I'm going to work on it in this sprint (probably today).

Second, code formatting. Honestly I think it would be fine to render the HTML elements in the sidebar without code formatting. I think it's a bit weird, MDN's obsession with code formatting everywhere. And we don't use code formatting for the "\<div\>" in titles like ["\<div\>: The Content Division element"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div), or in breadcrumbs. So my preference, for now, would be to treat them just as text.

But if we did want to format titles (and short titles), my preference would be to make them HTML in the JSON, and treat them as HTML in the renderer.

**Comment by peterbe** [comment]
> But if we did want to format titles (and short titles), my preference would be to make them HTML in the JSON, and treat them as HTML in the renderer.

Just a quick note about that, if the entry has a `node.title` *and* `node.short_title` you'd be able to do this:
```jsx
<Link to={node.uri} title={node.short_title && node.title && node.short_title !== node.title && node.title}>{node.short_title || node.title}</Link>
```
That way, displayed is the short title and the tooltip when you hover over the link would be the full title.

**Comment by peterbe** [comment]
This dates back to the very early days of stumptown-renderer when we did things differently. To fix *this* issue goes deeper into sidebar macros.
