### ISSUE TITLE
The live samples in some documents seem to be broken

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#12215]
### Summary

Some live samples in ["Making decisions in your code — conditionals"](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals) seem to be broken.

Check the _screenshot_ section.

### URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals#active_learning_more_color_choices

### Reproduction steps

1. navigate to the "Active learning: A simple calendar" section
2. Check the live samples

### Expected behavior

The live samples are work well, I've checked the page built by `@mdn/yari@v2.65.1` (run `yarn start` in mdn/content` folder):

![image](https://github.com/user-attachments/assets/522e2829-afe6-4b7f-a753-9e043eaa1cba)

### Actual behavior

See the _screenshot_ section.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Screenshot

![image](https://github.com/user-attachments/assets/408c4b9d-60b9-4aca-a089-cccb7d038dfd)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by fiji-flo** [comment]
Thanks for reporting. I didn't expect this worked previously. That's because

```
<script>
  const script = "<script></script>";
  const h1 = "<h1>H1</h1>";
</script>
```

will render:
![image](https://github.com/user-attachments/assets/29d04cba-944d-4e2d-be78-907ea9326b51)


We now do real templating so the `js` parts ends up in a `<script>` just before the body ends. Allowing real DOM events.


We need to settle on how we want to deal with this. The easiest way is to escape the script tag like:

```
<script>
  const script = "<script><"+"/script>";
  const h1 = "<h1>H1</h1>";
</script>
```
or 
```
<script>
  const script = `<script><${"/"}script>`;
  const h1 = "<h1>H1</h1>";
</script>
```

https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/conditionals/index.md?plain=1#L610

**Comment by argl** [comment]
Fixed in this [PR](https://github.com/mdn/content/pull/37105)
