### ISSUE TITLE
Thoughts on adding direct-links to heading tags within article content?

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#1427]
@tannerdolby commented on [Wed Oct 07 2020](https://github.com/mdn/sprints/issues/3757)

## URL(s)
[Content Categories - MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories)

## Request type

- [x] Correction or update

## Details

Hello, MDN team. I'm not so sure this is an issue or problem but something I wanted to ask your team about. 

I originally noticed it on this page [Content Categories - MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories) but I think it applies to all pages within `/docs/Web/`. I wanted to click on the section heading, [Palpable content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Palpable_content) to get a direct link to this section without having to scroll down from [Content Categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Main_content_categories). I inspected the page and copied the corresponding id selector `#Palpable_content` and pasted it to the end of the page URL to provide a "direct-link" to that sections content.

I do recognize the "On this page" section containing direct links to main headings of the page in that unordered list which is very helpful. But for sections with more content that require the user to scroll further down the page, this is where I think potentially having direct links on some of the subheadings in long categories could be useful for people sharing links to specific sections within MDN docs.

### Proposed update: 
1. Create direct links for section headings that are further down from the "On this page" direct links. Allowing for a direct link to that section heading to be produced in the browsers address bar upon clicking the `.direct-link` element nested in the heading for fast internal linking. I used the hashtag character as the anchors value (which could also be an SVG if there is a specific icon wanting to be used) within the direct link screen shot I attached below.

The `.direct-link` anchor elements could be fully visible or visually hidden from the screen with good ole `visibility: hidden` or potentially a fancier way of visually hiding using absolute positioning and translate. 

The `.direct-link` element could then become visible upon hovering the heading element and allow for a quick click to update the page URL with a direct link to that specific section heading.

```
<h3 id="Palpable_content">Palpable content <a class="direct-link" href="https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Palpable_content">#</a></h3>
```

## Screenshot with direct link visible for Palpable content heading: (no styling or margins currently applied)
<img width="708" alt="Screen Shot 2020-10-06 at 4 02 18 PM" src="https://user-images.githubusercontent.com/48612525/95269038-6c446f80-07ed-11eb-98e6-11cf0c4c73b1.png">

Let me know your thoughts!

---

@chrisdavidmills commented on [Wed Oct 07 2020](https://github.com/mdn/sprints/issues/3757#issuecomment-704711601)

Hi @tannerdolby !

Yes, I agree this would be nice, and in fact we did have this at some point, but I think it was disabled in the "viewer" front-end because of some kind of performance reason. If you look at the "wiki"/"edit" version of the page (https://wiki.developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories), you'll see the feature active there.

I think it'd be good for us to have this feature sorted out again at some point soon in the final UI, therefore I'm going to move your issue over to the platform (kuma) repo so I can add your voice to the discussion. Thanks for speaking up.

**Comment by tannerdolby** [comment]
Hey, Peter. Thank you for the clear explanation! I found a sandbox environment to mess around in and came up with this prototype for the `cheerio` portion. (Probably flawed but I can build upon and improve).

Now I need to focus on steps 1 and 2. Could you direct me to where `syntaxHighlight()` or `injectNoTranslate()` are located in the project? If I can find those, then I could test out passing the cheerio object in to mutate it in-place and then loop over with `.each()`. 

### Prototype cheerio object out to HTML-string
Here is my current prototype for handling a single HTML string `<h3>Sub header</h3>/n<p>Bla bla</p>`. I found `cheerio` has a `.serialize()` method but I wasn't sure how to go about the deserialize/serializer parts.

I attempted to mimic `generateUniqueH3ID` (ie on [Yari Content Categories page](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Guide/HTML/Content_categories#Metadata_content) the ID selector syntax was `id="Metadata_content"`, to help with testing the `.each()` loop.

```js
const $body = $('body'); // for my testing

// deserialize HTML string to cheerio object $blob
const $blob = $('<h3>Metadata content</h3>\n<p>Bla bla bla</p>');

// Title case first letter .. lower case replace spaces with underscores for snake_case
function uniqueH3ID(id) {
  return id.charAt(0).toUpperCase().concat(id.split(" ").join("_").slice(1).toLowerCase());
}

$blob.each((i, header) => {
    const $header = $(header);
    // bad but works for now
    const $h3 = $header.filter('h3');
    const $a = $header.filter('a');

    // come back to conditional statement
  
    // using $header.attr('id', ..) was applying to the <p id="#${id}-${i}"> from its .text() since it is apart of the original HTML string
    var id = uniqueH3ID($header.text()); // mimic generateUniqueH3ID
    $h3.attr('id', `#${id}-${i}`);
    $a.attr('id', `#${id}-${i}`);

    var link = $(tag('a', {href: `#${id}-${i}`}, $h3.text()));
    $h3.text(""); // empty textContent for h3 
    $h3.prepend(link); // prepend the link to the start of h3

    $body.append($header); // append to <body> or whevever it needs to go
});
```

Raw output

```html
<body>
    <h3 id="#Metadata_content-0"><a href="#Metadata_content-0">Metadata content</a></h3>
<p>Bla bla bla</p>
</body>
```

Which gives as shown above, the HTML string. This doesn't have the \n character shown after `</h3>\n` but uses it and shifts the paragraph content to the next line. This may be an issue.

```html
<h3 id="#Metadata_content-0"><a href="#Metadata_content-0">Metadata content</a></h3>
<p>Bla bla bla</p>
```

### Notes
When adding more than one subheading/paragraph pair inside the HTML string to `$blob` ie,

```js
const $blob = $('<h3>Metadata content</h3>\n<p>Bla bla bla</p><h3>Different content</h3>\n<p>Bla bla bla</p>');
```

The current implementation is a bit messed up from my logic (i'm assuming) in the `.each()` loop and the index variable is off. 

```html
<h3 id="#Metadata_content-0"><a href="#Metadata_content-0">Metadata content</a></h3>
<p>Bla bla bla</p><h3 id="#Different_content-3"><a href="#Different_content-3">Different content</a></h3>
<p>Bla bla bla</p>
``` 

I filter `$header` for `<h3>` and `<a>` tags to set `id` selectors because using `$header` was applying `id` stuff to the paragraph tags since its `.contents()` contain the `<p>` tags. I think this is where the index variable is counting the `<p>` tags in the `id="#${id}-${i}` raw output and causing the out of order.

**Comment by peterbe** [comment]
Regarding where `syntaxHighlight` is, to make a contribution you'll need to get Yari up and running your laptop. Then you'll be able to grep and search for where functions like that are and you can read then to see how they do things. You'll also need this to be able to set up so you can write automated tests to go with your pull request. And just being able to have the whole system running on your laptop means you can test any odd page all in your browser on http://localhost:3000.

My first impression of your thoughts is: Yes! You're on the right track!
I think you should write your algorithm so the ID doesn't include a number less it has to. I.e. an end result like this:
```html
<h3 id="examples"><a href="#examples">Examples</a></h3>
<p>...</p>
<h3 id="something_else"><a href="#something_else">Something else</a></h3>
<p>...</p>
<h3 id="examples_2"><a href="#examples_2">Examples</a></h3>
<p>...</p>
```
(also, note that I'm recommending you make your solution force the ID into lowercase)

By mindful that what's in the `<h3>`'s text might not always make for a valid ID. For example:
```html
<h3>99 Balloons</h3>
<p>...or...</p>
<h3><svg>...</svg> SVGs</h3>
<p>...or...</p>
```

Please have a go and I'll guide if you get stuck. It's really actually pretty straightforward once you get a bit into it. What's a bit challenging is that there are sooooo many different documents and some of them have crappy HTML.

**Comment by peterbe** [comment]
Hmm... It seems a lot of content has already manually had `id`s manually entered on a lot of `<h3>` documents. 
E.g. https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/configuring_server_mime_types/index.html
Note that it even has them on `<h4>` tags. 

I've never fully understood what that `name` attributes are. See 
```html
<h3 id="Technical_Background" name="Technical_Background">Technical Background</h3>
```
...for example. [line 29](https://github.com/mdn/content/blob/9cebe14a501b213b23a677090e616f05d4149493/files/en-us/learn/server-side/configuring_server_mime_types/index.html#L29).

Anyway, I think if you come across one of these `<h3>` elements that already has an `id` then it's best to just leave it. Feels saner and safer. 
But what you could is to convert it still into:
```html
<h3 id="Technical_Background" name="Technical_Background"><a href="#Technical_Background">Technical Background</a></h3>
```

@escattone Can you explain why a lot of headings have a `name`? Is it something something complicated related to live samples or translations maybe?

**Comment by escattone** [comment]
@peterbe The `name` attribute was added to override the default mechanism where the auto-generated `id` of a header attribute is taken from the text content of the header (with special characters removed and space replaced with underscores). If the header has a `name` attribute, its value is used (without any modification) to create the `id` for the header (i.e., the text content of the header is ignored when creating the `id` attribute).

**Comment by peterbe** [comment]
But what's the point of a `name` attribute if the `<h3>` already has an `id` attribute?

Either way @tannerdolby I think, the times when `<h3>` tags have a `name` attribute, they most likely also have an `id`. But if they don't and you're confronted with `<h3 name="some_thing">Other thing</h3>`, write your business logic so that it becomes `<h3 id="some_thing" name="some_thing"><a href="#some_thing">Other thing</a></h3>`. That seems fair.

**Comment by escattone** [comment]
> But what's the point of a `name` attribute if the `<h3>` already has an `id` attribute?

@peterbe I'm not saying it's a good thing, but our current, ancient approach has been that we have always ignored any existing `id` attributes on headers, and overwritten them with our own auto-generated `id` attribute (taken from the header text but with special characters removed and spaces converted to underscores), except if there's a `name` attribute, then we've used that directly. It's definitely an area that we should improve, which will be so much easier to do after we launch Yari.

**Comment by tannerdolby** [comment]
@peterbe I've got Yari running locally on port 3000. After I used the correct `export CONTENT_ROOT=~/content/files` to the `mdn/content` the whole Yari/Content system is working smoothly. (no errors when viewing different pages). 

I was able to track down `syntaxHighlight` within `/build/index.js` and `syntax-highlight.js` using `git grep -n "syntaxHighlight("`. I've used Prism before for highlighting `<pre>` tags and after looking through `syntax-highlight.js`, I thought maybe creating something similar to highlight `<h3>` tags and apply the direct link could be the right direction.

To then export with `module.exports = { headingHighlight }` and use in `index.js` specifically in the `buildDocument` async function like `syntaxHighlight` is being used. This might be wrong, but I started trying things.

Addressing the duplicate ID issue, I forced the `uniqueH3ID` output to be lowercase like you mentioned and number less unless it is indeed a duplicate ID and needs a number to be unique. I tested this solution out in the `cheerio` sandbox environment I've been using.

#### Input HTML
```html
<h3 id="metadata_content">Some other example</h3>
<h3 id="metadata_content">Some cool text</h3>
<h3 id="metadata_content">Some blue text</h3>
```

#### cheerio
```js
const presetID = $header.attr("id");
const duplicateID = $(`h3[id=${presetID}]`);

if ($header.attr("id") && duplicateID.length > 0) {
    const matchedID = $header.attr("id", `${presetID}_${i}`);
    link.attr("href", `#${presetID}_${i}`);
    $header.text("");
    matchedID.prepend(link);   
}
// rough fix for the above logic
if ($header.attr("id") === `${presetID}_0`) {
    $header.attr("id", `${presetID}`);
    link.attr("href", `#${presetID}`);
}
```

#### Raw output HTML
```html
<h3 id="metadata_content"><a href="#metadata_content">Some other example</a></h3><h3 id="metadata_content_1"><a href="#metadata_content_1">Some cool text</a></h3><h3 id="metadata_content_2"><a href="#metadata_content_2">Some blue text</a></h3>
```

This works for one duplicate ID within any `<h3>` tags but when I add another subheading with duplicate ID (and a different id value) to the HTML, the index variable goes to `<h3 id="new_duplicate_id_3">` instead of restarting back to 1 for new duplicate ID values. I can tinker with it, ie if a `<h3>`s duplicate id value is different from another duplicate then set the index back to `id=“new_dupl_id_1”`.

### Handling `name` attributes
For the subheadings with `name`, this logic handles the correct transformation. (maybe remove special characters with regex and replace space with underscores in `uniqueH3ID` would be more sturdy).

#### Input HTML
```html
<h3 name="some_name">Some thing</h3>
<h3 name="another_name">Another thing</h3>
```

#### cheerio
```js
if ($header.attr("name")) {
    const name = $header.attr("name");
      	
    link.attr("href", `#${name}`);
    $header.attr("id", `${name}`);
}

```

#### Raw output HTML
```html
<h3 name="some_name" id="some_name"><a href="#some_name">Some thing</a></h3><h3 name="another_name" id="another_name"><a href="#another_name">Another thing</a></h3>
```

### Regarding the sub headings with .text() that wouldn't make for a valid ID

> By mindful that what's in the `<h3>`'s text might not always make for a valid ID.

I’m still figuring this out. If the `<h3>`'s text is not valid, should I write logic to where an id is generated like `id="desc_content_99_ballons"` or something of that nature, `id="desc_content_svgs"` to still allow the sub heading to have a direct link added if the `$(‘h3’).text()` isn’t a valid ID format? This has become quite long, so I'm going to start a new comment for my questions on testing in Yari locally.

**Comment by peterbe** [comment]
I haven't carefully read your comment yet. But I skimmed it and something that stood out is that it might that the sample input HTML is not realistic. 
If the input HTML is:
```html
<h3 id="metadata_content">Some other example</h3>
<h3 id="metadata_content">Some cool text</h3>
<h3 id="metadata_content">Some blue text</h3>
```
I think nothing should be done. Yes, it's nuts that the same `id` value is repeated and that's something we need to deal with, but it's a story for another day. We have a system called "flaws" which deals with finding things like that. 

A more realistic input would be:
```html
<h3>Some other example</h3>
<h3>Same text</h3>
<h3 id="blabla">I already have an ID</h3>
<h3>Same text</h3>
```

With an input like that, your output should something like:

```html
<h3 id="some_other_example"><a href="#some_other_example">Some other example</a></h3>
<h3  id="same_text"><a href="#same_text">Same text</a></h3>
<h3 id="blabla"><a href="#blabla">I already have an ID</a></h3>
<h3 id="same_text_2"><a href="#same_text_2">Same text</a></h3>
```

I.e. If the `h3` has an `id` already, keep it. Don't touch it. 
If the `h3` texts are repeated, increment the normalized ID. 

Stay away from the `name` attribute entirely. Pretend it doesn't exist. As Ryan pointed out, it's a relic of the past but it was ultimately just there to help set the `id`. 

Does that simplify the task a bit?

**Comment by Ryuno-Ki** [comment]
The cheerio selector would be `h3:not([id])` then?
It would select all `h3`s without an ID attribute.

**Comment by tannerdolby** [comment]
Yes that simplifies things a bit more. I thought maybe the input was a bit unrealistic, since having duplicate `id` attributes is considered invalid HTML. But yes, a story for another day.

I've forgotten about `name` attributes and cleaned up the logic in the `.each()` loop. It handles the input HTML as intended now. Any bare subheadings like `<h3>Text</h3>` and tags that already have an id, `<h3 id="blabla">Some text</h3>` are converted correctly.

More realistic input
```html
<h3>Some other example</h3>
<h3>Same text</h3>
<h3 id="blabla">I already have an ID</h3>
<h3>Same text</h3>
<h3>Some other example</h3>
```

Simplified `cheerio` code. I had a bit of trouble filtering the `<h3>`'s with the same text but ended up finding a way that worked using, ```$(`h3:contains('${$header.text()}')`).eq(1);```. Hopefully there aren't more than two duplicate sub headings but if there are, this logic will need to be updated.

```js
$h3.each((i, header) => {
    const $header = $(header);
    
    // if id exists use it for anchors href
    if ($header.attr('id')) {
      	var id = $header.attr('id');
      	var link = $(tag('a', {href: `#${id}`}, $header.text()));
      	
      	$header.attr("id", `${id}`);
      	$header.prepend(link);
      	$header.text("");
    } else {
      	var id = uniqueH3ID($header.text());
      	var link = $(tag('a', {href: `#${id}`}, $header.text()));
      	var duplicate = $(`h3:contains('${$header.text()}')`).eq(1);
        var i = 2;
      	
        duplicate.attr('id', `${id}_${i}`);
        $header.attr('id', `${id}`);
        $header.text("");	
    }
    $header.prepend(link);
    $body.append($header);
});

```
And the correct output

```html
<h3 id="some_other_example"><a href="#some_other_example">Some other example</a></h3>
<h3 id="same_text"><a href="#same_text">Same text</a></h3>
<h3 id="blabla"><a href="#blabla">I already have an ID</a></h3>
<h3 id="same_text_2"><a href="#same_text_2">Same text</a></h3>
<h3 id="some_other_example_2"><a href="#some_other_example_2">Some other example</a></h3>
```
I'm now trying things in Yari locally to see if I can utilize `headingHighlight` in a similar fashion as `syntaxHighlight` to highlight all `<h3>`'s and add the direct links.

**Comment by tannerdolby** [comment]
It's working! I've successfully added direct links to all `<h3>`'s by utilizing `headingHighlight`. 

I created a file `heading-highlight.js` with similar structure to that of `syntax-highlight.js` and then used it in `index.js` as `headingHighlight($, doc)` within the `buildDocument` function. I checked around on a few different pages and the `<h3>` elements are all working as intended.

Running `yarn dev` finds zero errors and compiles successfully, starting up the local development server. No flaws at the moment on page `/en-US/docs/Learn/Getting_started_with_the_web`. Now that I've got the direct links working in Yari, I think its time to start writing automated tests. Let me know your thoughts! 

### Sub heading with direct link in my local version of Yari 

<img width="326" alt="Screen Shot 2020-10-22 at 2 11 52 AM" src="https://user-images.githubusercontent.com/48612525/96850760-0b7f7e80-140c-11eb-9757-61f99db73da1.png">

Note: (My mouse is hovered over the subheading in screenshot making `text-decoration: underline` appear)

With the following HTML:

```html
<h3 id="html"><a href="#html">HTML</a></h3>
```

**Comment by peterbe** [comment]
Before I forget, one realistic input is:
```html
<h3>123 IDs can't start with numbers</h3>
```
This *can't* become 
```html
<h3 id="123_ids_cant_start_with_numbers"><a href="123_ids_cant_start_with_numbers">123 IDs can't start with numbers</a></h3>
```
Perhaps the simplest solution is to inject a `_` if the first character of the generated ID starts with a character that isn't `[a-z]`. E.g.

```html
<h3 id="_123_ids_cant_start_with_numbers"><a href="_123_ids_cant_start_with_numbers">123 IDs can't start with numbers</a></h3>
```
See if you can research up the current rules about what a valid ID has to be for a DOM.

**Comment by Ryuno-Ki** [comment]
> Note: (My mouse is hovered over the subheading in screenshot making text-decoration: underline appear)

Hint: In the [CSS pane](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector) there's a `:hov` next to `.cls` (not in the screenshot linked).
Clicking that allows you to set different pseudo selectors like `:hover`.

> Perhaps the simplest solution is to inject a _ if the first character of the generated ID starts with a character that isn't [a-z].

What about non-Latin characters? Would `.toLowerCase()` on `\w` work, too?

**Comment by tannerdolby** [comment]
@peterbe I researched the HTML spec and found rules for valid `id` attributes. 

The [HTML 4.01 spec](https://www.w3.org/TR/html401/types.html#type-name) states that ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (-), underscores (_), colons (:), and periods (.). Some more stuff on [MDN -Global Attribute (id)](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).

In [HTML5](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute), some restrictions were lifted for the `id` attribute.

- There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

> Perhaps the simplest solution is to inject a _ if the first character of the generated ID starts with a character that isn't [a-z].

This would be valid, as of HTML5 to inject an underscore `_` at the beginning of the `id` attribute if the first character isn't [a-zA-Z].

**Comment by tannerdolby** [comment]
I wrote this `cheerio` logic to handle `id`'s starting with non-letter characters. The `else-if` could probably be removed unless you think an `<h3>` tag would already have a manually set `id` starting with numbers `<h3 id="123_manually_set">Some heading</h3>`

```js
// if first character of an ID doesn't start 
// with [a-zA-Z] then inject an underscore
const regExp = new RegExp(/^[^a-zA-Z]+/, "g")
if (regExp.test($header.text())) {
    var id = uniqueH3ID($header.text());
    $header.attr('id', `_${id}`);
} else if (regExp.test($header.attr('id'))) {
    var id = $header.attr('id');
    $header.attr('id', `_${id}`);
}	
// input: <h3>123 IDs can't start with numbers</h3>
// output: <h3 id="_123_id_starts_with_numbers"><a href="#_123_id_starts_with_numbers">123 id starts with numbers</a></h3>
```

**Comment by Ryuno-Ki** [comment]
@tannerdolby 
> @Ryuno-Ki Thanks for the info about the CSS Pane.

You're welcome.

> I've noticed using .toLowerCase() on non-latin characters can return different lengths.

Oh, right. There was something.

**Comment by tannerdolby** [comment]
@Ryuno-Ki 
> Oh, right. There was something.

Yeah there is a problem with characters being counted twice when using `toLowerCase` on non-latin characters. I will make sure to write tests for this specific case.

That being said, I'm new to writing automated tests so bear with me. I found the directory `yari/testing/tests/` which looked to be where some tests were being run. I saw the `index.test.js` file contains `cheerio` code being tested with Jest.

Should I be using the same `test()` and `expect()` syntax for testing my code?

**Comment by tannerdolby** [comment]
Aside from the automated tests, I think I could submit a PR for review. My local setup is looking like this:

1. Create `heading-highlight.js` in `/yari/build/` to highlight all `<h3>` tags and create the direct link.
```js

/**
 * Create a unique lowercase and snake_case
 * ID from the sub heading inner text content.
 * 
 */
function uniqueH3ID(id) {
    return id.toLowerCase().split(" ").join("_");
}

/** 
 * Mutate the $ instance by looking for <h3> tags that can
 * be converted into direct links.
 * 
*/
function headingHighlight($, doc) {
    $('h3').each((i, header) => {
        const $header = $(header);

        // if first character of an ID doesn't start 
        // with [a-zA-Z] inject an underscore
        const regExp = new RegExp(/^[^a-zA-Z]+/, "g")
        if (regExp.test($header.text())) {
            var id = uniqueH3ID($header.text());
            $header.attr('id', `_${id}`);
        } else if (regExp.test($header.attr('id'))) {
            var id = $header.attr('id');
            $header.attr('id', `_${id}`);
        }
        
        // if id exists use it for anchors href
        if ($header.attr('id')) {
            var id = $header.attr('id').toLowerCase();
            var link = $(`<a href='#${id}'>${$header.text()}</a>`);
            
            $header.attr("id", `${id}`);
            $header.prepend(link);
            $header.text("");
        } else {
            var id = uniqueH3ID($header.text());
            var link = $(`<a href='#${id}'>${$header.text()}</a>`);
            var duplicate = $(`h3:contains('${$header.text()}')`).eq(1);
            var i = 2;
            
            duplicate.attr('id', `${id}_${i}`);
            $header.attr('id', `${id}`);
            $header.text("");	
        }

        $header.prepend(link);

        return;
    });
}

module.exports = { headingHighlight };

```

2. Use `headingHighlight` in the async `buildDocument` function within `/yari/build/index.js`
```js
  // Add direct links to all <h3> tags.
  headingHighlight($, doc);
```

**Comment by peterbe** [comment]
Go for it! Once you make it a PR, I'll comment on individual lines. Take your time and test it carefully.

**Comment by tannerdolby** [comment]
@peterbe Ok thanks! I'm all up to date with the upstream repo and plan to submit a PR later today.

**Comment by tannerdolby** [comment]
Question: While testing, I noticed some `<h3>` tags have textContent with words separated by hyphens, for example 

```
<h3 id="third-party_tools"><a href="#third-party_tools">Third-party tools</a></h3>
```

Would you suggest keeping the hyphen in the `id` like `<a href="#third-party_tools">` or omit the hyphen to be `<a href="#third_party_tools"`? I think removing the hyphen for `<h3>` text feels wrong since I'm changing the grammar but having all underscore separated words seems more uniform. Let me know your thoughts!

**Comment by peterbe** [comment]
No, keep the hyphen untouched. Treat it like any other character. Just like `p` or `w`. 

By the way, before you submit your PR, consider whether it should be:
```html
<h3 id="Title"><a href="#Title">Title</a></h3>
```
...instead of...
```html
<h3 id="title"><a href="#title">Title</a></h3>
```

I can't remember exactly why but it seems that `<h2>` tags keep the case of the `<h2>` content.

**Comment by tannerdolby** [comment]
@peterbe I see your work in #1811 will probably make the above PR I submitted obsolete. Let me know your thoughts.
