### ISSUE TITLE
*.content.dev.mozit.cloud is always the same as main.content.dev.mozit.cloud

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1471]
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/video/index.json works.
But https://lazy-load-all-bcd-tables.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/video/index.json doesn't actually serve up the files from the S3 bucket prefix: https://s3.console.aws.amazon.com/s3/buckets/mdn-content-dev/lazy-load-all-bcd-tables/?region=us-west-2&tab=overview

Besides if you mess with the domain and replace `main.` with `blablable.` it doesn't fail. It ought to 404.

**Comment by escattone** [comment]
This is fixed. I forgot to add the `Host` header to the caching policy of the default behavior, which is essential since we vary the response based on the value of the `Host` header. This only affects the CDN for the `dev` environment. It is not needed to `stage` and `prod`, since their responses will not vary on the value of the `Host` header.
