### ISSUE TITLE
Can we move all build artifacts at the root level (*.png, *.json, *.ico, *.js) into the static/ folder?

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1477]
There is a small set of build artifacts at the root level:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/3743693/96313270-65beb080-0fc2-11eb-832c-603964ac54ab.png">

and these complicate how we create CloudFront behaviors to best serve these files. It would help immensely if all of these files could be moved under the `static` folder. Can we do that easily?

**Comment by peterbe** [comment]
We chatted about this and eventually came to a vague conclusion:

1. Let's try out the idea of instead having strict CF behaviors dedicated to prefixes like `/api/v1/` and all the other 100% Kuma related (possibly a future `/api/serverless` also) that is strictly no S3 lookups and no caching at all. Just a gaping hole from the user straight to Kuma and back. 
2. If that simplifies and gives comfort perhaps we can treat all other things as simply a "1) in S3?, 2) no? fall back on Kuma"
This way we *might* be able to treat all of the following identically: 
* `/sitemap.xml`
* `/sitemaps/*`
* `/static/js/foo.js`
* `/favicon.ico`
* `/*/docs/*`

Lastly, the original request, filed in this issue, *can* be pretty much accomplished. The only outliers (that have to sit at the root) is the `/favicon.ico` and `/contribute.json` (and a future `/robots.txt`) because these are based on conventions and not something we control from our template.

**Comment by escattone** [comment]
@peterbe Thanks for the nice summary of our conversation. I think I've got the CloudFront behaviors configured without needing this, so closing this issue.
