### ISSUE TITLE
Support Google Analytics for the production builds

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1533]
When building documents for the production environment, we need to support Google Analytics.

**Comment by peterbe** [comment]
Drive-by comment... I think we should strive for simplicity in that we shouldn't have too many variations of a build. In general. As a principle. However, exceptions must be made. 
But what it might mean is that we don't try to omit the Google Analytics code from builds such as https://main.content.dev.mdn.mozit.cloud and https://yari.stage.mdn.mozit.cloud. 
And maybe even for https://some-experimental-branch.content.dev.mdn.mozit.cloud
Because, after all, Google Analytics does a good job of filtering out pageviews that come in a domain that *isn't* `developer.mozilla.org`.

I think what I'm suggesting is that we put in something like:
```
export BUILD_INCLUDE_GOOGLE_ANALYTICS=true
```
into the Production Build workflow independent of which deployment prefix or which branch gets built.

**Comment by peterbe** [comment]
Actually, more specifically, it might be better to do something like:
```
export GOOGLE_ANALYTICS_ACCOUNT=UA-36116321-5
```
instead of just a bool.
