### ISSUE TITLE
[HTML docs] Subtopics are misaligned

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1559]
**Steps to reproduce:** 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/HTML#Brief_history
2. Scroll down to 'Block' topic and compare to topic alignment on https://developer.mozilla.org/en-US/docs/Glossary/HTML

**Actual results:**
Subtopics are aligned with topics. 
![image](https://user-images.githubusercontent.com/53306802/97487808-09667400-1966-11eb-9987-67a6479b20ef.png)

**Expected results:**
Subtopics are aligned more to the right, under the same head topic, as on current pages. 
Also notice that 'Related Topics' header is missing on the unreleased docs. 

NOTE: this applies to **Block, Media, Node, Property and Signature** topics.

**Comment by peterbe** [comment]
Uh? Here's what I see:
<img width="919" alt="Screen Shot 2020-10-28 at 4 48 42 PM" src="https://user-images.githubusercontent.com/26739/97494987-7ca7c000-193d-11eb-95eb-3fe10f6766e9.png">

So there's definitely indentation but it's still looking a bit wonky since the distance between the 

```
Block
    Block
    ...
```

...is different from all the other vertical distances.

**Comment by mirunacurtean** [comment]
No longer occurs after dev environment has been updated to latest design. 

![Misaligned subtopics resolved](https://user-images.githubusercontent.com/53306802/97601739-2c029680-1a13-11eb-97f4-d3f44f0045d8.gif)
