### ISSUE TITLE
SVG link response is 404 Page not Found

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1569]
Environment: dev

**Steps to reproduce:** 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web. 
2. Scroll down to SVG link and select it. 

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/97599814-0ffdf580-1a11-11eb-9359-4f8a18cb166e.png)

**Expected result:**
Document is successfully loaded. 

NOTE:  Same issue encountered on https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Reference for the HTML [Developer guide](https://main.content.dev.mdn.mozit.cloud/main/en-us/docs/web/guide/html) , [Getting started with CSS](https://main.content.dev.mdn.mozit.cloud/main/en-us/docs/web/guide/css/getting_started) and [Common CSS questions](https://main.content.dev.mdn.mozit.cloud/main/en-us/docs/web/css/common_css_questions) links.

**Comment by peterbe** [comment]
@escattone There appears to be a redirect going on. I haven't looked into it yet, deeper, but we should escalate this because it could be serious.

**Comment by escattone** [comment]
Good find @mirunacurtean !!

@peterbe I just looked into this, and I think it is serious. It happens because `/en-US/docs/SVG` is a redirect to `/en-US/docs/Web/SVG`, but it's also a folder holding other redirects, like `/en-US/docs/SVG/Element` --> `/en-US/docs/Web/SVG/Element`. The `deployer` uploads `main/en-us/docs/svg` as a redirect file first, but then later over-writes it as a folder holding the other redirects in the tree! 🤦

This makes me wonder if we have to abandon S3-file based redirects, and perhaps perform the content-based redirects in Lambda, but we need to think about this one more. This is fairly common.

**Comment by escattone** [comment]
@peterbe Oh man, I'm blind! 🤦 I know what this is! PR coming in a bit!

**Comment by escattone** [comment]
@mirunacurtean Nice work, thank you! This has been fixed. See #1575.

**Comment by peterbe** [comment]
I read your reply comment on my phone late last night. I assumed it was because I was tired but I didn't understand it at all. 
I see now you've edited it away. So there is hope for my little brain!
I totally understand https://github.com/mdn/yari/pull/1575 and I love the swift action!

**Comment by escattone** [comment]
> I read your reply comment on my phone late last night. I assumed it was because I was tired but I didn't understand it at all.
> I see now you've edited it away. So there is hope for my little brain!
> I totally understand #1575 and I love the swift action!

@peterbe 😆 I wrote the original comment at the end of my day when I was tired and rushing. Later, when I had a moment to think about it in the evening, I realized that it was nonsense! 😆
