### ISSUE TITLE
Not all links in the HTML element reference tables have been rendered correctly 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1570]
**Environment: dev**

**Browsers:** 
Firefox Release
Chrome 

**Steps to reproduce:** 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element. 
2. Scroll to 'Document metadata' table  and check the description content. 
3. Check the other tables to see if other html elements links are not displayed correctly. 

**Actual result:** 
Elements such as  ({{glossary("metadata")}}) and  {{glossary("Browser", "browser")}}'s  can be seen. 
On the meta row a set of commas has been displayed instead of element links. 
![image](https://user-images.githubusercontent.com/53306802/97606960-08dae580-1a19-11eb-8b4e-fd9a77334645.png)
See attached text for all similar issues in the other tables on this page. 
[broken links.txt](https://github.com/mdn/yari/files/5460060/broken.links.txt)

**Expected result:** 
All these elements should be rendered as links.

**Comment by peterbe** [comment]
@escattone Yeah, this is due to our chicken-and-egg problem which we solved by writing our own regex-based extractor of a summary. 
http://localhost:3000/en-US/docs/Web/HTML/Element looks pretty bad now. 

You know what could give us a lot of mileage is if we keep doing the whack-a-mole game and treat KS macros in the extracted summaries with more regex. For example, you could convert
```
content of the {{HTMLElement("body")}} of a
```
to
```
content of the <code>body</code> of a
```
and the list of regexes to do this would be pretty small. 
You wouldn't even need to list them all: `HTMLElement`, `htmlattrxref`, etc. 
You could just look for any `\{\{\w+("(1)", ...\}\}` and replace them with `<code>(1)</code>`.

I think it would make a lot of pages, that use `subpages.summary` (or whatever it's called) less broken at a really cheap cost. 

Yari1 blocker?

**Comment by escattone** [comment]
@peterbe Yes, I think it is a Yari1 blocker.
