### ISSUE TITLE
Blank icons on HTML5 page

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1572]
Steps to reproduce: 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Guide/HTML/HTML5. 
2. Scroll through page and view section headers and icons.

**Actual result:** 
![image](https://user-images.githubusercontent.com/53306802/97612405-10ea5380-1a20-11eb-93e4-e89eaa5e315e.png)

A blank image is displayed for each section icon. 
Note: This could be happening only because it's on dev environment. 

**Expected result:** 
Image is displayed. 
![image](https://user-images.githubusercontent.com/53306802/97612203-ca94f480-1a1f-11eb-9d5f-8f2d6340de14.png)

Note 2: Shouldn't the image be displayed side by side with the header?

**Comment by peterbe** [comment]
Thank you but not a bug. 
The HTML contains `<img src="/files/3827/HTML5_Semantics_512.png">` which means it loads this absolute URL:
https://main.content.dev.mdn.mozit.cloud/files/3827/HTML5_Semantics_512.png 
That domain doesn't do the fallback onto `developer.mozilla.org` for the images. 

https://yari.stage.mdn.mozit.cloud/en-US/docs/Web/Guide/HTML/HTML5 is, in this case, a better domain to use because it'll take care of the fallback. 

Either way, we have a good handle on loading images and flagging images that are broken.
