### ISSUE TITLE
No space between example reference links on Getting started with HTML page

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1585]
**Steps to reproduce:** 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started.
2. Scroll to 'Omitting quotes around attribute values' examples. 
3. View example links. 

**Actual result:** 
There is not space between two different example links. 
![image](https://user-images.githubusercontent.com/53306802/97718017-17cf9f80-1ace-11eb-81bd-6714d264c6ec.png)

**Expected result:** 
![image](https://user-images.githubusercontent.com/53306802/97718069-26b65200-1ace-11eb-8c63-cc594909b220.png)

**Comment by peterbe** [comment]
@escattone I suspect the code that extracts the `html` snippets and eventually puts them into the samples HTML doesn't concatenate them in with a whitespace charater. 
Here's what you get in prod:
<img width="652" alt="Screen Shot 2020-10-30 at 4 41 36 PM" src="https://user-images.githubusercontent.com/26739/97755142-08048b00-1acf-11eb-9ce1-886ba9345350.png">

It's because it's `<a href...>text</a> <a href=...>text</a>` in Kuma but `<a href...>text</a><a href=...>text</a>` in Yari.
