### ISSUE TITLE
The functionality of the search box is much different between Kuma and Yari

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1663]
@schalkneethling @peterbe 

We need to address the difference in functionality between the search box in Kuma and the one in Yari. Currently, on the home page or a profile page (Kuma) the search box is for full-text search, but on the Yari document pages, it's an auto-complete search (with a full-text fallback). I think we have to choose one of two options here:

1. Make the Yari search box functionality the same as the home page. It only performs full-text search, and we add the fuzzy URI search functionality sometime post-launch.
1. Make the Yari search box functionality a superset of the home page. So, for example, if you first enter a `/`, you go into fuzzy URI search mode, but if you just enter some text, it does a full-text search like the home page.

To me, this is a blocker for the Yari1 launch.

**Comment by escattone** [comment]
@peterbe and I discussed this in our 1:1 meeting today and decided the following:
- For the Yari launch, for production, we will adjust the functionality of the search box on document pages to exactly match the functionality on the home page, i.e. it does a full-text site search just like MDN works today. However, for the local development experience, we will keep it in auto-complete mode.
- Sometime after we launch Yari, perhaps whenever we "take over" the home page, we'll adjust the search box's functionality to provide both full-text site search and auto-complete options at the same time.

**Comment by peterbe** [comment]
A reminder of what's going on with this issue:
* https://github.com/mdn/yari/pull/1726 is a solution on the code so that it doesn't do any auto-complete as you type. Is awaiting review by @schalkneethling 
* https://github.com/mdn/yari/issues/1655 is an open issue about making the style of input box looking almost identical in Yari and in Kuma. Depends on https://github.com/mdn/yari/pull/1726

@schalkneethling These could be good things to work on whilst we're away next week.

**Comment by escattone** [comment]
This is done.
