### ISSUE TITLE
Javascript sidebar could have a 'Jump to section' section 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1702]
**Environment:** 
Stage

**Steps to reproduce:**
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript and view the sidebar topics. 
2. Compare with https://developer.mozilla.org/en-US/docs/Web/JavaScript. 

**Expected result:**
On production there is a "On this Page" section containing links redirecting to the main topics. 
Currently this is in stage known as "Jump to section" ( https://developer.allizom.org/en-US/docs/Web/CSS ) and it would be helpful to have it at least on pages that previously did on production. 

On another note, maybe other pages might benefit from the same, since the content is no longer organized to show the topics side by side but one after another, which makes it necessary to scroll through. 
Examples of pages that do not have an "On this page" section on prod but could not benefit from one: 
https://developer.allizom.org/en-US/docs/Web/HTML
https://developer.allizom.org/en-US/docs/Web/HTML

**Comment by peterbe** [comment]
Seems the TOC is busted on that page. Also, the `<h2>` tags haven't become clickable permalinks.

**Comment by peterbe** [comment]
It's busted [on Dev too](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript)

**Comment by peterbe** [comment]
Hmm.. Definitely reproducible locally. There's nothing wrong with the `makeTOC` function. The problem is that it doesn't split the rendered HTML by `<h2>` correctly.

**Comment by peterbe** [comment]
Actually, I don't think this is worth solving. It's just not worth the extraneous effort and there's an interesting twist to it too. 

The reason there's no TOC on this page is that the rendered HTML (from kumascript) isn't like this:

```html
<p class="summary">...</p>

<h2>...</h2>
<p>...</p>
<p>...</p>

<h2>...</h2>
<p>...</p>

<h2>...</h2>
<p>...</p>
<p>...</p>
```

No, instead it's like this:

```html
<p class="summary">...</p>

<div class="column-container">
   <div class="column-half">
      <h2 id="Tutorials">Tutorials</h2>
      <p>...</p>
  </div>

   <div class="column-half">
     <h2 id="Reference">Reference</h2>
     <p>...</p>
  </div>
</div>
```
So the `<h2>` tags are not sitting at the "root level". They're deep inside other elements (`div.column-container div.column-half` in this case)

And the way we split up the rendered HTML is dependent on this because it allows us to have full control over how each `<h2>` is rendered. (It's the `<ProseWithHeading/>` component)

Sure, we *could* hack around this. 
If the HTML is weird like it is on this page, we could go back to the original `Cheerio` instance of the renderd HTML and try to fish it out with some potentially complicated...
```javascript
$('h2').each((i, element) => {
  const $element = $(element)
  const text = $element.text()
  const id = $element.attr('id') || text.replace(/\s+/g, '_')
  toc.push({ id, text })
});
```
but that's not enough. You now also need to *mutate* each `$header` so that it eventually becomes:
```html
<h2 id="$ID">
  <a href="#$ID title="Permalink to $TITLE">
    $TITLE
  </a>
</h2>
```

And I looked pretty carefully. I could have missed some but this is the ONLY page that does weird things in Web (i.e. the `<div class="column-container">` wrapper)
About 300 pages don't have any `<h2>` tags. And it seems all of them are pages like http://localhost:3000/en-US/docs/Web/XPath/Functions/number http://localhost:3000/en-US/docs/Web/API/HTMLButtonElement/disabled and http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/Index

**So should we go through all that trouble just for 1 page?** I vote we don't. 

And here's another argument for why we shouldn't do weird things: **It becomes extremely weird and hard to go to Markdown.**

Eventually we want to switch to Markdown and then the doc should become:

```markdown
## First header 

bla bla bl

## Second header

ble ble bla
```
And you don't want to make weird exceptions. So, I think this touches a nerve. Kuma has no structure and that's a bad thing. Yes, it means we can make whatever you like with HTML on one-off pages, but that's just not a very smart choice if you have to support 12k (en-US) documents which is such a large number that it's impossible to have much more than just 1 way of doing things. 

I think it can still be possible to make a one-off special page that is totally different. But if we do, we shouldn't expect that page to get the same general automation tools as we get on regular pages (a Table of Contents thing in this case).

**Comment by Ryuno-Ki** [comment]
Just for the sake of it …
What happens if you pipe that twisted HTML through [turndown](https://www.npmjs.com/package/turndown)?
(there's a [plugin for GFM](https://www.npmjs.com/package/turndown-plugin-gfm), which could come in handy)

**Comment by peterbe** [comment]
Fixed some time ago.

**Comment by mattiapontonio** [comment]
Yes but it is not in the sidebar but in the main. Maybe it's better this way otherwise on mobile it would not be at the top but at the bottom.
