### ISSUE TITLE
Remove useless macros

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1727]
Once Yari has launched, the following macros (which output nothing) should be simply deleted from all documents that use them and from the list of kumascript macros that we support. 
- `gecko_minversion_header`
- `gecko_minversion_inline`
- `fx_minversion_header`
- `fx_minversion_inline`
- `CurrentGecko`
- `GeckoVersionIndicator`
- `FirefoxVersionIndicator`

**Comment by peterbe** [comment]
Related: https://github.com/mdn/yari/issues/1274
It uses the `BUILD_LOG_MACROS_USED` env var and a Python script to find out which macros are never ever used.
Mind you, the research was a bit flawed initially since I only built en-US. If we unfreeze some of the other locales you'll find more macros that are only used in certain locales. 

But I agree with this issue. Those macros are unequivocally useless this day and age.

**Comment by peterbe** [comment]
Perhaps it's not perfect triaging but I'm going to close this in favor of https://github.com/mdn/yari/issues/1274
