### ISSUE TITLE
Align certain <h2> headers with "Jump to section" 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1732]
This goes in line with https://github.com/mdn/yari/issues/1729. 
On https://developer.mozilla.org/en-US/docs/Web/JavaScript/About_JavaScript the first `h2` header is aligned with the "On this Page" header. 
Reducing the white space would look better if it was applied to uniformly to pages on https://developer.allizom.org/en-US, as well.

**Examples**
![image](https://user-images.githubusercontent.com/53306802/99083464-44a3ac80-25ce-11eb-8236-ff920f7b7435.png)

https://developer.allizom.org/en-US/docs/Web/JavaScript/About_JavaScript
https://developer.allizom.org/en-US/docs/Web/JavaScript/JavaScript_technologies_overview

**Comment by peterbe** [comment]
Related 
https://github.com/mdn/yari/pull/1710#pullrequestreview-530213040

**Comment by schalkneethling** [comment]
@peterbe One thing I noticed here when looking at the problem is that the HTML here looks as follows:

```
<article class="article">
  <div>
    <div></div>
  </div>
  <h2 id="What_is_JavaScript">
    <a href="#What_is_JavaScript" title="Permalink to What is JavaScript?">What is JavaScript?</a>
  </h2>
```

I guess this is a content issue but, thought I would flag it. I know these pages usually begin with a leading paragraph and then a heading or interactive example. Not sure if those `div` elements are related to the fact that this page does not have the leading paragraph.

Anyhow, it is not the root cause of this problem, but it is not great that we have that in the DOM. Perhaps we can do something about it, perhaps not 🤷‍♂️

**Comment by peterbe** [comment]
Strange that it's not appearing in the source content: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/About_JavaScript$edit

Either way, I doubt there are only `<p>` and `<div class="notecard">` that are the only 1st element.

**Comment by peterbe** [comment]
Why do the empty divs have any height by the way?

**Comment by peterbe** [comment]
I guess because they're not entirely empty. There's whitespace inside them.

**Comment by schalkneethling** [comment]
> Why do the empty divs have any height by the way?

I do not think they do. The main problem is the top margin on the `h2` and, in other instances to top margin above the `notecard`. I am going to see whether inside the main `article` we standardize on only ever using bottom margins.
