### ISSUE TITLE
Javascript Guide chapters should be set onto card grids and the elements color should be consistent

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1742]
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript/Guide and compare the 'chapters' with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide
2. Notice that:
- the chapters are no longer set onto card grids
- some of the elements, for example "try/catch/throw"  have gained a black font color. This does not seem to have a particular purpose and for the sake of consistency this should be changed. 

![guides](https://user-images.githubusercontent.com/53306802/99111144-41231c00-25f4-11eb-9fbf-2d4a2a029f65.gif)

**Comment by peterbe** [comment]
@schalkneethling @chrisdavidmills How do *you* think we should solve this?

Unfortunately, we don't have a great tooling solution to this. At least not at the moment. 
It hurts my soul to think the solution is to keep adding to the global bloat of CSS. If overrides are local, it's never bloat. 
If we write a SCSS file called `learningarea-chapter-grid.scss` and include it in the main bundle, when will it ever stop? Before you know it, we'll have forgotten about that exception and we add another. And another and another. And suddenly you're back to the bloat that was Kuma.

Here are some possible solutions I can think of:

1. In content; Include a `<style>` tag in the Kuma HTML for that page(s) verbatim. 
1. In content; Create a file, in the same folder as the `index.html` called `_extra.css`.
1. In Yari; In some config file, write down certain file or URL patterns that should get additional CSS when built.
1. In Yari, write a regex that injects extra (S)CSS dynamically, at build time, depending on certain patterns in the content.
1. In content; disallow any custom formatting (because, how can this ever be converted to Markdown?) and make these pages as plain as any other page. 
1. Do nothing and just suck it up and add to the bloat. After all, `<ul class="card-grid">` appears in 22 places spread across 8 files.

**Comment by peterbe** [comment]
I think @escattone and @fiji-flo too might have ideas and feelings. 
The problem requires an almost intimate feel for the content which is why I've cc'ed Chris.

**Comment by schalkneethling** [comment]
We have decided to do away with the `card-grid`. Closing
