### ISSUE TITLE
"Jump to section": fix z-index with header

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1747]
Hello, if i open the `Jump to section` select on top of the page and then the `hamurger menu` the menu is under the list of the select and the select do not close...

Try here from a mobile phone:
https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink

My note
It's should be an issue of `z-index` and eventually focus out listening on the `Jump to section`.

**Comment by peterbe** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink is for github.com/mdn/kuma which is the old front-end we're slowly leaving. 
Use https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink to test for *this* repo.

**Comment by mattiapontonio** [comment]
The problem was in allizom.
The link was wrong.
Link corrected.

**Comment by peterbe** [comment]
As of a couple of hours ago, https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink#Browser_compatibility is working now. It used to have no rows.

**Comment by mattiapontonio** [comment]
I suggest to put only on mobile an Arrow Down icon After so validator should see find the button in a table but user know that there is a `details`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

**Comment by mattiapontonio** [comment]
I also suggest to move the `supported data` from background ti a green bullet so It Is more flexible and It can be moved around.

**Comment by peterbe** [comment]
Hang on. Let's focus. It took me a while to understand that the bug is. Let me try to explain it:

1. Go to https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink and enable responsive design mode. 
2. Click the "Jump to section" so it's open
<img width="413" alt="Screen Shot 2020-11-18 at 9 17 31 AM" src="https://user-images.githubusercontent.com/26739/99541515-e6384e80-297e-11eb-96f9-45985bfe6efa.png">
3. Now, without closing the "Jump to section" menu, click the "hamburger menu" icon
<img width="421" alt="Screen Shot 2020-11-18 at 9 18 19 AM" src="https://user-images.githubusercontent.com/26739/99541593-02d48680-297f-11eb-82c1-0efb16daae16.png">

Bonus problem. Without clicking the hamburger menu to close it, click on something in the "Jump to section" menu. E.g. "Formal syntax". This is what you see:
<img width="422" alt="Screen Shot 2020-11-18 at 9 18 41 AM" src="https://user-images.githubusercontent.com/26739/99541699-25ff3600-297f-11eb-8071-3ee3c2fe4f3e.png">

So I guess a solution would be that the "Jump to section" menu should be similar to a modal dialog in that any click outside should hide it. Perhaps easier is to give the "Jump to section" menu a lesser `z-index` than the top menu.

**Comment by mattiapontonio** [comment]
This Is what I know today by my experience:

- A good way to close things by itself is listening to https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onblur and then changhe the opened / close logic so elements are encapsulated
- Z-index Is and issue because the Jump to section comes after in the DOM, is ok like that
- dialog Is good because It has open apptribute and methods in the interface out of the box
- What You see (the black trasparent rectangle) should be the ::backdrop of the probably dialog menu that is still open or some similar element.
- i thing that if the select is out of menu in terms of dom it will trigger blur but not sure.

### My solution
So my attempt Is add `2` event listeners that remove the `open` attribuite `on blur` on both elements and refactor both to be visually affected by this.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile: Main and jump to menu](https://trello.com/c/ADx82o2B/17-mobile-main-and-jump-to-menu)

**Comment by peterbe** [comment]
@schalkneethling https://github.com/mdn/yari/pull/2550 makes it a little bit better. But can we not fix the z-index at least so that if you (in responsive mode) click the "Jump to section" first, then click to expand the top menu. The Top menu's z-index just needs to be higher.

**Comment by mattiapontonio** [comment]
@peterbe 
Yeah let me know where to test.

Pro-future: fix `z-index` and use `details`.
Let me search z-index in minimalist.

**Comment by mattiapontonio** [comment]
I Will close this.
Lets focus on something not complicated 👍

**Comment by mattiapontonio** [comment]
This Is going to
https://en.m.wikipedia.org/wiki/Overhead_(computing)

Lets use `<details>` first witch exists and then fix what missing.

**Comment by schalkneethling** [comment]
> This Is going to
> https://en.m.wikipedia.org/wiki/Overhead_(computing)
> 
> Lets use `<details>` first witch exists and then fix what missing.

I definitely do not disagree with this @mattiapontonio - would you mind opening a separate issue to explore using a `summary/details` element for this? Thank you

**Comment by mattiapontonio** [comment]
> would you mind opening a separate issue to explore using a summary/details element for this?

Actually not. But should be in future if We need effort in this. 👍
