### ISSUE TITLE
Missing Browser compatibility table in mobile

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1749]
https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink#Browser_compatibility
https://whatismybrowser.com/w/57KDH42
If You are logged in the table exists.

**Comment by peterbe** [comment]
It's actually working fine on `master` but the problem is that our Stage server has failed to deploy and we're working on that. 

<img width="1264" alt="Screen Shot 2020-11-17 at 10 01 31 AM" src="https://user-images.githubusercontent.com/26739/99406438-e02d6980-28bb-11eb-910e-8a5813a481bd.png">

So in a day or two, this problem will be solved in Stage.
