### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1775]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps
https://web.dev/progressive-web-apps/

**Comment by peterbe** [comment]
Not an issue.

**Comment by mattiapontonio** [comment]
The question is that the project could benefit from the characteristics of a PWA. It is not a small matter but the installability alone is not too difficult to reach, it requires a manifest and a service worker. I personally would like to have a nice icon on MDN's mobile phone and read it to me quietly in full screen, so I could also check if the browsing flows are "good". There is a panel in the Chrome inspector (and Firefox probably, I have to check) called "application" that checks the installation requirements, icons and so on and is a good experience on both the user and developer side.

**Comment by peterbe** [comment]
Yep! I look forward to having it too. It might finally make it possible to download all of MDN into an offline app. Service Workers are powerful beasts. 
But to turn MDN into a PWA is a huge topic. Something that needs a lot of planning, research, and careful execution. 
The truth is, the way MDN is consumed today is not as an app but as a quick search result page from Google. So that alone has an important impact on how we turn it into a PWA. 

But I closed it because it needs a bigger discussion elsewhere and not as a GItHub Issue. 
Right now, the major planning for MDN is happening in private Trello board but also to a large degree it happens in various discussions and Google Docs that float around.

**Comment by Ryuno-Ki** [comment]
> Yep! I look forward to having it too. It might finally make it possible to download all of MDN into an offline app.

You are aware of devdocs.io?

They scrape MDN already: https://github.com/freeCodeCamp/devdocs/tree/81abc5af628c426fe7882bc615615f7290e96eb2/lib/docs/scrapers/mdn

**Comment by peterbe** [comment]
> > Yep! I look forward to having it too. It might finally make it possible to download all of MDN into an offline app.
> 
> You are aware of devdocs.io?
> 
> They scrape MDN already: https://github.com/freeCodeCamp/devdocs/tree/81abc5af628c426fe7882bc615615f7290e96eb2/lib/docs/scrapers/mdn

Very aware. There are great things about PWAs to benefit users. But it's foolish to think it's trivial.

**Comment by mattiapontonio** [comment]
I repeat that from experience only passing the installation test is quick enough quick. Then how to align the various possible features with the project needs is easily questionable but without being able to take a screenshot of the shortcuts or the full-screen layout, how do you talk about it?
