### ISSUE TITLE
link rel canonical

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1804]
I know that Is a staging enviroment but when You try to share the link of the page via the anchor in the headings or via the share widget of the phone etc... the link is wrong, It points to the production.

It Is a issue for sharing link here on GitHub for example and i don't know where else.

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

**Comment by peterbe** [comment]
I think it's curious that your device shares the canonical URL rather than the current URL. Is it Android? Chrome or Firefox?
I can understand and see why the browsers would choose to do that but it's one of those difficult decisions where there's pros and cons with both options. 
But this problem will not be a problem in production. And if you desperately what to share a stage URL you'll have to copy the URL from the address bar.

**Comment by mattiapontonio** [comment]
Ok... This Is one of things in CI/CD for deploy in multiple environments but I'm not expert so ok i Will put effort
