### ISSUE TITLE
button#hamburger img[src] preload

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1814]
The hamburger menu button in the open state has a different image than in the closed state. There is a time after opening the menu when the open status image is not present.

## Potential solution
Preloading the icon. 
Didn't investigated but i guess the tag is created on the fly by React template re-rendering so it triggers a network call with the new source.
In fact the problem seems to be present only on first time on the page, probably icon is cached the second time.
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

To reproduce use incognito or clear cache.

**Comment by peterbe** [comment]
Simplest solution would be to not use an external SVG icon but inside inline it. Then this wouldn't happen at all. 
But if you inline it, you add more to the DOM which adds weight when it's only ever used or needed by the mobile view. 
But in general, I prefer to inline SVGs rather than external images.

**Comment by peterbe** [comment]
The Open-menu SVG is only inlined into the HTML. But both SVGs become part of the JS bundle. 
In terms of the weight it adds to the HTML is: 451 bytes. But if you compare the Brotli compressed it's: 121 bytes. 

The advantage of inlining SVGs is that they load instantly and there's no flicker. It's the same conclusion Facebook used when [they rewrote the facebook.com front-end in React](https://engineering.fb.com/2020/05/08/web/facebook-redesign/):
<img width="785" alt="Screen Shot 2020-12-02 at 3 26 31 PM" src="https://user-images.githubusercontent.com/26739/100927345-c3e01e00-34b2-11eb-843f-49227d05881c.png">

By the way, now that the JS bundle has the content of two new SVGs inlined in JavaScript, the bundle gets bigger. 
I analyzed the difference. 
* External: 217,212 bytes
* Inlined: 219,686 bytes
* difference: 2,474 bytes

But considering that most people use Brotli the difference is as follows (this is the bundle chunk that has the SVGs):
* External: 60,931 bytes 
* Inlined: 61,200 bytes
* difference: 269 bytes.

So basically, you're making the HTML and the JS bundle 121 + 269 = 390 bytes larger with this technique. 
That's tiny numbers but it's probably the right thing to do. Maybe.

The truth is, the hamburger menu is only used when the CSS's responsive mode figures out to display it. And only 15% of our traffic is mobile. So is it worth solving the flickering problem for 15% of users? Interesting question!

Larger JS bundles isn't so much about network download but larger JS means more busy CPU work taking up precious time from rendering on the main thread. 

So it really boils down to asking yourself; how much flickering is too bad? 
For example, everyone always gets the black and white MDN logo in the upper left-hand corner, so that one is hands-down best to do with inline SVG. But stuff that only appears for 15% of users. Hmm. Perhaps not worth it. 

By the way, I put my experimentation in: https://github.com/mdn/yari/compare/master...peterbe:1814-inline-svgs-instead-of-external-svgs if anybody's interested. 

Also, by the way, the SVG icons when served externally can be aggressively cached. But so can the JS bundles. So no difference there.

**Comment by peterbe** [comment]
@schalkneethling What do you think? 
Apart from the icons in the BCD table, I don't think we have any other external images, do we?

**Comment by mattiapontonio** [comment]
This icon seems ok
![Screenshot_20201203-093641.png](https://user-images.githubusercontent.com/44380480/100984548-284ebc00-354b-11eb-8497-7a91b009d878.png)

This icons sometimes comes after a little delay, before that a white space is showed
![Screenshot_20201203-093701.png](https://user-images.githubusercontent.com/44380480/100984663-4ddbc580-354b-11eb-8d80-8901bda29d65.png)

I don't know how to solve, sometimes this is a network async porblem.

**Comment by mattiapontonio** [comment]
Note: the orange outline Is not aligned with logo

**Comment by mattiapontonio** [comment]
I know as You said that inline Is like _sync_ and in the `src` Is like `async` so it has ti be managed of course in one possibile way in order to give the data (the image) to the browser when it Need It.

**Comment by peterbe** [comment]
@schalkneethling Should decide what to do. Inline SVGs are better for various reasons but those arguments can break down too. Switching to inline SVG is probably the right thing but what Schalk can decide is whether to do it in early 2021 or late 2021 :) Or better, a contributor helps :)
