### ISSUE TITLE
TURN OFF LANGUAGE DETECTION!

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#1831]
@determin1st commented on [Fri Nov 20 2020](https://github.com/mdn/sprints/issues/3913)

I'm really tired

---

@determin1st commented on [Fri Nov 20 2020](https://github.com/mdn/sprints/issues/3913#issuecomment-731445416)

or make it save the language choice (English should be the default)

**Comment by chrisdavidmills** [comment]
I'm assuming this is referring to the constant "you are viewing MDN in x language" type banners? Is this something that will affect yari also? Just moving this over here just in case.

**Comment by peterbe** [comment]
Language detection happens primarily when you arrive on MDN without a locale in the URL. Then it uses your browser `Accept-Language` header. E.g. 
```
▶ curl -I -H 'Accept-Language: sv-se' https://developer.mozilla.org/docs/Web
HTTP/2 302
...
location: /sv-SE/docs/Web
...
```
It also happens equally on the `/` URL:
```
▶ curl -I -H 'Accept-Language: sv-se' https://developer.mozilla.org/
HTTP/2 301
...
location: /sv-SE/
...
```

(Note, that `301` is thankfully turned into a `301` in Yari which is good because 301 redirects tend to get very stuck in browsers' cache)

One very common place where we have these locale-less URLs, for example, is in VS Code:
<img width="620" alt="Screen Shot 2020-11-23 at 9 51 06 PM" src="https://user-images.githubusercontent.com/26739/100040897-2449ce00-2dd6-11eb-82f5-4d6c6cc6fffb.png">
That URL that it links to is: https://developer.mozilla.org/docs/Web/CSS/animation

It's hard to tell where most of these inbound links come from since it redirects before it even gets to our web pages that start the Google Analytics stuff. 

I definitely think it would be possible to do something smart here with cookies. 
The `/` end point and the `/docs/*` endpoints are uniquely treated in the CDN, so we *could* make the CDN depend on HTTP cookies there without breaking any CDN caching violations. Right, @escattone ?
I believe it can be accomplished even without forcing users to sign in. Some UI in the app could set a HTTP cookie (not bundled with the session cookie) so this can be accessible in the CloudFront function that's responsible for the redirect based on the `Accept-Language` header.

**Comment by peterbe** [comment]
I skimmed the CDN logs a bit for some patterns and nothing obvious or easy stands out. It simply needs a lot more work. 
But one thing I noticed scared me. There are a lot of links in the content that are like this:
<img width="894" alt="Screen Shot 2020-11-23 at 10 27 40 PM" src="https://user-images.githubusercontent.com/26739/100043359-4bef6500-2ddb-11eb-8cf7-bcbf0114439e.png">
On https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key for example (note the `en-US` in the URL), the link looks like this:
```html
<li>If the pressed key is a control or special character, the returned value is 
one of the <a href="/docs/Web/API/KeyboardEvent/key/Key_Values">pre-defined key values</a>.
</li>
```
So, if you're happily viewing that page, with a non-en-US browser and you click that link you're now suddenly at the mercy of your browser's `accept-language` and you're kicked out of the English content you were happily consuming. 

We can pretty easily fix this, in buildtime, in Yari because we control every hyperlink during build time. 
If the page you're building and there's a hyperlink that doesn't have a locale, force it in. 
See https://github.com/mdn/content/blob/a76d0ef2fa03f0c68b1f8c489c5974d5eddcd75f/files/en-us/web/api/keyboardevent/key/index.html#L25
What I'm saying is that we can rewrite, during build to become:

```html
<li>If the pressed key is a control or special character, the returned value is 
one of the <a href="/en-US/docs/Web/API/KeyboardEvent/key/Key_Values">pre-defined key values</a>.
</li>
```
just to protect from this happening.

**Comment by peterbe** [comment]
Mostly a quick note, but based on a tiny window of CDN logs (1.5h) here are the top recurring referers when the link hit is `/docs/...` without a locale and where the refererer is actually set:

```
274 developer.mozilla.org
106 www.mozilla.org
41 support.mozilla.org
24 docs.microsoft.com
23 caniuse.com
11 addons.mozilla.org
8 www.foam-dispensing-tools.byallied.com
8 www.firefox.com.cn
7 www.baidu.com
6 wiki.mozilla.org
6 web.dev
6 docs.mapbox.com
6 developers.google.com
5 www.typescriptlang.org
5 github.com
4 stackblitz.com
4 mmp.unej.ac.id
4 m.baidu.com
4 jilin.ouchn.cn
4 guangdong.ouchn.cn
4 gansu.ouchn.cn
4 editor.p5js.org
4 discourse.mozilla.org
4 angular.io
3 zhejiang.ouchn.cn
```

So it's pretty darn common!

**Comment by peterbe** [comment]
<img width="535" alt="Screen Shot 2020-11-23 at 10 41 45 PM" src="https://user-images.githubusercontent.com/26739/100044206-13508b00-2ddd-11eb-9b40-3de842049f4a.png">
Firefox Devtools also uses links that don't have a locale in them.

**Comment by Ryuno-Ki** [comment]
> Firefox Devtools also uses links that don't have a locale in them.

Already filled on Bugzilla?

**Comment by peterbe** [comment]
> > Firefox Devtools also uses links that don't have a locale in them.
> 
> Already filled on Bugzilla?

I don't think those links are wrong. It's just a bit counter-intuitive with where we're at and where we're going.

**Comment by escattone** [comment]
We have a new system in place for Yari:
1. If you use the language selector and new `Change locale` button to change locale, it's remembered with a new `preferredlocale` cookie, and used going forward to resolve any URLs **without** a locale (e.g., `/docs/Web/HTML`). If a URL already has a definite locale (`/de/docs/Web/HTML`), that locale will **always** be used no matter what locale you have in your `preferredlocale` cookie.
1. You can also set/modify the very same cookie by logging into MDN (assuming you have an account), going to edit your profile, selecting your language, and hitting the `Save` button.

**Comment by peterbe** [comment]
Everything Ryan said! 
Also, note the *viewing* a different locale does not mean that's what you prefer. So manually changing the URL (if you prefer `en-US` instead of the `sv-SE` you have might stumble in on) will not change your permanent preferences.
