### ISSUE TITLE
BCD: Table rendering incorrectly on Push API page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1849]
Came across this one by chance and noticed it was all kinds of messed up :)

https://developer.allizom.org/en-US/docs/Web/API/Push_API#Browser_compatibility

![Screenshot 2020-11-26 at 20 07 25](https://user-images.githubusercontent.com/10350960/100382071-2c4a7d80-3023-11eb-9c49-8adfb34b2573.png)

It seems that on this page React is not replacing the old macro rendered compat-table(kumascript/macros/Compat.ejs) with the React version. I do not see any errors logged in the console though. I looked over a number of other pages and have not found another one that behaves the same.

**Comment by schalkneethling** [comment]
I notice it also adds a heading that the other tables do not have but, I assume that comes from the macro as well.

![Screenshot 2020-11-26 at 20 30 07](https://user-images.githubusercontent.com/10350960/100383404-35891980-3026-11eb-8145-44ea99561653.png)

**Comment by Ryuno-Ki** [comment]
The second observation could be #1725.

**Comment by schalkneethling** [comment]
> The second observation could be #1725.

Ah yes, this has been fixed in the latest release of minimalist.

**Comment by peterbe** [comment]
This is a problem. The reason it's happening is because that page is full of unnecessary `<div>` tags. If you make this diff, it solves the problem:
```diff
diff --git a/files/en-us/web/api/push_api/index.html b/files/en-us/web/api/push_api/index.html
index c47cea0b..dc110174 100644
--- a/files/en-us/web/api/push_api/index.html
+++ b/files/en-us/web/api/push_api/index.html
@@ -94,23 +94,16 @@ tags:
 
 <h2 id="Browser_compatibility">Browser compatibility</h2>
 
-<div>
 <h3 id="PushEvent"><code>PushEvent</code></h3>
 
-<div>
-
 
 <p>{{Compat("api.PushEvent")}}</p>
 
 <h3 id="PushMessageData"><code>PushMessageData</code></h3>
 
-<div>
 <div class="hidden">The compatibility table on this page is generated from structured data. If you'd like to contribute to the data, please check out <a href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> and send us a pull request.</div>
 
 <p>{{Compat("api.PushMessageData")}}</p>
-</div>
-</div>
-</div>
 
 <h2 id="See_also">See also</h2>
 
```

Not a great solution to have to rely on but BCD tables are very special. They're special because we're trying to turn punch a hole through a wall of HTML and turn it into something fully interactive. 
This was a lot easier and saner in Stumptown, for those who remember that, where each section was clearly defined as an array and thus we never really had to break apart from the Kumascript *rendered* HTML. 
But here we are and this is what we're dealing with. 

I think what I might do as a first stepping-stone baby step is to make a much bigger stink about it when the BCD table can't be replaced from the Kumascript rendered HTML. Then, at least we'll have insight into which documents it's happening on.

**Comment by peterbe** [comment]
For the record, the diff that's displayed [when I manually fixed it in the Wiki](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Push_API$compare?locale=en-US&to=1655959&from=1618499) looks like I changed a whole lot more than I actually did :)
I just removed every excessive `<div>` and `</div>` that didn't add any value and causes trouble in Yari.
