### ISSUE TITLE
Let's not use <Link> in the BCD table

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1920]
Steps to reproduce:

1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
2. Scroll down to the BCD table.
3. Click one of the links in the first column, e.g. `clear`
4. This happens:
<img width="1504" alt="Screen Shot 2020-12-03 at 11 33 24 AM" src="https://user-images.githubusercontent.com/26739/101058716-6e138080-355b-11eb-8726-c974d664af10.png">

I.e. it takes you to that other page but the scroll isn't working. It's not scrolling to the top.

**Comment by mattiapontonio** [comment]
Hello, this is not meant to be a war against React but I remember these things happened to me with Routers (both React and Vue) because this single page application thing is nice but they skip the classic process of serving html and having it redone to the browser all its classic rendering process starting from the beginning of the page .... with PHP this does not happen ... a URL means 1 HTML file served as in the 90s 😌 my 2 cents (I'm 30 years old not 60)

**Comment by peterbe** [comment]
Client-side navigation is like PWAs and WebSockets. Easy to get started, but hard to get sufficiently right. There are pros and cons and not settled easily when all things have to be considered.

**Comment by mattiapontonio** [comment]
Absolutely.
It's too much for me, I Just want to Say mine...
I'm sure it's all under control. 
👌

**Comment by mattiapontonio** [comment]
I don't see how it's implemented.
PWA and WebSocket are kind of standard.
There Is an API for history (discovered about a week ago).

https://developer.mozilla.org/en-US/docs/Web/API/History_API

I'm interested in this topic anyway, but i can't PR right now.

👌
