### ISSUE TITLE
tool/cli.js attempts to write to invalid path

### ISSUE THREAD

**Issue by bershanskiy** [mdn/yari#1990]
This is a pretty annoying bug because `yarn dev` apparently relies on `tool/cli.js`, so anyone following instructions in README should get an error. Note: `yarn build` and `yarn start` still work.

## Repro steps
1. Check out the project, as described in README
2. Run `yarn dev` or just `node tool/cli.js gather-git-history --verbose`

## Error (simplified)
```
/mdn/yari (master) $ node tool/cli.js gather-git-history --verbose
Error: ENOENT: no such file or directory, open '../content/files/en-us/api/file_api/index.html/_githistory.json'
    at Object.openSync (node:fs:476:3)
    at Object.writeFileSync (node:fs:1471:35)
    at tool/cli.js:289:12
    at Se._action (mdn/yari/tool/cli.js:20:13)
    at Se.run (mdn/yari/node_modules/@caporal/core/dist/index.js:1:27590)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Te._run (mdn/yari/node_modules/@caporal/core/dist/index.js:1:32257)

error: ENOENT: no such file or directory, open '../content/files/en-us/api/file_api/index.html/_githistory.json'
```

## Cause
On [line 288](https://github.com/mdn/yari/blob/master/tool/cli.js#L288), `locale` contains `index.html`, which makes this script write to an invalid path, e.g. `../content/files/en-us/api/file_api/index.html/_githistory.json`. (This path is invalid because sicnce `index.html` is a file, there can be no directory with the same path.)

**Comment by bershanskiy** [comment]
This simple patch fixes the issue:
```
diff --git a/tool/cli.js b/tool/cli.js
index 5818ced98..7b045eb71 100644
--- a/tool/cli.js
+++ b/tool/cli.js
@@ -285,7 +285,11 @@ program
         historyPerLocale[locale][relPath] = value;
       }
       for (const [locale, history] of Object.entries(historyPerLocale)) {
-        const outputFile = path.join(root, locale, "_githistory.json");
+        const shortLocale = locale.replace(path.sep + "index.html", "");
+        const outputDir = path.join(root, shortLocale);
+        const outputFile = path.join(root, shortLocale, "_githistory.json");
+        if (!fs.existsSync(outputDir))
+          fs.mkdirSync(outputDir, {recursive: true});
         fs.writeFileSync(outputFile, JSON.stringify(history, null, 2), "utf-8");
         console.log(
           chalk.green(
```

Also, it creates output dirs if needed because on the first build they might be missing.

**Comment by peterbe** [comment]
I can't reproduce. I followed [the Quickstart](https://github.com/mdn/yari#quickstart). 
It worked fine. 
Are you on Linux? What did you set `CONTENT_ROOT` to be?

It feels like the patch you commented above, is the wrong solution in a sense. Why does that `locale` have `/index.html` in it in the first place?

**Comment by peterbe** [comment]
Hmm... I'm not sure I touched anything but I just got
```
Saved 0 paths into /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/yari-git-history.json
```
and the file is empty!
```
▶ cat /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/yari-git-history.json
{}%
```

**Comment by peterbe** [comment]
Weirdness. the function `gatherGitHistory()` returns an empty Map in my `/tmp/` clone.

**Comment by peterbe** [comment]
Yeah, there's definitely something bad going on. The `git log` command isn't producing file paths that are relative to the `CONTENT_ROOT`. That's why some assumptions are breaking down. 
Great find @bershanskiy !

**Comment by peterbe** [comment]
@bershanskiy If you can describe how to break it again, I'm all ears to reopen this.

**Comment by SphinxKnight** [comment]
I'm on Windows 10 / Node v15.4 using Git bash and reproduced today.
I got a fresh copy of mdn/content today and also cloned yari.

I followed the setup instruction and set CONTENT_ROOT to `../content/files`  (I also tried `..\content\files` because Windows but that didn't change a thing)
When running `yarn dev`, it fails at the "Building SPAs" step 

It tries to write into `\content\files\en-us\api\file_api\index.html\_githistory.json` when there is no `api` directory (as of today) directly under `files/`.

I did not spend much time studying @bershanskiy patch but I think there needs to be a check if files exists.

When looking at the history of mdn/content, one can see that files/en-us/api/file_api/index.html has been added w/ commit cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630 and removed at commit commit 1937cb0f4ec7d66e62a6a64b6d8ce085c065b64a

Since this is my first "dive" into the code base, I must tell I'm not sure of the intent but if the goal is to write a _githistory.json for each existing document, we could either (actually it's more and/or):
* filter out files when the last edit is a deletion (this can be detected with `git log --name-status`)
* check if the tree exists

I'll fiddle with the second approach which seems easier but if you have any preference, let me know.

**Comment by peterbe** [comment]
> not sure of the intent but if the goal is to write a _githistory.json for each existing document,

I think the intent is to write 1 `_githistory.json` file in the `files/en-us/` folder. There's an open issue about it not working for `CONTENT_TRANSLATED_ROOT` but we'll get there when we get there.
