### ISSUE TITLE
reactions

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2009]
@mattiapontonio Feel free to re-open with a more specific feature request, but I'm not sure what you're asking for here.

_Originally posted by @escattone in https://github.com/mdn/yari/issues/1995#issuecomment-740061615_

I was talking about a feature that allows unregistered or registered users to add a limited set of quick reactions to articles and keep track so that everyone involved can have a quick glimpse of the feedback on the content eventually. In case of interest I can try to add more specifications or screenshots to copy from other social networks (I know it is not a social network but involvement seems to be important nowadays).

http://ui-patterns.com/patterns/reaction

![Screenshot_20201207-103149.png](https://user-images.githubusercontent.com/44380480/101408056-19199680-38dc-11eb-830a-239b09cc5a85.png)
![Screenshot_20201207-223313.png](https://user-images.githubusercontent.com/44380480/101408101-35b5ce80-38dc-11eb-93d9-79cf78d68ccb.png)
![Screenshot_20201207-223516.png](https://user-images.githubusercontent.com/44380480/101408409-a6f58180-38dc-11eb-8856-49bd8f95b4fe.png)
![Screenshot_20201207-223559.png](https://user-images.githubusercontent.com/44380480/101408416-a9f07200-38dc-11eb-915f-a14462643196.png)

**Comment by peterbe** [comment]
Adding the ability to post reactions to articles is a huge undertaking. It raises so many questions and its value is questionable. 
First of all; what does a thumbs up mean? That you like `CSS/background-image` more than `CSS/background-color`? Like a vote. Or does it simply mean that it was good article? Or that you "liked" the article. 

It'd be much more interesting to solicit genuine feedback instead and I think it would be significantly more interesting to make it qualitative rather than quantitative. Social media usually has both: like and post a comment. 
The way you consume social media (e.g. tweets to Instagram pictures) is entirely different in that you spend seconds on each post (minutes on an MDN article). And social media postings are inherently chronological and slow disappear (MDN articles are here to stay).

The other hugely important aspect is; what do you do with the feedback? We already sort articles, for search and stuff, by popularity which we get from pageviews traffic. If a page gets a lot of traffic it's most likely because it's valuable and needed by readers. Not necessarily because it was better written than some other article. 
But most importantly; if a user has an opinion about a page, what do you do with that? I can definitely see value in posting constructive criticism about a page. Primarily negative, because it usually means improvements can be made. For this, we actually already have something. At the bottom of every document, there's a link to prefill the posting of a new issue and it's prefilled with the URL. That lets GitHub handle the persistency, comment replies, reactions, resolutions, moderation etc. 

I think the case is clear that to build something sophisticated for feedback about the articles; it's complicated. It's the kind of thing that needs so much more than just an issue here on the Yari repo.  

I hope someday we can build something genuinely powerful for the benefit of improving the documentation even more. But that day is not near and the day it comes it'll be a whole big project with meetings, Google docs, planning etc etc.

**Comment by mattiapontonio** [comment]
Yes, I am interested in the fact that there can be freedom to express oneself without being too formal precisely to find solutions then obviously formal but without the fear of making mistakes. I really like GitHub for this type of experience and should be valued. I agree that a good contribution is an analysis but sometimes people are afraid of risking to throw away effort, it's all about managing it better thanks to Agile and the whole culture of projects.

**Comment by Ryuno-Ki** [comment]
FWIW: If you ever go down this route, please consider implementing it in a [reacji](https://indieweb.org/reacji)-friendly fashion.

I already see people using @snarfed's bridgy for interaction with GitHub from their sites.
