### ISSUE TITLE
article time[datetime=""] for translated content

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2047]
![Screenshot_20201209-235952.png](https://user-images.githubusercontent.com/44380480/101699042-caeec980-3a7a-11eb-9e83-851951d434bf.png)

https://developer.allizom.org/it/docs/Web

**Comment by peterbe** [comment]
For the record, this is a valid bug and we should probably fix it. 
Thing is, translated content is going to be frozen in the launch. And https://github.com/mdn/yari/pull/2070 patches it so that the translated content pages at least get their last-modified date from the Wiki export. 
But there won't be any git log entries to speak of even when the translated content is in git. It won't be anything until we start to unfreeze those git repos and start accepting PRs. That buys us some time. 
Also, I don't want to solve anything until we've done the 100% uplifting which @fiji-flo is working on.
