### ISSUE TITLE
Since it is more complex to write on mobile, I should have a input to reset the form#search

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2127]
Since it is more complex to write on mobile, I should have a button to clear the search field.
 https://github.com/mdn/yari/issues/1964

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset

**Comment by Ryuno-Ki** [comment]
Be aware, that [Norman Nielson group recommends against Reset buttons](https://www.nngroup.com/articles/reset-and-cancel-buttons/).

However, limited to the search form, I think, it'll be fine.

**Comment by mattiapontonio** [comment]
I ended up on reset but started with the X-shaped button.

**Comment by peterbe** [comment]
The bug here is that the search form isn't supposed to work like that. If you use `<input type="search">` instead of a magnifying glass you should get a little `x` symbol. @schalkneethling Does that get fixed once we enable the autocomplete search again?
Also, this issue talks about `reset` which is the wrong solution entirely. Do you know if we have an issue about this already?

**Comment by mattiapontonio** [comment]
Anyway for "standard" and future features reasons I'm expecting a `form` with 1 field, so It can be eventually reaetted or validated. I don't know if not It Is, that's what i've taught for clear the field.
