### ISSUE TITLE
"IncludeSubnav" KS macro seems to not render...

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2135]
...and just prints the source onto the page instead. Have a look at https://developer.mozilla.org/en-US/docs/MDN/Contribute for an example.

At the top of the content you can see the line

```
{{IncludeSubnav("/en-US/docs/MDN")}}
```

**Comment by peterbe** [comment]
Highly related https://github.com/mdn/yari/issues/1041
I think I saw a PR fly by that removes all its uses in the MDN subtree at least. So that page your mentioning for example won't work. But I know it's still present on other pages. E.g. https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example

**Comment by schalkneethling** [comment]
from the codebase:

```
// The IncludeSubnav macro is considered deprecated.
// As of today, Feb 2021, no content in the en-US repo uses it.
// The few translated-content files that were using it were buggy and
// we decided it wasn't worth even trying to recover that because no
// content should be using it anyway.
mdn.deprecated();
```
