### ISSUE TITLE
"Sign in" is not aligned

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2226]
<img width="1447" alt="Screen Shot 2020-12-19 at 9 37 27 AM" src="https://user-images.githubusercontent.com/26739/102691928-14a78480-41de-11eb-86d6-5c799d125add.png">

It happens when you're signed in too. In all browsers.

**Comment by tannerdolby** [comment]
@peterbe I noticed this alignment issue doesn't occur on the [MDN home page](https://developer.mozilla.org/en-US/) but it does occur like you mentioned on [CSS - MDN Web Docs Glossary](https://developer.mozilla.org/en-US/docs/Glossary/CSS)

After inspecting the page, the issue is caused because the `<header class="page-header" data-testid="header">` doesn't have `align-items: center` declared like it does on the home page for `.page-header`. This slightly fixes the issue but to fully fix it, I found the main menu div `<div class="page-header-main">` also needed `align-items: center` to be added.

### Screenshots:
<img width="214" alt="Screen Shot 2020-12-19 at 10 02 16 AM" src="https://user-images.githubusercontent.com/48612525/102696258-df049a80-41e1-11eb-9e4f-cdac437e314c.png">
<img width="234" alt="Screen Shot 2020-12-19 at 10 01 57 AM" src="https://user-images.githubusercontent.com/48612525/102696275-f9d70f00-41e1-11eb-8639-6d8e589856f5.png">

When I added `align-items: center` to `.page-header` and `.page-header-main` the problem seems to be resolved.

<img width="1204" alt="Screen Shot 2020-12-19 at 10 14 25 AM" src="https://user-images.githubusercontent.com/48612525/102696432-10319a80-41e3-11eb-8265-6b0f3b39e7f0.png">

I might be seeing things, but after adding `align-items: center` to `.page-header-main` the "Sign in" button does correctly align in the row, and since the search box moves down slightly, I couldn't visibly tell (I drew a few lines which looked even) if the nav items to the left of the search bar were perfectly aligned. I hope this helps!

**Comment by tannerdolby** [comment]
This is how it looks without `align-items: center` added to `.page-header-main`

<img width="1209" alt="Screen Shot 2020-12-19 at 10 20 22 AM" src="https://user-images.githubusercontent.com/48612525/102696517-df059a00-41e3-11eb-8cf8-908d77da68ca.png">

**Comment by peterbe** [comment]
The home page (technically there's one home page per locale) and search result pages come from the old (Kuma) system. 
It's, hopefully, looking almost identical. But clearly, it's not :)
That's why the CSS might look a bit confusing. 

Any URL that contains the `*/docs/...` is served from Yari and it would appreciate your fixes :)

**Comment by tannerdolby** [comment]
Okay, sounds good. I will write up a PR to fix this tonight :)

**Comment by tannerdolby** [comment]
I've submitted a PR to fix the alignment issue. It took some tinkering with a few different solutions, but I will discuss each below. 

My original idea of giving `.page-header` alignment with `align-items: center` was withdrawn as it moved the MDN logo into the center of the screen when the viewport is < 1199px. And it also moved the `main-nav` items down since it is aligning content along the main axis.
 
_Very noticeable shift of the main nav items which I don't think is desirable_
<img width="1278" alt="Screen Shot 2020-12-21 at 10 21 00 PM" src="https://user-images.githubusercontent.com/48612525/102857002-81886d80-43dc-11eb-9ad6-e5cba77b48c1.png">

_Without `align-items: center` (This is my final solution explained at the end of this comment)_
<img width="1280" alt="Screen Shot 2020-12-21 at 10 29 13 PM" src="https://user-images.githubusercontent.com/48612525/102856982-77666f00-43dc-11eb-88ed-9d234044e07a.png">


The underlying reason why "Sign in" is in the lowered position its in is because `align-self: center` is declared. 

```
@media (min-width: 47.9385em) {
  .page-header-main .auth-container {
      align-self: center;
      grid-column: 2/3;
      grid-row: 2/3;
      justify-self: flex-end;
  }
}

```

Without `align-self: center` in the above media query, the Sign in button moves up into a raised position above the main axis.

<img width="417" alt="Screen Shot 2020-12-21 at 10 01 18 PM" src="https://user-images.githubusercontent.com/48612525/102854781-16d53300-43d8-11eb-845d-394e673d17a5.png">

To avoid this, I gave `.page-header-main` alignment with `align-items: center` and this seems to be working nicely, but it does move down the entire flexbox container as its centering the `main-nav` content along the main axis, which works to align the sign in button but it does mess with the overall style a bit too much like I explained with the two images above.

The best solution seems to be removing `align-self: center` on the `.auth-container` and also removing `margin-top: 0` and replacing it with a top margin of 12px from `margin-top: $base-unit * 2`. This choice was my ideal solution as it didn't affect the alignment of the `main-nav` content along the main axis with the MDN logo.

Voila!
<img width="1277" alt="Screen Shot 2020-12-21 at 10 19 16 PM" src="https://user-images.githubusercontent.com/48612525/102856023-a54ab400-43da-11eb-8c22-33de2e8b504d.png">

Here is a screenshot to show correct alignment 
<img width="1280" alt="Screen Shot 2020-12-21 at 10 29 13 PM" src="https://user-images.githubusercontent.com/48612525/102857563-8568bf80-43dd-11eb-894d-86eb528f6bcc.png">

**Comment by tannerdolby** [comment]
I wanted to make sure this change worked everywhere so here is the details for viewports less than 1,199px wide. Since the `.auth-container` has a `margin-top: $base-unit * 2` which is only 12px, it does seem a bit raised up. 

<img width="820" alt="Screen Shot 2020-12-21 at 11 20 46 PM" src="https://user-images.githubusercontent.com/48612525/102860724-40e02280-43e3-11eb-871b-057b4be2bf23.png">

I created a media query within `yari/client/src/ui/molecules/login/index.scss` at 1,199px or `74.9375em` to increase the top margin a tiny bit for better horizontal alignment. Using `margin-top: $base-unit * 3` yields a better alignment.

<img width="850" alt="Screen Shot 2020-12-21 at 11 20 59 PM" src="https://user-images.githubusercontent.com/48612525/102860709-3aea4180-43e3-11eb-9f90-df6a6b0755ee.png">

**Comment by mattiapontonio** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

How about `vertical-align` property instead of a `grid`?
It not seems a `grid`... but inline elements here on desktop.

**Comment by tannerdolby** [comment]
@mattiapontonio No that doesn't work. I don't think it would be wise to remove the grid layout for `.page-header` or `.page-header-main`. Thanks for the input though.

**Comment by mattiapontonio** [comment]
FTR
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction
