### ISSUE TITLE
Help when the CONTENT_ROOT lacks the "files" ending

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2248]
At least two people have been tripped up by this now. 
E.g. You have a folder called `/path/to/mdn/content` which is a checkout of github.com/mdn/content so you think you can do:
```bash
export CONTENT_ROOT=/path/to/mdn/content
```
but if you do that, you'll get quite weird errors. The solution is to use:
```bash
export CONTENT_ROOT=/path/to/mdn/content/files
```
which isn't intuitive. We can pretty easily write some code around that constant that can either warn or just re-set it (and warn).

**Comment by peterbe** [comment]
Because at least two people have fallen into the pitfall of this, @ariasuni  and @jazzygasper :)

**Comment by peterbe** [comment]
@jazzygasper Do you want to attempt some neat tricks with `path` and `fs.existsSync` or something?
I'd love it if it just works to use `export CONTENT_ROOT=/path/to/mdn/content` but that it prints a warning.

**Comment by mattiapontonio** [comment]
I don't know at the deployment level how things are structured but if you put everything inside a large MDN folder as is in fact GitHub ie Yari, Content and Mdn-Minimalist maybe you shouldn't even set a variable for a path. Plus I'm not an expert but I also imagine a large Git repository that has submodules (which I know exist) with each their own story. Because it makes me think that if the server is 1 the root is 1 and if the servers are 2 then you have to expose some services (at least that's how I understood on these architectural topics).
