### ISSUE TITLE
Broken link checker and broken link indication is desirable

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2289]
Broken link checkers are an extremely useful tool for documentation maintenance. I did a spot check using [htmltest](https://github.com/wjdp/htmltest) and [BLC checker](https://matthewsetter.com/writing-tools/npm-broken-link-checker/) tools and there are 8000+ "potential" issues in the current docs. I say potential because I have spot checked only a small sample.

Gists of logs:
- https://gist.github.com/hamishwillee/f455ac42da19cb005482f23a78fe1c12
- https://gist.github.com/hamishwillee/4305d00308333e6407929b019f796521

I am hoping we could have a link checker run automatically on the source on a regular basis, possibly integrated into the doc styling to colourise broken links in red.

I'm also hoping you can look at this and tell me if there is anything generally we can/should be doing to address the links from an automation point of view.

FWIW neither of the tools above are "perfect" for this task.
- BCD works on the served version but has limited control over what is displayed.
- htmltest is very configurable but it runs on source. I had to modify the source so that links would work.

**Comment by peterbe** [comment]
I'm not sure what this is. We have a broken link checker but it only checks relative URLs (i.e. those starting with `/`). 
To go out on the network and check that the page really does exist and with or without redirects might be a tricky thing to do en-masse. 

The original idea was that we make the migration to Yari (Dec 14 2020) and "immediately" after run all broken link fixable flaws etc. But it turned out a bit chaotic (e.g. bugs in the fixable flaws for images) and we simply haven't had a chance to properly do it for all en-US content. 

A challenge with checking broken *external* links is that there are so many:
```
▶ rg 'href="http' | rg -v 'https://developer.mozilla.org' | wc -l
   18066
```

But sure, it would perhaps be possible to check it one page at a time so you don't do it for 12k documents when you run `yarn build`. 

One problem I've seen is that some external URLs are so old that domain scammers/squatters buy up the domain and replace it with a redirect to some scammy ad-filled page. So it works, but it's junk.

**Comment by mattiapontonio** [comment]
Comment from a non expert in all the project:

I would fetch HEAD of all hrefs in the document on server before serving the document and add a `data-status` attribute to the link

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

So this _status_ is computed every time and updated.

**Comment by hamishwillee** [comment]
> I'm not sure what this is. We have a broken link checker but it only checks relative URLs (i.e. those starting with /).

@peterbe Thanks for that. Mostly I wanted to highlight the problem and find out if there is anything that can be done to fix it. 

It sounds to like you have a link checker for the internal links to pages already - does this cover the links to page anchors? When is it run? Is this something that gets fixed if you fix the "flaws" on a page in the local build?

> But sure, it would perhaps be possible to check it one page at a time so you don't do it for 12k documents when you run yarn build.

That sounds like a good idea - perhaps something triggered on a local build for any page that you change or visit? This could even be something that only happen if you build with a particular flag.

In an ideal world you want to make it easy for users to see problem links before they go to them - making it easy to work out what needs fixing. Often that's just making broken links appear in red.

And yes, I appreciate that broken links might be squatted. Not much that can be done about that particular case.

**Comment by peterbe** [comment]
So, what we're talking about here is an advanced tool that can check all the external hyperlinks for you. It'd be done on a page-by-page basis because it wouldn't be feasible to do it in bulk across thousands of pages. 

What existing tools exist already that you can point to a page of HTML that does this greatly. If there exists a good third-party service, we might be able to pay for that instead of writing our own integration. Besides, it would be cool if said service could give you more insights, such as "yes, this linked, but it redirected to a site that's been flagged as potential spam"

**Comment by mattiapontonio** [comment]
@hamishwillee 
Is that fixed?

https://github.com/mdn/yari/issues/2065#issuecomment-761105203

**Comment by hamishwillee** [comment]
> Is that fixed? #2065 (comment)

@mattiapontonio Assuming you're asking "is this what you meant by red links marking up broken links", then yes :-). This is exactly what I meant except in an **ideal world** there would be hints for broken links to headings and broken external links.

@peterbe The general requirement is "make it easy to discover broken links". What you are [suggesting above](https://github.com/mdn/yari/issues/2289#issuecomment-761035401) sounds like a pragmatic solution - i.e. not as good as having every single questionable link marked up but achievable and much better than nothing.

**Comment by mattiapontonio** [comment]
@hamishwillee ok but please if You can be specific on code. We can't take issue open for big jobs otherwise they are milestone or something bigger. We need something actionable in 1 PR. 👍

**Comment by mattiapontonio** [comment]
> broken links to headings

This Is not an issue on _link_. Is an issue on _document_. A link can work but serves not the section that You are looking for.

**Comment by hamishwillee** [comment]
@mattiapontonio Whatever :-) The point is that someone gets to the document, but not the section that they want. The list of anchors in a page can be known/determined and hence can be reported for fixing.

**Comment by mattiapontonio** [comment]
@hamishwillee keep going 💪🤞

**Comment by mattiapontonio** [comment]
@hamishwillee i think You should close this and reopen one or more issues for others features.

**Comment by hamishwillee** [comment]
Closing this. Internal and anchor links are checked. External links are not, but there is https://github.com/mdn/yari/issues/653 which should address that.
