### ISSUE TITLE
Inform user about outdated content

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#233]
I keep forgetting to update my content and then Peter has to keep reminding me to do just that.

Our CLI should take that job over and inform users when the content dir is outdated and print the commands necessary to get it up to speed:

```bash
# if submodule out-of-date
git submodule update --init --recursive
# if build out-of-date
yarn build
```

Peter's idea for detecting out-of-date builds is to place a .gitsha in packaged and I also think that makes sense

**Comment by peterbe** [comment]
There's actually two different things going on:

1. Have you run `git submodule update` recently?
2. Have you run `cd stumptown && npm run build-json` recently?

Also, you can set the `STUMPTOWN_CONTENT_ROOT` env var which means the git submodule sha is pointless. 

Either way, if the `build-json` script "leave a trace" in `packaged` it would be great for stumptown-renderer to compare that and do a check.

**Comment by peterbe** [comment]
Perhaps we can start with testing this with stumptown-renderer on its own first. 
You're suppose to have run `yarn build` (with or without `CLI_BUILD_HTML`) otherwise `yarn start` is going to suck. 
So we could add, to the cli, that in the root of the destination folder it always makes a `.gitsha` file which is the result of `git rev-parse --short HEAD`.

Then when you run `yarn start` it could do something like this:

```javascript
const currentSha = runSpawn(`cd ${STUMPTOWN_CONTENT_ROOT} && git rev-parse --short HEAD`)
try {
  const buildSha = fs.readFileSync(path.join(STUMPTOWN_CONTENT_ROOT, "packaged", ".gitsha"), "utf8");
  if (buildSha !== currentSha) {
    return complainAboutRunningYarnBuild();
  }
} catch (err) {
  return complainAboutRunningYarnBuild();
}
```

**Comment by peterbe** [comment]
We don't have submodules anymore. Nor do we have Stumptown. 

If we do want to inform the user that their content is out of date, it'd be a git dance we do in `mdn/content`.
