### ISSUE TITLE
Folder localization layout

### ISSUE THREAD

**Issue by nschonni** [mdn/yari#2411]
Probably a bad time to bring it up since you already went live 😄 
There is probably a few things to borrow from the Microsoft Docs approach (without adopting their tooling).

I'll use the example of the Visual Studio docs:
- EN: https://github.com/MicrosoftDocs/visualstudio-docs
- CN: https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn

- one locale per repo
- locales aren't part of the folder path in the repos, that's a server side (or yari) concern
- paths to the files are the same for each file no mater the locale. Not sure how that would work with the slugs ...
- relative/absolute links don't include the locale. EX: https://docs.microsoft.com/visualstudio/ide/compiling-and-building-in-visual-studio goes to the browser local, and makes syncing for translation easier since the URLs don't need to change

Maybe this isn't the right repo, so feel free to transfer if it makes sense

**Comment by peterbe** [comment]
I like a lot of that! 
In particular, it's so redundant that every single file in `mdn/content` is called something like `en-us/web/css/index.html` which it's almost implicit that it's `en-us` from the simple presence of being in the repo. 
I think we can get there too someday. If we do a massive `git mv` we would potentially confuse every living open pull request ;)
But that can be remedied by doing it in incremental blocks over time. 

To be honest, I wish the slugs would just go away! The slug has to match the folder name (with some transforms) and that stuff's predictable so that the only value the `slug` has is the ability to specify case (e.g. `IntersectionObserver`). 
I wish it was as simple as the folder is the URL. Perhaps we can get there someday. 

@nschonni Do you know, how does `MicrosoftDocs` cope with renaming? E.g. suppose they decide to rename https://github.com/MicrosoftDocs/visualstudio-docs/tree/master/gamedev/unity/troubleshooting to `troublemaking`. How do they "sync" that with the https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn repo?

Regarding URLs without locale. MDN has that too. 

I'm pretty sure @fiji-flo is all for one locale per repo instead of the monster that is github.com/mdn/translated-content. 
But I think he has some other interesting experiments going on too. 

Also, one technical challenge we would have is that if someone makes a PR in something like `github.com/mdn/content.zh-cn` we'd need to have the `.github/worksflows/*.yml` stuff there that kicks in nicely. And that would need to the same functionality (and in sync) for every single `github.com/mdn/content.*` repo.

**Comment by nschonni** [comment]
I usually bug @mairaw when I have questions about the MSDocs setup. Maybe they'd be willing to meet with your team to share some of the stuff that goes on outside of the published stuff

**Comment by mairaw** [comment]
Adding @JasonCard who probably knows more in detail how renaming works for our localized content.

**Comment by JasonCard** [comment]
>@nschonni Do you know, how does MicrosoftDocs cope with renaming? E.g. suppose they decide to rename https://github.com/MicrosoftDocs/visualstudio-docs/tree/master/gamedev/unity/troubleshooting to troublemaking. How do they "sync" that with the https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn repo?

Our loc platform monitors the English source repo for any new/updated files.  
A renamed file is treated as a new file added, handed off to translation, previous translation is recycled, and the newly translated file is committed into localized repos. Previously localized file with old name will be deleted from localized repos as it no longer exists in the source repo.

**Comment by mattiapontonio** [comment]
> - No locale, then sniff Accept-lang and set a cookie or somthing for subsequent requests

Yes. If the browser is the same even the _Accept-lang_ could be the same.

> - If URL includes locale, respect the locale

Yes. A query param overrides the header. I see Is a big issue for the project since the locale in the path Is used a lot now.

> - If the page doesn't exist in the locale, fall back to default en-US locale
> 

I like the actual solution so in fact a 404 and a body that helps.

**Comment by peterbe** [comment]
I think it's honestly too late to deal with this. Our current plan in unfreezing locales is that they share a repo so then it makes perfect sense to keep the prefix. 
But even if we someday give each locale its own repo, there might still be enough value in using a prefix always. 
And given the size of the task (including risks of dealing with quirks and legacy) to move away from the redundant prefixes, I'm going to close this for now. 

THANK you all for your wonderful contribution and feedback.
