### ISSUE TITLE
Language select Bug

### ISSUE THREAD

**Issue by 1337Eddy** [mdn/yari#2436]
By changing language to another than English just English and the choosen language appear in the select field.
All other languages disappear until you switch back to English.

**Comment by peterbe** [comment]
We're aware of this and it's based on the fact that it's complicated to know what all language combinations possible are. 
But it's not impossible. 

We made it like this, for now, because it's simpler. And as a user, if stumble into a document in a language you don't understand, it's unlikely that you can't hop from that language, to English, and from there to the desired language.

**Comment by mattiapontonio** [comment]
Couldn't we put them all and at most mark the broken links / `option`s in red?
