### ISSUE TITLE
Create automated updated page render preview during CI build process

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2453]
Reviewing more complex page updates and additions can be a little cumbersome in Yari:

1. Checkout a new branch on your local repo
2. Pull the PR branch into it
3. yarn start
4. Go to your browser, localhost:5000
5. Figure out which pages have been changed.
6. Go visit each one and check whether the changes look OK, cross-referencing the diffs in the PR so you can home in on the changes.

It would be great if somehow the CI build process could provide a link to a rendered version of each changed content page, so they can be found and viewed more easily.

**Comment by peterbe** [comment]
Somewhat related to: https://github.com/mdn/yari/issues/1624

**Comment by peterbe** [comment]
I think we can break down this issue into 2 passes:

1. After the `yarn build $GIT_DIFF` that happens in the `pr-build.yml` workflow in mdn/content. We also run the deployer and upload it all to the Dev S3 bucket in a prefix that reflects the name of the PR. Next, we just need to tell the deployer to additionally print (to `stdout`) what the URLs would be. (e.g. https://pr12356.main.content.dev.mdn.mozit.cloud/en-us/docs/Web/Foo/bar)
2. Instead of just printing the URLs to `stdout` in the CI output, we post these URLs as a (Markdown) comment back into the PR. Kinda like Codecov posts a nice comment that explains what the new PR code coverage was.

**Comment by peterbe** [comment]
We did it! The PR Review Companion is live now.
