### ISSUE TITLE
Our code snippets don't have line numbers

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#246]
On [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) it looks like this:
<img width="1051" alt="Screen Shot 2019-11-20 at 2 38 06 PM" src="https://user-images.githubusercontent.com/26739/69271730-6462e900-0ba3-11ea-9d31-8cb670de92e2.png">

On [Stumptown](http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) it looks like this:
<img width="718" alt="Screen Shot 2019-11-20 at 2 38 39 PM" src="https://user-images.githubusercontent.com/26739/69271760-7775b900-0ba3-11ea-9111-fa8eff862247.png">

**Comment by peterbe** [comment]
@wbamberg @Elchi3 Do we want line numbers for our code snippets in Stumptown too? If so, this issue is the roll up the sleeves and do the work. 

I could see how it could potentially be dictated by the user when typing the markdown using those triple backticks.

**Comment by wbamberg** [comment]
In Kuma you get line numbers by default but can suppress them using the `no-line-numbers` class.

Personally I don't like line numbers in code samples, and think they look especially silly when the code sample is very short. I think line numbers are useful when you need to refer to a line (for instance because the tools are telling you you have an exception there) and this is quite rarely the case in MDN. The only case I can think of is where the prose wants to talk about a particular bit of the example, which is not that common.

So perhaps we should swap the default, so we don't have line numbers by default but let authors ask for them if they know the text wants it?

On the other hand I'm tempted to make a choice and not let authors override it, for consistency and simplicity.

**Comment by wbamberg** [comment]
Interestingly CodePen has line numbers but they are almost invisible.

**Comment by peterbe** [comment]
Yeah, the more I think about it the more I feel that having line numbers kinda defeats the notation of calling them code snippets. 

Let's leave this issue for now until someone needs it then we can incorpoate a solution so it becomes *possible* to type something like: ` ```js line-numbers `

**Comment by peterbe** [comment]
Let's use [this more up-to-date dupe](https://github.com/mdn/yari/issues/628).
