### ISSUE TITLE
height on code live examples is being set to `auto` overriding the inline height

### ISSUE THREAD

**Issue by rachelandrew** [mdn/yari#2683]
On pages that have embedded code examples, the macro allows a height to be added which is then added as an inline style.

However the following CSS is setting `height` to `auto` and so they are all appearing as small boxes.

```.sample-code-frame {
    border: 1px solid #1e7f9d;
    border-left: 6px solid #00458b;
    height: auto;
    margin: 0 0 12px;
    padding: 12px;
    width: 100%;
}
```

Noticed when working on https://github.com/mdn/content/issues/1653 reported on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator but it happens everywhere.

**Comment by captainbrosset** [comment]
It looks like the `height:auto` is being set from this file: https://github.com/mdn/mdn-minimalist/blob/7dc4c60a2a12782282ed707fbcfaa81ca8adf2fd/sass/atoms/_examples.scss#L4

Removing this declaration fixes the particular problem reported in mdn/content#1653, but if the auto height is useful in other cases, maybe instead of using the iframe's `height` attribute, we should use `<iframe style='height:...'>`.

**Comment by peterbe** [comment]
@schalkneethling Can you triage this one?

**Comment by peterbe** [comment]
@schalkneethling Can you help me decipher this one if it needs just changes to the SCSS or to the macros as well?

**Comment by peterbe** [comment]
25 days ago, https://github.com/mdn/mdn-minimalist/issues/422 seems to have been the trigger that added `height: auto` to all code examples.
