### ISSUE TITLE
Issue closing times

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2706]
I couldn't find the issue I had in mind, so please pardon for open a new one.

There were discussions somewhere about running some stats over git (which were harder to do on MySQL?).

In that chord, I want to highlight a small web app written by @LeaVerou which might be interesting to look at from time to time:
https://projects.verou.me/issue-closing/

The issue closing time could be an indicator for „contributor happiness” (i.e. faster responded tickets make contributes happier - like in tech support).
Or, it could be used to detect long-standing issues (which tend to fall on the wayside).

What do you think?

**Comment by mattiapontonio** [comment]
To be mentioned
https://en.m.wikipedia.org/wiki/Burn_down_chart#:~:text=A%20burn%20down%20chart%20is,the%20work%20will%20be%20completed.

This is an Agile thing.
A _Jira thing_.

**Comment by peterbe** [comment]
A solution to open-issue-lingering is to not file issues. 
A lot of companies have an offline discussion (not literally, but meaning away from their primary ticketing system) which when concluded because an issue (or ticket or whatever they call it). 

Generally, an issue should be actionable, even if low priority. I.e. a concrete solution would always be welcome. Some issues become blocked, which is unfortunate, but it just means it's an actionable *blocked* issue. 

So in this case, I think *this* issue is not an issue. It might become some day when the discussion concludes something that needs to get code (e.g. coding).

**Comment by mattiapontonio** [comment]
We can't talk about project management here ... In any case, these are all ideal issues that cannot really be measured, they are just tools.

**Comment by mirunacurtean** [comment]
@escattone As I was trying to categorize the issues in yari I also came across this issue and I was wondering, isn't it better to turn it into a discussion?

**Comment by mattiapontonio** [comment]
> into a discussion

Or into a project (same menu).
https://github.com/features/project-management/

![Screenshot_20210212-184251.png](https://user-images.githubusercontent.com/44380480/107802827-20d53b80-6d62-11eb-9f1c-739f071c319a.png)

**Comment by escattone** [comment]
Thanks @mirunacurtean. Yes, let's move this into a discussion.
