### ISSUE TITLE
Markup on SERP

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2707]
While doing some research, I noticed that there is markup on Search Engine Result Pages.
Take https://developer.mozilla.org/en-US/search?q=edit+mode+html&page=2 for example:

![markup-on-serp](https://user-images.githubusercontent.com/3097194/106031596-c1273100-60cf-11eb-8131-8ff0ec74ba4c.png)

I feel like those should be stripped away.

**Comment by peterbe** [comment]
I disagree. I think in MDN it makes sense to be able to search within the code examples. 

Look at https://developer.mozilla.org/en-US/search?q=switchMode for example. The term `switchMode` (I have no idea what it is by the way) never appears in any of the prose. It only appears in the JS and HTML code examples. 

One thing we *could* do is to index the code examples separately from the prose. When you do that you can *prefer* (aka boost) the prose over the code examples. I.e. instead of indexing like this:

```
index_document(
  title=doc.title,
  body=escape(doc.html)
)
```
we could do:

```
all_pretags, everything_except_pre_tags = removeAllPreTags(doc.html)
index_document(
  title=doc.title,
  body=escape(everything_except_pre_tags),
  code_examples=escape(all_pretags.join('\n'))
)
```

If you do that you'd be able to search, by field, separately. 

But before we get into the weeds about the things you "could" do, let's first figure out if this is something we want to do. Code examples *is* MDN.

**Comment by Ryuno-Ki** [comment]
What I really miss (might be another issue) is the ability to apply filters - or facets - to search results.
For example, to only search in a certain subtree.
Or, here, to include hits from code examples.

I believe, this would improve the search experience a lot.
(Shall I open a new issue for that? I _think_ it has no high priority right now).

**Comment by peterbe** [comment]
> (Shall I open a new issue for that? I _think_ it has no high priority right now).

Yes please! Perhaps even better would be to start a Discussion. 
Then other people can "pile on" with what they wish the search could do. And once some sort of pattern emerges, we can pluck, from that, an actionable issue. 

We have to be very careful and not add search functionality just because it's possible. 

But for example, it could be neat to make a link like this:
```html
<p>
  For a complete list of all CSS pages relating to "grid" go to
  <a href="/search?tree=/web/css&q=grid">this search result page</a>.
</p>
```
This could be useful to [replace some of those crazy `Index` pages](https://github.com/mdn/yari/issues/1786)

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/yari/discussions/2715

There you have it :-)
