### ISSUE TITLE
Sub headings not getting direct linkified 

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#2736]
I noticed these two `<h2>` tags aren't being highlighted and turned into a direct link like they should be. This is happening on the [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) page.

<img width="710" alt="Screen Shot 2021-01-28 at 8 13 53 PM" src="https://user-images.githubusercontent.com/48612525/106230999-868fc800-61a5-11eb-8b9c-22ffe5ece499.png"> 

<img width="520" alt="Screen Shot 2021-01-28 at 8 15 57 PM" src="https://user-images.githubusercontent.com/48612525/106231244-1a619400-61a6-11eb-9e36-d7bd7f88848e.png">

<img width="444" alt="Screen Shot 2021-01-28 at 8 16 46 PM" src="https://user-images.githubusercontent.com/48612525/106231237-1766a380-61a6-11eb-9886-fb2d36a7b2c8.png">
<img width="725" alt="Screen Shot 2021-01-28 at 8 13 35 PM" src="https://user-images.githubusercontent.com/48612525/106231005-898ab880-61a5-11eb-8107-5167540313ca.png">

**Comment by peterbe** [comment]
It happens because the `<h2>` there (the one that doesn't work) isn't sitting at the "root level". It's inside a `<div>`. I don't know how or why, but the problem is with the content. 
<img width="621" alt="Screen Shot 2021-01-29 at 11 12 14 AM" src="https://user-images.githubusercontent.com/26739/106299147-d9f42b80-6222-11eb-9d50-c2370538385f.png">

Can you figure out what the `<div>` is coming from?

**Comment by tannerdolby** [comment]
@peterbe Yeah I will figure out where the `<div>` is coming from. Check back in later today.

**Comment by Ryuno-Ki** [comment]
> I don't know how or why, but the problem is with the content.

Except that the content does not create that div:

https://github.com/mdn/content/blob/d33756432e0b336d33c1f47bb3d0f65e0ce56659/files/en-us/web/css/using_css_custom_properties/index.html

There are plenty of `<div>`s in this page, that weren't authored.

**Comment by peterbe** [comment]
So what's probably happening is that some invalid HTML gets forgiven by `cheerio` and when serialized back to a HTML string, it adds that `<div>` lets see what's going on.

**Comment by peterbe** [comment]
What's happening here is that we have HTML looks like this:

```
<p>intro bla bla</p>

<h2>Basic usage</p>
<p>blabla</p>

<h2>First steps with custom properties</h2>
<div id="sample1">
  <p>blabla</p>
  <h2>Inheritance of custom properties</h2>
</div>
```

What the builder does is that it first breaks it up into sections by looping over the "root level" elements. The first and section section is:
```html
<p>intro bla bla</p>
```
and 
```html
<h2>Basic usage</p>
<p>blabla</p>
```

But for the next section, yes it starts with a lovely `<h2>` but here's more than one *within*
```html
<h2>First steps with custom properties</h2>
<div id="sample1">
  <p>blabla</p>
  <h2>Inheritance of custom properties</h2>
</div>
```

So it dares not to extract split it by `<h2>`. In fact, to extract the title, it uses:
```javascript
const h2s = $.find("h2");
if (h2s.length === 1) {
    id = h2s.attr("id");
    title = h2s.html();
    titleAsText = h2s.text();
    h2s.remove();
}
```
But what happens here on this page is that `h2s.length === 2` so it can't confidently proceed. 

The solution is two-fold. 
First, we need to correct the HTML. That second `<h2>Inheritance of custom properties</h2>` should be moved and appear *outside* the `<div id="sample1">` so it's at the root level instead. 
Secondly, because there's a lot of pages that are like this. We can do a little bit better. So we can change the `id` and `title` extraction to:
```javascript
const h2s = $.find("h2");
if (h2s.length >= 1) {
    id = h2s.attr("id"); 
    title = h2s.html();
    titleAsText = h2s.text();
    h2s.eq(0).remove();  // only remove the first one
}
```
That, and log it as a flaw (not fixable) where a writer has to go in and move the `<h2>` to the root level.

**Comment by peterbe** [comment]
As warmup, I ran a complete build (all en-US) where I logged every time there's a page that exhibits this exact same problem. 
Just a random one: http://localhost:3000/en-US/docs/Learn/Accessibility/Mobile 
([scroll the bottom](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Mobile) and note that the "See Also" is not a valid section)

In total, there are 84 times where there's `<h2>`s that aren't at root level and 60 where `<h3>`s aren't at root level.

**Comment by Ryuno-Ki** [comment]
Pardon me, but … are you sure?

https://github.com/mdn/content/blob/d33756432e0b336d33c1f47bb3d0f65e0ce56659/files/en-us/web/css/using_css_custom_properties/index.html#L20-L54

I cannot find a `h2` nested inside a `div` there (like the „Inheritance of custom properties” you mentioned before)

**Comment by peterbe** [comment]
> Pardon me, but … are you sure?
> 
> https://github.com/mdn/content/blob/d33756432e0b336d33c1f47bb3d0f65e0ce56659/files/en-us/web/css/using_css_custom_properties/index.html#L20-L54
> 
> I cannot find a `h2` nested inside a `div` there (like the „Inheritance of custom properties” you mentioned before)

I'm sure. 
See line 157 in this range: https://github.com/mdn/content/blob/d33756432e0b336d33c1f47bb3d0f65e0ce56659/files/en-us/web/css/using_css_custom_properties/index.html#L48-L190

A PR is coming soon. You can study it in a bit more detail then.

**Comment by Ryuno-Ki** [comment]
Okay, found the opened (but unclosed) `<div>` in line 105.
