### ISSUE TITLE
Design and implement replacements for all appropriate macros in our JavaScript documentation

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#2843]
**Depends on https://github.com/mdn/sprints/issues/2520**

In https://github.com/mdn/sprints/issues/2520 we triage all KumaScript macros called from our JavaScript documentation. Some of them (hopefully not many) will be triaged as "replace", meaning that we need to provide a replacement in stumptown.

We've already done this for Compat, EmbedInteractiveExample, and EmbedLiveSample.

## Acceptance criteria
We have a replacement for every macro that was triaged as "replace" in https://github.com/mdn/sprints/issues/2520.

**Comment by chrisdavidmills** [comment]
This will be useful when we start to actually do the work to get rid of KS

**Comment by peterbe** [comment]
What I propose we do is write a flaw that treat a macro as "render-out-able" :)
It'll be a flaw but it'll gracefully continue to work. Then, as part of the fix fixable flaws, we basically replace the `{{MACROCALL}}` with the HTML it produced and save it back to the source `index.html` file. 

I think we can take a page from the `mdn.deprecated()` trick. I.e. the macros that should be replaced (at the source) with its rendered HTML string, should individually get an extra call like `mdn.selfDestruct()` and then the flaw system will be informed. This is better than having a hardcoded array of macro names within the kumascript Node code.

**Comment by escattone** [comment]
> What I propose we do is write a flaw that treat a macro as "render-out-able" :)
> It'll be a flaw but it'll gracefully continue to work. Then, as part of the fix fixable flaws, we basically replace the `{{MACROCALL}}` with the HTML it produced and save it back to the source `index.html` file.
> 
> I think we can take a page from the `mdn.deprecated()` trick. I.e. the macros that should be replaced (at the source) with its rendered HTML string, should individually get an extra call like `mdn.selfDestruct()` and then the flaw system will be informed. This is better than having a hardcoded array of macro names within the kumascript Node code.

@peterbe Just so there's no confusion when others read this issue (since this issue is for the `replace` case), your proposal would be for the macros that are in the `render` list, not the `replace` list.

Also, I'm not sold on your approach for the `render` case, mainly because fixing these `render-out` flaws (the `remove` -- aka "deprecated" -- flaws as well)  becomes a tedious process because there's currently no way to tell the builder to automatically fix only one type of flaw. If we had a more fine-grained way to control flaw-handling from the command line when building, I think I would be more convinced. To me, it's clearer and easier to just add another option to our `yarn tool` that can either `remove` or `render` macros (the code for handling those two cases is already in the kumascript renderer).

**Comment by escattone** [comment]
@schalkneethling I know we made some progress in removing/rendering-out some macros, but I suspect we've picked all or nearly all of the "low-hanging" fruit, and what's left is more challenging or something we shouldn't even do. However, I'm not sure. There might be some cases remaining that are obvious choices to render-out or remove. CC @wbamberg

**Comment by wbamberg** [comment]
I think we should probably close this issue. It was originally written in the context of Stumptown, which envisaged replacing KS macros. I still hope we might eventually replace them but we don't have any active projects to.
