### ISSUE TITLE
Triage all KumaScript macros that are called from our JS docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#2846]
**Depends on https://github.com/mdn/sprints/issues/2519**

1. Run our linter on all the JS docs to get a list of all the KumaScript macros that they call.
2. Go through all the macros, and decide for each one whether we should:
* render: replace the macro call with the static HTML that it generates
* remove: remove the macro call
* replace: design and implement a replacement for the KumaScript macro

These decisions should be made public and reviewed by our content lead.

## Acceptance criteria
We have a resolution (render, remove, replace) for every macro called from the JS docs.

**Comment by peterbe** [comment]
Regarding the list of "Remove" (above)...
Since https://github.com/mdn/yari/pull/2746 it's now a flaw to use one of the KS macros whose code (`.ejs` file) includes the line `mdn.deprecated()`. And it's a fixable flaw so it will automatically remove the KS macro. So, to tackle the KS macros that should be removed, you just need to update the `.ejs` file to have that line (look at https://github.com/mdn/yari/blob/8cedcfd125eb88b594c10a7e27b24905a2ccf7ff/kumascript/macros/fx_minversion_inline.ejs#L20 for an example)
So let's compare that list with what we've got:

- [ ] `Draft`
- [ ] `Non-standard_inline`
- [ ] `Obsolete_inline` 
- [ ] `experimental_inline` 
- [ ] `deprecated_inline`
- [ ] `Index`

(in other words, at the time of writing, all of these macros render out and are not cleaned up with the flaw-system)

A tricky one is `Index`. If that macro should be removed what should happen to all the pages whose slug ends with `Index`. E.g. https://github.com/mdn/content/blob/main/files/en-us/web/api/index/index.html

**Comment by peterbe** [comment]
Also, can we not say that this issue is complete and can closed? If [Will's comment above](https://github.com/mdn/yari/issues/2846#issuecomment-593693054) is the final verdict, then that answers the issue's title and the next action is to explode this into fresh new smaller atoms of issues that we can work against.

**Comment by mirai-anime** [comment]
([animation)](https://mirai-anime.com/) ซึ่ง{มา|มาหา|มาริ|มาสู่|ลงมา}{ริ|ริอ่าน}{ดำเนิน|ไป|จาก|เดินทาง|เคลื่อน|เดิน|เคลื่อนที่} ภาษาฝรั่งเศส อานีเม่ (anim?) {ถ่าย|ขนถ่าย|ขน|ขนย้าย|สำเนา|คัดลอก|ขี้|อึ|ถ่ายอุจจาระ|ขับถ่าย|ระบาย|โยกย้าย}{ความหมาย|ความนัย|คำจำกัดความ|คำนิยาม|คำอธิบายศัพท์|ความสำคัญ|นัย}{เหมา|ว่า|ว่าจ้าง}{เคลื่อน|ขับเคลื่อน|ขับ|เขยื้อน|เขยิบ|ขยับ|ย้าย|เลื่อน|เคลื่อนตัว|เคลื่อนไหว|ขยับเขยื้อน|ไป|จาก|เดินทาง|ดำเนิน|เดินเครื่อง|ติดเครื่อง|กระดิกกระเดี้ย|กรีธา|ยก} {หรือ|ใช่ไหม|หรือไม่|ไม่ใช่หรือ|เหรอ|หรือว่า|ไม่ก็|หรือไม่ก็}{ไม่|มิ|เปล่า}ก็{ทัศนียภาพ|ทิวทัศน์|วิว|ทิวภาพ|ขอบฟ้า|ภาพ}{ขยับเขยื้อน|เคลื่อนไหว|เคลื่อน} {แต่ว่า|ทว่า|แต่ทว่า|แต่|แต่ถ้าว่า|เสียแต่ว่า|แม้ว่า}{ได้|ได้รับ|ได้มา|หาได้|จัดหามา|คว้า}{กลาย|เปลี่ยนไป|แปรไป|กลับกลาย|เปลี่ยนแปลง|กลายเป็น}{เป็นนัย|โดยปริยาย|ใบ้|แย้มพราย}{หมด|สิ้นสุด|จบ|ถึงที่สุด|รวด|ทั้งหมด|เรียบ|ไม่เหลือ|เกลี้ยง|ขาดมือ|ตรึก|สิ้น|เปลือง|เจ๊ง|ล้ม|ชิ่น|สูญสิ้น|ว่างเปล่า|ล่มจม|หมดสิ้น}{ทาง|ลู่|แนว|ทางวิ่ง|เลน|โอกาส|ช่อง|จังหวะ|ลู่ทาง|ลาดเลา|แนวทาง|วิถีทาง|วิธี|วิธีการ|แบบ|วิถี|เส้นทาง|สาย|ถนน|มารค|มรรค|มรรคา|ถนนหนทาง|ทำนองคลองธรรม|แบบอย่าง|ทิศ|ทิศานุทิศ|เบื้อง|ข้าง|ทิศา|ด้าน|ทางสัญจร|กระแส|ช่องทาง|ตรอก|ซอย|ทางผ่าน|ทางเดิน|ทางแคบ|ครรลอง|หนทาง|มุข}{ไป|เสด็จ|อยู่|จาก|เดินทาง|เคลื่อน|ดำเนิน|เสด็จพระราชดำเนิน|คลาไคล|จร|เที่ยวไป|เดิน|เคลื่อนที่|เจียร|จากไป}{มี|ประกอบด้วย|กอบด้วย|มีอยู่}{ชีวิต|ปากท้อง|ชีพ|ชีวะ|ชีวา|ชีวี|ชีวัน|ชีวิตินทรีย์}{วาจา|คำพูด|ถ้อยคำ|วลี|คำกล่าว|คำ|วจี}{เท่านั้น|แต่|เฉพาะ|อย่างเดียว|เพียงนั้น|แค่นั้น|ขนาดนั้น}{ข้าวของ|เครื่องใช้|ของ|สิ่งของ|ข้าวของเครื่องใช้|ของใช้}{เครื่องใช้|ข้าวของ|ของ|สิ่งของ|ข้าวของเครื่องใช้|ของใช้|เครื่องบริขาร|บริภัณฑ์|เครื่องใช้สอย|เครื่องอุปโภค|ของอุปโภค|สิ่งของเครื่องใช้|ที่|ภาชนะ}ภาษาญี่ปุ่น {ระวาง|ที่|ตำแหน่ง|ทำเนียบ}{ใช้|ชดใช้|ชำระคืน|กิน|เปลือง|ใช้คืน}{คืน|ส่งกลับ|ส่งคืน|กลับคืน|กลับ}{พาหะ|ตัวนำ|สื่อ}{แม้|ถ้าแม้|แม้ว่า|ถึงแม้|แม้น|หาก|ถ้า|ถ้าหาก|สมมติว่า|ผิ|ถึง|ทั้งที่|ทั้งๆ ที่|ถึงแม้ว่า|ขนาดที่}{พาหะ|ตัวนำ|สื่อ}{จอเงิน|ภาพยนตร์|หนัง|จอภาพยนตร์}{ภาพ|ทัศนียภาพ|ทิวภาพ|ทิวทัศน์}{ล้อ|ล้อรถ|ลูกล้อ|แหย่|เย้า|ยั่วเย้า|ยั่ว|หยอกล้อ} (animated media

**Comment by Elchi3** [comment]
@schalkneethling asked for input on this. So here are my thoughts.

I think we have less macros these days but not all can be removed yet. (I haven't done a grep on macro usage but suspecting the list above is more or less accurate).

- Banners (non-standard, deprecated, seeCompatTable) should be driven by BCD (proposal: https://github.com/openwebdocs/project/issues/81)
- Sidebars (JSRef, JsSidebar) need a sidebar project (there was once talk to have yaml files drive sidebar generation)
- Interactive Examples may want to see how it's possibly to embed them without KS?
- SpecName/Spec2 are 98% gone thanks to the spec project I did last year.
- Link macros (jsxref, previous, previousnext, glossary, bug) can probably be replaced by plain markdown links.

**Comment by teoli2003** [comment]
- I think that with @sideshowbarker PR (#5284) about `spec_url` we should be able to deal with most of the remaining `SpecName` `Spec2` entries (special cases like Aria, but also overview pages linking to whole specs).
- The `page` macros are little by little replaced by @hamishwillee  (mostly).
- I agree that all link macros could be replaced by plain markdown links nowadays (thank you Markdown): this is likely scriptable.

**Comment by SphinxKnight** [comment]
If I may (re: mdn/translated-content)
- Regarding `{{Spec}}`: migration needs to be done over on mdn/translated-content (same goes for the short {{Compat}} form)
- For {{page}}: we created a set of issues for active locales https://github.com/mdn/translated-content/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22%7B%7Bpage%7D%7D%22+ and PR
- Manual replacement of xref/link macros is encouraged, at the moment mostly on PR per PR basis (w/ tools like https://marketplace.visualstudio.com/items?itemName=bhughes339.replacerules)

**Comment by teoli2003** [comment]
We have deleted/deprecated a lot of macros since then. But this is still valid, even if `{{page}}`, `{{SpecName}}`and `{{Spec2}}` are now gone from mdn/content. (And many others are now gone).

Dealing with banners would be a contained (and doable) project (on the dev side), to move this project forward, while we continue to remove the use of the long tail of macros.

Sidebars macros depend on the page-type project (adding page-type to the YAML header) and the renaming of the page (which will add another YAML header). Once this is done, we should be mature enough to start a sidebar project.

> 
>     * Banners (non-standard, deprecated, seeCompatTable) should be driven by BCD (proposal: [OWD project proposal: Generate "experimental" banners from BCD openwebdocs/project#81](https://github.com/openwebdocs/project/issues/81))
> 
>     * Sidebars (JSRef, JsSidebar) need a sidebar project (there was once talk to have yaml files drive sidebar generation)
> 
>     * Interactive Examples may want to see how it's possibly to embed them without KS?
> 
>     * Link macros (jsxref, previous, previousnext, glossary, bug) can probably be replaced by plain markdown links.

**Comment by schalkneethling** [comment]
> We have deleted/deprecated a lot of macros since then. But this is still valid, even if `{{page}}`, `{{SpecName}}`and `{{Spec2}}` are now gone from mdn/content. (And many others are now gone).
> 
> Dealing with banners would be a contained (and doable) project (on the dev side), to move this project forward, while we continue to remove the use of the long tail of macros.
> 
> Sidebars macros depend on the page-type project (adding page-type to the YAML header) and the renaming of the page (which will add another YAML header). Once this is done, we should be mature enough to start a sidebar project.
> 
> > ```
> > * Banners (non-standard, deprecated, seeCompatTable) should be driven by BCD (proposal: [OWD project proposal: Generate "experimental" banners from BCD openwebdocs/project#81](https://github.com/openwebdocs/project/issues/81))
> > 
> > * Sidebars (JSRef, JsSidebar) need a sidebar project (there was once talk to have yaml files drive sidebar generation)
> > 
> > * Interactive Examples may want to see how it's possibly to embed them without KS?
> > 
> > * Link macros (jsxref, previous, previousnext, glossary, bug) can probably be replaced by plain markdown links.
> > ```

I have no idea what is going on. There are a LOT of issues being closed by the `github-actions` bot.

**Comment by caugner** [comment]
Most of these macros have already been replaced, and this is obsolete with the rari work, so I'm closing this as resolved.
