### ISSUE TITLE
Remove the magnifying glass icon?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2847]
**Note** We can't act on this issue until we've ported the home page and site-search over to Yari. Otherwise we'd have inconsistencies and we'd have to edit Kuma front-end code. 

Why do we have this magnifying glass?
<img width="883" alt="Screen Shot 2021-02-08 at 1 55 31 PM" src="https://user-images.githubusercontent.com/26739/107267986-9022f680-6a15-11eb-8837-6434df582fa4.png">
It adds weight and noise and adds very little value. 
We already have a button to press (if you can't rely on simply hitting Enter or the built-in form submission on mobile) (`<input type="submit" class="ghost search-button" aria-label="Search" value="">`) so it's not meant to be pressed to submit the form. 
I also suspect it might cause problems with mobile devices that should be putting a little "reset/cross icon" there on iOS browsers. 
Isn't it obvious that the white input widget in the header, on the right-hand side, is a site search widget?

**Comment by Ryuno-Ki** [comment]
As a stop-gap solution, I think, you could hide the icon with `display: none;`.

**Comment by mattiapontonio** [comment]
Google was the first to do this idiocy of putting things visually into inputs (I don't have the commit to mention) like microphones, X, other. From then on a number of designers (myself included) have wanted to embrace this problem which is in fact a problem of putting an internal border on the input and the magnifying glass for example. Today we should take a step back and go back to the good old input type search and submit, separate, so we easily delete one rather than the other.

**Comment by peterbe** [comment]
Let's work on this as soon as https://github.com/mdn/yari/pull/3009 has landed.
