### ISSUE TITLE
Cannot find "Add translation"

### ISSUE THREAD

**Issue by marcuspag** [mdn/yari#2921]
According to "Translating MDN pages" guide, at the bottom of the Language dropdown list of every MDN page I should be able to find "Add a Translation" (at the bottom of the list). Unfortunately, there's no such item in my list. If I try to go to the wiki site (as stated in the same "Translating MDN pages" guide), whose base URL should be https://wiki.developer.mozilla.org/, I get redirected to https://developer.mozilla.org/, where there's no "Add a translation" at all.

**Comment by Ryuno-Ki** [comment]
@chrisdavidmills Is this a relict of our wiki times? You're the best to decide, what to communicate regarding translation process.

**Comment by mattiapontonio** [comment]
Where Is Translating MDN pages guide URL?
The add `button` in any case I would not put it in the `select` because the `select` only supports `option` as descendant.

**Comment by chrisdavidmills** [comment]
This page was deleted a long time ago, and should not be still showing on the site. I just checked the source, and it no longer exists in the repo, so I'm not sure why this is still showing.

@escattone any thoughts here?

**Comment by escattone** [comment]
@chrisdavidmills @marcuspag Finally getting to this, sorry for the delay. This is due to a known deficiency in our deployer (see https://github.com/mdn/yari/issues/2224). We don't yet handle deleted documents/redirects (i.e., we don't remove them from S3), so that's why the "Translating MDN pages" guide **was** still visible. I haven't had time to work on that issue yet, but will shortly. In the meantime, I've gone ahead and manually deleted all of the S3 documents under https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize (but not that document itself, since it's still a valid document), so the obsolete "Translating MDN pages" guide (https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize/Translating_pages) is no longer visible.

Also, that page (or any other deleted page) hasn't been in any locale's sitemap file since it was deleted -- for example, do a `wget wget https://developer.mozilla.org/sitemaps/en-US/sitemap.xml.gz && gunzip sitemap.xml.gz && vi sitemap.xml` and then search for `/en-US/docs/MDN/Contribute/Localize/Translating_pages`. You'll notice that it doesn't exist.

@marcuspag For now, we're not yet ready for localization on MDN and we're making some radical changes. The best things to read about localization on MDN are the following:
- https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize
- https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/
- https://hacks.mozilla.org/2021/02/mdn-localization-update-february-2021/

**Comment by chrisdavidmills** [comment]
Thanks @escattone , much appreciated!
