### ISSUE TITLE
Flaw check that docs don't link to themselves?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2974]
I just fixed an issue where there was a link to a topic with a different name that actually went back to the current page: https://github.com/mdn/content/pull/2464

This case was clearly a flaw, and it might be useful to have these pointed out automatically - both direct links to same page and links that go via a redirect.

Might be useful in the flaw checker

**Comment by escattone** [comment]
Interesting, thanks @hamishwillee. Just for the record (for others), the specific case you fixed above actually originated from an act of fixing a flaw (see https://github.com/mdn/content/pull/1051), where `/en-US/docs/Web/HTTP/Server-Side_Access_Control` was fixed to `/en-US/docs/Web/HTTP/CORS` because it was redirected (you can see the redirect in https://raw.githubusercontent.com/mdn/content/main/files/en-us/_redirects.txt).

I'm thinking that's the most common case too, so perhaps we should add some code to the way we handle the `MacroRedirectedLinkError` to make that flaw **not** fixable (i.e., it'd have to be fixed manually) when we detect that we're suggesting a link to the same page.

**Comment by hamishwillee** [comment]
Yes, that could work (in particular if the flaw-warning explained _why_ it wasn't fixable). 

Note further, that I do not know if there are cases where a link to the current page is something that we allow/support/want.

**Comment by peterbe** [comment]
You're so good at coming up with great ideas for the flaw system. 
I think the `broken_link` flaw should be extensible enough. You have the free reign of an `explanation` string which you could do something like this with:
```javascript
if (a.href === doc.href) {
  addBrokenLink(
          a,
          checked.get(href),
          href,
          null,
          "Link links to the page it's already on"
        );
}
```

**Comment by hamishwillee** [comment]
Thanks so much @peterbe (and @escattone )!

I did just think of a case where we wouldn't want to report a flaw, and that's in a sidebar link that contains a whole set of related pages, including the current one. I really like that your fix does not have to worry about this case.
