### ISSUE TITLE
about if you search <a> in https://developer.mozilla.org

### ISSUE THREAD

**Issue by usecry** [mdn/yari#3004]
**Summary**
_What is the problem?_
when you search <a> in search bar, it tell you that:"0 documents found for "a" in en-US."

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. go to https://developer.mozilla.org
2. there's a search bar that on the right top, say:"search MDN"
3. write a or <a>

**Actual behavior**
_What actually happened?_
there no document found, but if you search: (a HTML) in google, you may found a page :"https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a"

**Expected behavior**
_What did you expect to happen?_
when i search a, or <a>, it will come out the page of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

**Additional context**
_Is there anything else we should know?_
i also try it on my iphone , but it also can't found anything.

**Comment by peterbe** [comment]
The indexing is actually happening in the Deployer which is a piece of code that's part of Yari's build process. 

The reason `<a>` yields nothing is because when broken down into tokens it first becomes `a` and that's a stop word so all you're left with is `''` (no tokens). 

It's a bit better with [`<video>`](https://developer.mozilla.org/en-US/search?q=%3Cvideo%3E) but if someone typed that it will also match `Multimedia: video` which might be a bit surprising. 

However, imagine two different users. They both want to get to this page: [`<script>: The Script element`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)
One might type: [`script`](https://developer.mozilla.org/en-US/search?q=script)
The other might type: [`<script>`](https://developer.mozilla.org/en-US/search?q=%3Cscript%3E) 
In that case I think it makes sense to break down the indexing to 2 different tokens. Just to cover all the cases.
