### ISSUE TITLE
smartLink() should fall back to English in some way

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3053]
We have a lot of xrefs and sidebars (soon!) that use `smartLink()` and these can recover to fall back to English if the translated content doesn't exist. 

We can discuss implementation choices here. For example:

1. `<a class="page-not-created" title="Not yet created ...">SomeApiMethod</a> <a href="/en-US/docs/SomeApiMethod">English</a>`
2. `<a title="Not available in Japanese. Falling back to English" href="/en-US/docs/SomeApiMethod">SomeApiMethod</a>`
3. `<small>In English</small> <a href="/en-US/docs/SomeApiMethod">SomeApiMethod</a>`
4. (Chris's suggestion) `<a title="Page only currently available in English" href="/en-US/docs/SomeApiMethod">SomeApiMethod (en-US)</a>`

Any other ideas?

**Comment by peterbe** [comment]
@chrisdavidmills @schalkneethling @escattone any preferences and ideas for how the links should appear when the `smartLink()` KS function can fall back to English?

**Comment by Ryuno-Ki** [comment]
Perhaps worth to show an US flag behind?
As in, this is a default-link

**Comment by Ryuno-Ki** [comment]
https://emojipedia.org/flag-united-states/ - so Unicode support since 2015.

**Comment by peterbe** [comment]
No flags please.

**Comment by peterbe** [comment]
Here's a great example of a page that would benefit from this:
https://developer.mozilla.org/ca/docs/Web/API/WebGL_API#refer%C3%A8ncia
It looks like this at the time of writing:
<img width="1201" alt="Screen Shot 2021-03-02 at 1 27 02 PM" src="https://user-images.githubusercontent.com/26739/109696376-fd303480-7b5a-11eb-9186-021d0ecae259.png">

These are `domxref` macros which already uses `smartLink` but we're just not doing anything with the fact that these can be "salvaged" by linking to the English version.

**Comment by peterbe** [comment]
@schalkneethling @escattone @fiji-flo @chrisdavidmills   Can you share your feelings/opinions about how we should treat these links? 
See the bullet point list above. Feel free to add new alternatives to that list. 
**And please share your vote of preference.**

Please keep in mind that real-estate is real. A lot of links are displayed in a fashion that it's not conducive to display a lengthy additional link/word and even just adding "English" might have "bad effects" of line-breaking in the sidebar.

**Comment by peterbe** [comment]
Keep this one in mind too: https://github.com/mdn/yari/issues/3104
Whatever we solve here, we should consider regular broken localized links that can be salvaged too. 
One thing that comes to mind is that regular cheerio `<a>` objects are easy to mutate with things like `.addClass('page-only-in-english')` or `.attr('title', 'Only available in English (US) at the moment')`. But it's less obvious to inject new elements into the DOM if that's what we decide to do. KS macros are easier in this regard.

**Comment by escattone** [comment]
> @schalkneethling @escattone @fiji-flo @chrisdavidmills Can you share your feelings/opinions about how we should treat these links?
> See the bullet point list above. Feel free to add new alternatives to that list.
> **And please share your vote of preference.**

I really like the idea of falling-back to the English link if the non-English link doesn't exist. I think we should do that. I like option #2, but I suppose it has to be translated, at least for the 4 actively-supported locales.

**Comment by schalkneethling** [comment]
Instead of just presenting a non-functioning link, it makes a lot more sense to offer users the English version when it exists. Of the options provided I also vote for option 2

```
<a title="The linked document is currently only available in English. Continue?" href="/en-US/docs/SomeApiMethod">SomeApiMethod</a>
```

When a user hovers over the link the title will pop-up as a tooltip which will then contain the explanatory text. For screen reader users it would read: "SomeApiMethod. link. The linked document is currently only available in English. Continue?"

We should also consider styling these a bit differently from "working" links. So, for a link where there is also no fallback we do red as we currently do, we have our general link color for "working" links, and then for these fallbacks, we can use a high contrast yellow as well as the question mark cursor.

What to do on mobile? That is a hard question I do not have an answer to yet. We could attach an event handler on mobile devices and show a custom tooltip with something like:

```
The linked document is currently only available in English. Continue?
```

Clicking. continue will then take the user to the English page. Something to think about but, I would vote for the above is a really good first step.

**Comment by chrisdavidmills** [comment]
I feel a bit uneasy about solution 2. A little while back we got rid of the title tooltip stuff from all the *xref macros because of concern over accessibility bad practice. I believe the concern is that not all AT reads out the title contents consistently, , at least not by default, so you are supposed to not include any vital information in there, just extra "nice to have" information that isn't vital for usage.

I can also see the problem of solution 1. Having an extra link to the English version after each non-existent page link could be really ugly, and detract from the user experience.

I think the knowledge that you are about to go to an English page is essential knowledge for site users, so it should be in the link text.

The knowledge that the page doesn't exist yet, which is why they are being sent to the English page , isn't essential knowledge to use the site, but it is useful knowledge, especially if you are a (would be) contributor. I'd therefore suggest that we use a variant of solution 2 along these lines:

```
<a title="Page only currently available in English" href="/en-US/docs/SomeApiMethod">
  SomeApiMethod (en-US)
</a>
```

**Comment by schalkneethling** [comment]
Thanks, @chrisdavidmills. I think this is a nice compilation of everything that was suggested here.

> I believe the concern is that not all AT reads out the title contents consistently

That is very true. I tested it out and while NVDA does a good job, VoiceOver reads it in such a way that the connection between the link text and the text in the `title` attribute is easily missed.

**Comment by peterbe** [comment]
I'm very impressed with @chrisdavidmills 's arguments there. I added his alternative solution. 
I think it would be technically very feasible to force-change the link text to add that extra ` (en-US)` which is short, accurate, and helpful. 

Unless someone screams a stronger argument for an even better alternative, I'd be delighted to implement Chris's suggestion.

**Comment by escattone** [comment]
@peterbe @schalkneethling I'm switching my vote to @chrisdavidmills' solution! ❤️ it!

**Comment by escattone** [comment]
Thanks for leading this discussion @peterbe! Let's move ahead with @chrisdavidmills' solution.

**Comment by peterbe** [comment]
I think we should do the same with regular `<a href>` links too. E.g. 

```html
<p>Kolla in denna länken här <a href="/sv-SE/docs/Web/CSS">CSS</a>.</p>
```
should automatically become:
```html
<p>Kolla in denna länken här <a 
  title="Page only currently available in English"
  href="/en-US/docs/Web/CSS">CSS (en-US)</a>.</p>
```

But that can be done as a separate thing.

**Comment by Ryuno-Ki** [comment]
Crosslinking #2705 in case we want to pick up on https://github.com/mdn/yari/issues/3053#issuecomment-789536813 in the future.
