### ISSUE TITLE
Create a separate dependency for `yarn content`/ "utils" commands - Portability between mdn/content and mdn/translated-content

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/yari#3226]
After having slept on #3220 and a quick discussion on Matrix with @chrisdavidmills, I'm opening this issue to discuss the following.

As I understand it, mdn/content has mdn/yari as a dependency to be able to use `yarn content/filecheck/build` and the corresponding subcommands.

If I'm not familiar with all of them, I think such "utils" could be useful for mdn/translated-content as well.

In order to bundle those properly, could it be possible for them to live in a separate repo/package?
(I don't think mdn/translated-content should get the full mdn/yari as, in the current workflow, we expect mdn/content to spin up the yari server)

**Comment by peterbe** [comment]
In general, the mdn/translated-content repo could have a `package.json` too. And in it, one of the dependencies can be `@mdn/yari` too. 
Because right now translators have to use mdn/yari to do previewing and that's kinda annoying because it's certainly slower and it's just a bit odd that the contribution instructions are so different from en-US writers compared to translators. 

The challenge is that if we "copy" what mdn/content has over to mdn/translated-content, the big difference is that the mdn/translated-content actually needs a separate checkout of mdn/content. It needs that for being able to do comparisons and stuff. 

But I don't think it's infeasible. We could make it an exception and a loud warning would say something like:
```
Warning! the CONTENT_ROOT environment variable couldn't find the mdn/content repo. 
Please ....
```

**Comment by peterbe** [comment]
Ideas and preferences here @fiji-flo ?

**Comment by fiji-flo** [comment]
I don't have to many opinions here. I don't think there's to much overhead in the workflow. We currently encourage localizers to use the same workflow as _en-US_ editors + checking out `translated-content`. We do not ask them to use a `yari` checkout.

If I understand @SphinxKnight corrent: The proposal is to carve out the tooling like `yarn content` of yari and make them available in the `translated-content` repo. Unfortunately these tool require all of yari so that's not really feasible. We could indeed just _copy_ the `package.json` from `content` + some adjustments.

An alternative would be to evolve this into a porper cli tool that edits install globally and that has a `yari update` command.
