### ISSUE TITLE
Windows setup - Local server crash - EMFILE when editing / opening tabs

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/yari#3297]
After a few days using my Ubuntu machine, I switched back to a Windows one and set up a fresh environment (cloning mdn/content and mdn/translated-content in the morning).

However, when I was editing a localized page for a PR and checking a few links on my current page (localhost:5000 in/... my browser), I repeatedly had crashes.

```
[Error: EMFILE: too many open files, open 'C:\Users\julien\mdn\content\files\en-us\web\api\window\scrollmaxx\index.html'] {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\julien\\mdn\\content\\files\\en-us\\web\\api\\window\\scrollmaxx\\index.html'
}
```
I definitely reproduced this a few times without "trying too much" but don't have a specific scenario for reproduction. I'll update if I get one.

**Comment by SphinxKnight** [comment]
@hamishwillee: as @tristantheb and I came across this one quite easily and, if I recall correctly, you are using Windows, I was wondering if this was something you stumbled upon.

**Comment by tristantheb** [comment]
**Observed:**
```bash
15:52:02 server.1       |  node:internal/process/promises:245
15:52:02 server.1       |            triggerUncaughtException(err, true /* fromPromise */);
15:52:02 server.1       |            ^
15:52:02 server.1       |  [Error: EMFILE: too many open files, open 'C:\Users\trist\OneDrive\Documents\MDN\content\files\en-us\web\api\window\scrollbylines\index.html'] {
15:52:02 server.1       |    errno: -4066,
15:52:02 server.1       |    code: 'EMFILE',
15:52:02 server.1       |    syscall: 'open',
```

**Step to reproduce:**
1. Open 1 page
2. Open a page in a new tab (mouse middle click)
3. Sometime the server crash and the page return an 500 error ECONNREFUSED due to the crash

**When observed:**
-> Openning a US page from an FR page
-> Openning multiples pages
-> Return back to a previous page

**AND ! The error refers to a page I did not try to open...**

**Comment by peterbe** [comment]
Skimming https://stackoverflow.com/a/21070580/205832 it seems it's quite a common thing and it's simply bound to happen. 
But how do we solve it? We can either have a troubleshooting section about how to increase your OS's `ulimit` for various operating systems. Truth is, we actually already have such as a [section on the yari repo](https://github.com/mdn/yari/#troubleshooting) but that's not helping you on the `mdn/content` or `mdn/translated-content` repo. 
Also, it would be nice to not have this problem at all. 

I'm assuming this is only happening when you're using the `yarn start` from within the `mdn/content` repo clone. Is that right?

Would you mind testing trying to running `ulimit` and report what it might say there. 
Perhaps we can run that for people and print out a warning about needing to set a higher limit if the number is too low. 

Can you try to reproduce this using the mdn/yari repo instead? It's different from the server you get from mdn/content because on mdn/yari it starts a React/webpack dev server which also watches all the .js and .scss files as well. 
It would be interesting to know how much worse it is there? :)

Also, would you mind then trying to check out my branch here: https://github.com/mdn/yari/compare/mdn:main...peterbe:3297-try-switching-to-graceful-fs
Check out the branch and then type:
```
yarn install
yarn dev
```
and now use HTTP://localhost:3000 instead and click around. 
It might not be a good test but it's worth a shot to see if this `graceful-fs` is good for us.

**Comment by hamishwillee** [comment]
@peterbe This is a new thing, which first started happening last week (or so I recall). 

I did not report because I always have around 200 chrome/ff tabs open and assumed I'd just gone over some limit. Did not appear to stop anything - ie at most a refresh of the page of interested still reloaded it. Note, my computer is not running short of any obvious resource according to the Windows Resource manager.

Below is the debug after opening 12 or so pages after doing yarn start (on yesterday's head revision of /mdn content)
```
...
buildDocumentFromURL(/en-us/docs/web/api/content_index_api): 87.481ms
buildDocumentFromURL(/en-us/docs/web/api/content_index_api): 40.193ms
buildDocumentFromURL(/en-us/docs/web/api/performance_api): 119.735ms
(node:11756) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, open 'D:\github\mozilla\mdn_content\content\files\en-us\web\api\window\scrollmaxy\index.html'
(node:11756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Windows does not have Ulimit so I couldn't run that.

I've had trouble getting yari branches to work with my content, so I just changed the same file in my current build tree to use fs-graceful (as shown). I think this is all you changed in your branch. I opened about 100 files in browser and also opened a few in vs code and did not see the error. Not "canonical" but indicative that this might be a good move.
![image](https://user-images.githubusercontent.com/5368500/112066876-42c0aa00-8bbb-11eb-9f5a-b46891e7d4d7.png)

**Comment by tristantheb** [comment]
I haven't tried to change the `ulimit` yet ^^'

But one thing I noticed mainly about my crashes today was that they all happened when I tried to search from an open US page. And I only had 2 tabs open (FR + US). When a launch the search en the MDN search bar (localhost:3000) => Error 500 + errno "-4066"

Regarding the Repo used, I use `mdn/yari` all the time, and errors are often triggered when I interact with the content of `mdn/content` from `mdn/translated-content`, or from `mdn/content` itself. [Yari .env is configured with : Editor + Content + Translated (+ Archive since yesterday but the issue comes from before)]

That's it for the little information ^^

**Comment by peterbe** [comment]
That's super helpful!
And I think I know why it is the way it is. When you request HTTP://localhost:5000/en-us/search-index.json it will trigger this:
https://github.com/mdn/yari/blob/0fcf5178e39791c36cd13087b6ab280feb96c540/server/index.js#L138
which does this: https://github.com/mdn/yari/blob/0fcf5178e39791c36cd13087b6ab280feb96c540/server/search-index.js#L29
which, if you look closely uses async style opening of thousands of files. 
These lines in particular: https://github.com/mdn/yari/blob/0fcf5178e39791c36cd13087b6ab280feb96c540/server/search-index.js#L39-L41

I did a bunch of benchmarking to write that code and found it to be faster to do it async than to do it sync. 
But I can see now, that if you have a very limited amount of open file descriptors on your OS, it'll easily run into problems. 

In fact, can you download https://gist.github.com/peterbe/2cc06543cea5089a16f6f88d619a7095 and put it into your root Yari directory and run it. Here's what I see:
```
▶ node populate-search-index-benchmark.js
Populate search-index: 1.718s
11716
```
What happens when you run that?

Next, since you probably have `graceful-js` in your `./node_modules` already you can probably run:
https://gist.github.com/peterbe/95faab6d3346da9ce4725b9de17595cf
That file still works for me. 
Does it work for you?

Last but not least, what if we get away from all this fancy async and go back to a plain sync version?
Can you download https://gist.github.com/peterbe/c1b3bd467648de603ab6143cb14fb7b2 and run that too?
Here's what I get:
```
▶ node populate-search-index-benchmark-sync.js
Populate search-index: 1.545s
11716
```

As you can see, this "unoptimized" sync version populates 11,716 files in 1.545 seconds which is practically the same as the one that uses `async`.

**Comment by peterbe** [comment]
@SphinxKnight @hamishwillee you're on Windows right? 
Can you download all 3 gists ^ into your `yari` directory and run each one of them and report what happens?

**Comment by tristantheb** [comment]
With `populate-search-index-benchmark.js`
```bash
$ node populate-search-index-benchmark.js 
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: EMFILE: too many open files, open '[MyWindowsRoot]\MDN\content\files\en-us\web\api\window\screenleft\index.html'] {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: '[MyWindowsRoot]\\MDN\\content\\files\\en-us\\web\\api\\window\\screenleft\\index.html'
}
```
[MyWindowsRoot] = The C:\ path to user directory, to reduce the line lenght

With `populate-search-index-benchmark-graceful-fs.js `
```bash
$ node populate-search-index-benchmark-graceful-fs.js 
Populate search-index: 3.398s
11713
```

With `populate-search-index-benchmark-sync.js`
```bash
$ node populate-search-index-benchmark-sync.js
Populate search-index: 4.527s
11713
```

**Comment by SphinxKnight** [comment]
Here are my results:
I ran `graceful` and `sync` twice to get more datapoints. It seems both works better when files are "hot".

```

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark.js
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: EMFILE: too many open files, open 'C:\Users\julien\mdn\content\files\en-us\web\api\window\
scrollmaxx\index.html'] {
  errno: ←[33m-4066←[39m,
  code: ←[32m'EMFILE'←[39m,
  syscall: ←[32m'open'←[39m,
  path: ←[32m'C:\\Users\\julien\\mdn\\content\\files\\en-us\\web\\api\\window\\scrollmaxx\\index.h
tml'←[39m
}

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark-graceful-fs.js
Populate search-index: 12.588s
11704

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark-sync.js
Populate search-index: 7.792s
11704

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark-sync.js
Populate search-index: 9.175s
11704

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark-graceful-fs.js
Populate search-index: 6.190s
11704

julien@laptop MINGW64 ~/mdn/yari (main)
$ node populate-search-index-benchmark-sync.js
Populate search-index: 6.840s
11704
``` 

@peterbe thanks for the dedication about this issue and swift answers, I know that Windows users are not that frequent around here. Sincerely appreciated 🙇‍♂️

**Comment by hamishwillee** [comment]
I'm back on Moz stuff tomorrow. Happy to test the next round.
