### ISSUE TITLE
browser compat table layout glitch in Safari/Chrome

### ISSUE THREAD

**Issue by nt1m** [mdn/yari#3373]
Safari/Chrome:
![image](https://user-images.githubusercontent.com/1795135/112839977-174c2c80-909f-11eb-9826-cf2dc2469877.png)

Firefox:
![image](https://user-images.githubusercontent.com/1795135/112840015-1fa46780-909f-11eb-9f4d-30dc525aa885.png)

**Comment by schalkneethling** [comment]
Dang these things are so fragile 😢 Thank you for reporting @nt1m

**Comment by dveditz** [comment]
I'm sure not needed by the devs, but this specific example is on https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust in case other interested people want to see it "live". Click the black triangle in the Safari column of the compat table.

**Comment by jfkthame** [comment]
Looks like the problem arises because of
```
.ic-prefix::before {
  content: "-x-";
}
```
putting the content "-x-" in there, but the rule
```
.bc-icons i::before, .legend-icons::before {
  width: 18px;
}
```
makes the element too narrow for that to fit. Firefox refuses to break the line after the initial hyphen (so instead it overflows), but webkit/blink do break the line at the hyphen.

A simple fix would be to use `content: "\u2011x\u2011"` so that the hyphens are non-breaking; then the result in Safari looks similar to Firefox. (Though it would probably be better to avoid constraining the width so severely. If we want the content "-x-" in there, we should ensure the element is wide enough for it to fit.)

**Comment by caugner** [comment]
No longer an issue since the redesign.
