### ISSUE TITLE
Revisit SVG usage in CSS sidebar

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#3385]
@fiji-flo pointed out that perhaps the reason it's so slow is that it's so HUGE. 
Sure enough, the HTML blob in https://developer.mozilla.org/en-US/docs/Web/CSS/padding/index.json for example is 104KB. Yikes. Considering that 90% of that weight is visually hidden, it feels like a huge burden just to build that much just to not display it. 

Also, we discovered that there's a LOT of  in that HTML blob. If you replace every  block with a  the total weight goes down to 56KB. That might be quick boost on its own. It probably won't help our build times but it'll probably help users.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/3332#issuecomment-809696419_

**Comment by peterbe** [comment]
I'm not so sure now. I'm losing interest in any quick hacks on https://github.com/mdn/yari/issues/3332

The server-side rendered HTML would become ~40% smaller if you could React render the [sidebar based on an array of arrays](https://github.com/mdn/yari/discussions/2895) because it only includes the portion of the sidebar that you click. But because it'd include ALL possible sub-topics in the React state, expanding a node in the sidebar would be instant. 

But suppose we go for this, we can't use `<svg>` as part of the link text. It has to cascading CSSOM to be performant. 
The CSS pages' sidebar has 107 `<svg>` elements. It would be foolish to HTML encode that 107 times. So it would have to be dynamic in the React rendering (i.e. the `<RenderSidebar/>` would need to know when to inject a SVG).
(Yes, Brotli compressed anything that's repeated 107 times very well but it's still a lot of underperforming bloat for the browser to process)

**Comment by peterbe** [comment]
@schalkneethling Are you actively working on this? I actually think it's worth doing. ...if it's easy. 
The total weight of the 107 `<svg>` icons is 49KB which is repeated because the `sidebarHTML` is part of the JSON serialized state too. So it's 98KB to every single CSS page. 
This number isn't as bad when you Brotli compress the HTML. 
If we can replace this with external SVG icon URLs, I think it would be a huge improvement for users.

**Comment by peterbe** [comment]
@schalkneethling What would it take to change from `<svg>` to `<img src="...">`? We can't use the `webpack` stuff since these SVGs aren't rendered via React. What about if we just hardcode the URL to the SVG?

**Comment by schalkneethling** [comment]
> @schalkneethling What would it take to change from `<svg>` to `<img src="...">`? We can't use the `webpack` stuff since these SVGs aren't rendered via React. What about if we just hardcode the URL to the SVG?

My plan is to get to it this week. Just need to tie up a few pull requests and the work on the localized content notes.

**Comment by peterbe** [comment]
> > @schalkneethling What would it take to change from `<svg>` to `<img src="...">`? We can't use the `webpack` stuff since these SVGs aren't rendered via React. What about if we just hardcode the URL to the SVG?
> 
> My plan is to get to it this week. Just need to tie up a few pull requests and the work on the localized content notes.

I have time. I can tackle it if you're swamped.

**Comment by schalkneethling** [comment]
> > > @schalkneethling What would it take to change from `<svg>` to `<img src="...">`? We can't use the `webpack` stuff since these SVGs aren't rendered via React. What about if we just hardcode the URL to the SVG?
> > 
> > 
> > My plan is to get to it this week. Just need to tie up a few pull requests and the work on the localized content notes.
> 
> I have time. I can tackle it if you're swamped.

Thanks. All good though. Working on it at the moment.
