### ISSUE TITLE
PR updates not picked up by PR companion?

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#3506]
Great work on the preview URLs / the PR companion. Really love this!

In https://github.com/mdn/content/pull/4048 `innerHTML` [was updated](https://github.com/mdn/content/pull/4048/commits/dae2a86ad2bf654d0db549c031b4c905455a3c6a) to `textContent` in the code example but I still see `innerHTML` here: https://pr4048.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Document/caretPositionFromPoint

If a content PR sees updates, does the PR companion update the preview? Or is it caching on some side that prevents me from previewing the most current version of a PR?

**Comment by peterbe** [comment]
Caching. :(
You could test it by messing with the casing of the URL. E.g. https://pr4048.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Document/caretPositionFromPOINT

I don't know how to solve this. We could upload it to a different domain each time. E.g. `pr4048.content.dev.mdn.mozit.cloud` the first time and `pr4048-2.content.dev.mdn.mozit.cloud` the second time. 
Or we can attempt to send a CloudFront Cache invalidation request as part of the second upload. 

Because either of those would take some time, perhaps we can start by injecting a comment that mentions that caching could get in your way.

**Comment by peterbe** [comment]
@escattone How do you feel about the idea of sending a boto3 cache invalidation request. They're limited but we'd only sent it if the Deployer noticed that a file existed but had to be updated.

**Comment by escattone** [comment]
Just saw this, hi @Elchi3! I went ahead and disabled caching on the `*.content.dev.mdn.mozit.cloud` domains, since there's really no need for it (other than mimicking the functionality of `stage` and `prod`). So this issue should be resolved. Thanks for letting us know @Elchi3!

If we decide later that we'd like some caching, I could re-enable it and force it to something like a few minutes, but I don't see the need at this point in time.

**Comment by Elchi3** [comment]
Fantastic, thanks Ryan! 🎉

**Comment by peterbe** [comment]
> Just saw this, hi @Elchi3! I went ahead and disabled caching on the `*.content.dev.mdn.mozit.cloud` domains, since there's really no need for it (other than mimicking the functionality of `stage` and `prod`). So this issue should be resolved. Thanks for letting us know @Elchi3!
> 
> If we decide later that we'd like some caching, I could re-enable it and force it to something like a few minutes, but I don't see the need at this point in time.

That will disable the ability to push a branch of testing some web perf feature in Yari. E.g. my branch where I experimented with doing some lazy-loaded BCD tables. 

I would much prefer that we do this in the Deployer. We're very explicit about calling the Deployer. The call to `poetry run deployer upload ...` is distinct in the PR Review Companion compared to `dev-build.yml`. 
I'll make a PR about it and perhaps if that works, we can set the default caching back on that CloudFront instance.
