### ISSUE TITLE
[Minor] Issue with archived pages, top bar is missing z-index

### ISSUE THREAD

**Issue by ferrybig** [mdn/yari#3538]
1. Set the screen resolution to 1920x1080
2. Go to https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects (or any other page using this banner)
3. Observe the archived page bar

**Expected:**

I expected the top bar to be in the middle

**Actual:**

The text in the top bar is shifted to the right

![image](https://user-images.githubusercontent.com/1576684/115021154-e734c400-9ebb-11eb-96f0-895d31ed5406.png)

**Fix**

Add `left: 0;` to `.archived {` in the css file `index.scss`

**Comment by peterbe** [comment]
Archived pages are going to be deleted at the end of the quarter.

**Comment by tannerdolby** [comment]
@peterbe I just checked https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects at 1920x1080 and the issue still exists, do you want me to submit a fix (adding `left: 0;`) for this so the archived page banner text is atleast centered on larger viewports until archived pages are deleted at the end of quarter (which I'm not sure when this date is)?

**Comment by peterbe** [comment]
> do you want me to submit a fix [...snip...] Or do you think this is ready to be closed?

No fix necessary. These pages will be deleted off MDN first week of July this year. 
And I don't want to close it until that has officially happened. 

Thank you so much for thinking about a fix. 

Besides, one thing we can, today already (but perhaps merge it a little bit later),  do is find if that banner has any (S)CSS that we can now delete because it's going to just be an orphan that can never be used again.

**Comment by tannerdolby** [comment]
> No fix necessary. These pages will be deleted off MDN first week of July this year. And I don't want to close it until that has officially happened... Thank you so much for thinking about a fix.

Ok sounds good. And of course, your welcome!

> Besides, one thing we can, today already (but perhaps merge it a little bit later), do is find if that banner has any (S)CSS that we can now delete because it's going to just be an orphan that can never be used again.

That is a good idea! I will look for any scss that the banner uses and report back here because (if found), those scss styles can now be deleted since it will be an orphan after the first week of July like you mentioned.

**Comment by tannerdolby** [comment]
It looks there there was some scss associated with the `.archived` class for that top bar, I did a quick `git grep` search, the `.archived {}` scss declaration is only being used once:

```git
tannerdolby:yari TannerDolby$ git grep -n ".archived {"
client/src/document/index.scss:249:.archived {
```

and here is the corresponding scss within `client/src/document/client/index.scss`

```scss
/*
 * style for archived content banner
 * http://localhost:3000/en-us/docs/BrowserID/Specify_an_Email_Address
 */
.archived {
  background-color: $yellow-400;
  padding: math.div($base-spacing, 4);
  position: fixed;
  text-align: center;
  top: 0;
  width: 100%;

  p {
    margin: 0;
  }
}
```

plus the `<div>` element that represents that archived bar in HTML: 

```
tannerdolby:yari TannerDolby$ git grep -n "archived"
client/src/document/index.tsx:199:    <div className="archived">`
```

I assume since the class `.archived` is not longer going to be used in the className declaration in JSX, then we can probably go ahead and remove that entire `<div>` along with the scss. Submitting a PR that we can hold off on merging until ready.
