### ISSUE TITLE
Documentation page in other languages not found

### ISSUE THREAD

**Issue by sgarbini** [mdn/yari#3544]
Since im navigating with a spanish configured language when i try to enter the introduction documentation it automatically redirects to: "https://developer.mozilla.org/es/docs/Introduction", which derivates in "not found".
Im guessing there is not actually documentation in other non-english system configuration, like JP, BR, DE, etc etc).

Maybe it should redirect to "https://developer.mozilla.org/en/docs/Introduction" by default?.

**Comment by peterbe** [comment]
This is actually very interesting and I'm curious to solve this. 

What do you mean by "try to enter the introduction documentation"?

We use your cookie to redirect when the URL doesn't have a locale in it. 
```
▶ curl -I -H 'Cookie: preferredlocale=es' https://developer.mozilla.org/docs/Introduction
HTTP/2 302
content-length: 0
server: CloudFront
date: Mon, 19 Apr 2021 13:45:19 GMT
location: /es/docs/Introduction
```

But this is probably foolish because if that particular page doesn't exist, it would have been better to redirect to `/en-US/docs/Introduction`. 
The code that redirects is unable to know what Spanish translations exists so it's just being very (overly) optimistic.

**Comment by peterbe** [comment]
A curious thing, https://developer.mozilla.org/es/docs/Introduction is a plain 404 because it's unable to figure out that the correct `en-US` URL isn't https://developer.mozilla.org/en-US/docs/Introduction but https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction because of redirects.
