### ISSUE TITLE
Compress an SVG error?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3645]
I'm getting a CI error on https://github.com/mdn/content/pull/4505 asking me to run `--save-compression` on and SVG. That's a bug right?

**Comment by peterbe** [comment]
It's not a bug. The `imagemin-svg` library can turn that `.svg` file into a smaller `.svg` file. It does this by stripping extraneous whitespace and quoted attributes that can be spared. 

The problem is that this will force you to kinda ruin the file. It's a bit like saying; Your Photoshop file can be turned into a smaller JPG file! Fix it now!
But, like a Photoshop original file, you might want to open this `.svg` and work on it for a future revision. Hmm.

It's all happening because Yari expects the file attachments checked into the git repo to be perfect for serving. And here might be an exception because you might not want to optimize the `.svg`. 

One solution is to upload the `.svg` some other place. Like a dedicated git repo, a Gdrive, Dropbox, or S3 :) ...and then only check in the hyper-optimized `.svg` file into mdn/content. But all of that kinda sucks.

**Comment by hamishwillee** [comment]
@peterbe Yes, so as you imply, I did create this as an SVG to ease future editing (the original being in lucidcharts). Note that I use tools for editing - inkscape - which presumably would not be broken just by minification.

I would prefer to keep this with the docs. Could we make an exception for SVGs? Or perhaps have a rule that says a file under /uncompressed/ subfolder can exist uncompressed for exceptions?

**Comment by peterbe** [comment]
> I would prefer to keep this with the docs. Could we make an exception for SVGs? Or perhaps have a rule that says a file under /uncompressed/ subfolder can exist uncompressed for exceptions?

Mayhaps. Probably not quickly. I think we can start a chat about treating SVGs differently but if you want to get your content PR landed I think it's best to run the compression now and get CI to pass. *Then*, we can discuss changing the rules for `.svg` files. 
Does that make sense?

**Comment by Ryuno-Ki** [comment]
I took the liberty to fill https://github.com/mdn/yari/discussions/3652

**Comment by hamishwillee** [comment]
I am closing this, as it is not an error but a feature. SVGs are still editable even if compressed, so my justification for not wanting to compress is gone.
