### ISSUE TITLE
Consider more conservative flaw-fixing for xref macros

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#3687]
xref macros like [jsxref](https://github.com/mdn/yari/blob/main/kumascript/macros/jsxref.ejs), [cssxref](https://github.com/mdn/yari/blob/main/kumascript/macros/cssxref.ejs), or [domxref](https://github.com/mdn/yari/blob/main/kumascript/macros/domxref.ejs) typically take:

* one mandatory argument, which is the name of the thing to link to
* one optional argument, which is something to use for the link text

When we fix xref flaws, we sometimes change the value of the first argument. If the writer hadn't supplied a second argument, then that results in a change in the prose content of the page. In at least some cases this might make the page make less sense than it did before.

For example, I complained about this one: https://github.com/mdn/content/pull/4420#pullrequestreview-643743984. In the current page, the prose is like:

> _Date_ instances inherit their toString() method from _Date.prototype_, not _Object.prototype_.

After the flaws are fixed it would read:

> _Date_ instances inherit their toString() method from _Date_, not _Object_.

See also https://github.com/mdn/content/pull/3584#pullrequestreview-638191939 for a similar issue.

I'm actually on the fence about whether we should worry about this. But if we do think that these changes make the docs worse, or even that as a general principle fixing xref flaws should not change the prose content, then we could make flaw-fixing more conservative so it preserves the original text content, providing a second argument to the macro if necessary.

**Comment by peterbe** [comment]
But doesn't it happen because there is no `Date.prototype` page? So it'd weird to refer to it by that when there's no page with that title. Maybe there used to and *back then* it used to make sense to use `<code>Date.prototype</code>` as the link text. 

How are you supposed to know, with confidence, in automation, that it's wrong to discard that `.prototype` portion of the link text?

But is it not a solution that if the writer believes the `.prototype` "suffix" is useful, they first have to rewrite the use of `jsxref` to become this instead:
```
{{jsxref("Date", "Date.prototype")}}
```

What we *could* do, to avoid a bunch of fix fixable flaws work that reduce the quality of the content, is to make an exception that suggests that `{{jsxref("Date.prototype")}}` becomes `{{jsxref("Date", "Date.prototype")}}` instead. Just because it's the `jsxref` macro.

**Comment by wbamberg** [comment]
> So it'd weird to refer to it by that when there's no page with that title.

It's often the case that the link text isn't the title of the page. And it's also often the case that the surrounding text is written under an assumption that the link text is a particular string, and changing that makes the whole thing make less sense.

Here's another example of a place where fixing the flaw regressed the content: https://github.com/mdn/content/pull/4768.

**Comment by caugner** [comment]
> Here's another example of a place where fixing the flaw regressed the content:

@wbamberg Is this still an issue? And if you understand the problem better, what would you suggest to move forward?

**Comment by wbamberg** [comment]
I think we can close this. I think I understand the issue - flaw-fixing can sometimes change the link text in ways that the author didn't intend, and this can break the sense of the text - but I expect this is quite rare and probably at this point if it was going to happen it would have happened :).
