### ISSUE TITLE
Make all internal broken links red

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3799]
Currently links created with one of the xref macros are marked in red if the target page does not exist. This is great for authors  because it tells us that there is some content that needs to be written, and it is great for other readers, because they don't waste time following links to 404 errors.

IMO it is always better to be shown a red link for ANY broken internal links - not just macros - for the same reasons. It really doesn't matter _why_ it is broken, I never want to navigate away from my reading context to something I could know in advance does not exist. 

This might help with problems like: https://github.com/mdn/content/issues/4922

This continues discussion from https://github.com/mdn/content/issues/4570#issuecomment-831598775

**Comment by peterbe** [comment]
I actually like this! It's silly to present a link to a page that doesn't exist, and just going to lead to a 404 Page Not Found. 
However, here's how the red links are created from `smartLink()` inside KS macros:
```html
<a class="page-not-created" title="The documentation about this has not yet been written; please consider contributing!">
  <code>for each...in</code>
</a>
```
(from [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/57#javascript))

Can we think up a better tooltip text for that? Perhaps something that covers us from the fact that perhaps it used to work but has since become broken. 

My "fear" is that someone sees that and starts to create the page and doesn't realize it already exists but the link was badly pointed. 

Truth be told, perhaps the tooltip could be something we only bother with in Kumascript macros. But for all other internal links that won't work we just make them un-clickable and red without a tooltip.

**Comment by peterbe** [comment]
We chatted about this in the weekly Editorial meeting and at least 3 people said "Yes!" to this. 
Much better to do a red un-clickable link rather than a link that'll just lead to sadness. E.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter

**Comment by wbamberg** [comment]
It seems like there are a couple of things in here:
1. make links to nonexistent pages red (say) and unclickable
2. have a tooltip saying something like "The documentation about this has not yet been written; please consider contributing"

I can't see any downside to (1) but (2) is tricky because it will confuse people when the link is wrong or is pointing to a page we deleted. On the other hand that's already a problem for macro-generated links, and I agree it seems totally arbitrary to do it one way for macro-generated links, and the other way for plain links.

**Comment by peterbe** [comment]
> It seems like there are a couple of things in here:
> 
>     1. make links to nonexistent pages red (say) and unclickable
> 
>     2. have a tooltip saying something like "The documentation about this has not yet been written; please consider contributing"
> 
> 
> I can't see any downside to (1) but (2) is tricky because it will confuse people when the link is wrong or is pointing to a page we deleted. On the other hand that's already a problem for macro-generated links, and I agree it seems totally arbitrary to do it one way for macro-generated links, and the other way for plain links.

The 1. problem is taken care of by https://github.com/mdn/yari/pull/3815

But regarding 2., can you share some light on this question here: https://github.com/mdn/yari/pull/3815#issuecomment-842594946

The easiest thing would be to just do nothing (i.e. no tooltip for the broken links) but now's the good time to deal with it while our brains are active on this subject.
