### ISSUE TITLE
ESLint check of the Node CLI stuff

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#400]
In `create-content-from-mysql` we 3 groups of JavaScript code:

1. `content/scripts/**/*.js` and `server/**/*.js` - pure Node JavaScript
2. `ssr/*.js` - ES 6 code that gets compiled with Webpack to `ssr/dist/main.js` and some plain JS code like `ssr/browser-compatibility-table.js`
3. `client/src/**/*.js` - ES 6 code that quite possibly will be replaced with TypeScript and managed with the ESlint config we get from `create-react-app`. 

I don't know about you but I often make silly mistakes in (1) such as typos on variable names that I only find out about in runtime with a crash. It would be nice to have `eslint` check that code. We can worry about how and where to run that but at least it would be nice to start with something like `yarn workspace content run lint`. Then we can add it to CI and we can potentially integrate it into our IDEs. 

It doesn't need to be perfect but let's get something working that checks for easy mistakes.

The code in (2) we might want to use the same lint that we use in the `eslint` from `create-react-app` (3). Let's wait with that.

**Comment by peterbe** [comment]
@Gregoor Can you look at adding a script to `content` and `server` that checks for some decent checks that aren't style related?

**Comment by Gregoor** [comment]
Personally I think moving us to TS (workspace by workspace) is a better investment. I definitely don't like those typo runtime errors either, but ESLint is too surface-level there for my taste anyway. I.e. I don't want it to only throw when I do `tpyo()` but also when I do `notAtypo.tpyo()`, where the latter would be caught by a type-system, but not by a linter. Not that having the former isn't useful, I just tend to make both mistakes.

There might be other ESLint that would be worth adding but TS satisfy my more immediate needs tbh.

I wanted to post this comment when I also have the client TS PR ready but since I failed at setup yesterday and I don't want to lose this comment, I'm posting it now (without having any work towards it done yet)

**Comment by peterbe** [comment]
Ok. Don't give up on TS! And yeah, I think it's a good idea to get warmed up to TS on the client-side workspace.

**Comment by peterbe** [comment]
If time allows I would port all the `content/*.js` and `build/*.js` to `.ts` and that's it.
