### ISSUE TITLE
"No query, no results" displayed briefly but inappropriately

### ISSUE THREAD

**Issue by dandavison** [mdn/yari#4006]
Hi, thanks for your work on this great resource! I could not see an open issue for the following:

When I enter any query for the first time (I can see there is some caching, but not sure of the details), the words "No query, no results" are displayed briefly on the screen, despite the fact that the query does soon after return with results. For example, I just saw this now with https://developer.mozilla.org/en-US/search?q=throw.

However, it only occurs the first time I submit the query (I tried artificially slowing down the network requests in dev tools to see if I was just missing a very brief flash but that did not appear to be the case; it is pretty brief when it happens on first submit). It doesn't prevent me from using the site as intended of course.

**Comment by peterbe** [comment]
Yeah, it's not great. The page that loads the search results is a "skeleton" page, or a "single-page-app". It's static and it's XHR that replaces the skeleton with the search results once they come in from the API server. 

But actually, the way it works is that there are 3 phases:

1. The bare-bones HTML skeleton which says "No query, no results"
2. Once the JS loads it looks at the current document URL and sees `?q=throw` so it rewrites the heading to `Search results for: flow`
3. Once the XHR request (`/api/v1/search?q=flow&locale=en-US`) comes in, the heading doesn't change but underneath it fills in "Found 346 matches in 39 milliseconds." and the actual search results themselves. 

Your "concern" is actually between 1 and 2. From the bare-bones HTML and the JS loading. Clearly, it's not fast enough.

**Comment by peterbe** [comment]
I think it shouldn't say *anything* until we know. I.e. blank white nothingness. ...until the JS has loaded at least. 
Perhaps we can also include something like
```html
<noscript>Site-search depends on working JavaScript to be enabled and working.</noscript>
```
Most of the time (like, 95%) the JS loading is decently fast and then the "No query, no results" just flashes by. The user might think it's a bug or that it's just annoying flicker that makes them think "Something isn't right". 

We recently updated a lot of our loading placeholders so that for 1.5s they say nothing. Just white emptiness. ...until there's either something to replace it by or then it starts to say "Loading...". 
The argument is that flicker is worse than saying nothing. 

I would recommend we treat the search result page the same. Say nothing in the server-side rendered HTML and once the JS has loaded, it determines whether to says "Search results for: XXX" or "No query, no results" based on the `document.location.search`.

**Comment by d-g** [comment]
@peterbe wrote:
> Perhaps we can also include something like
> `<noscript>Site-search depends on working JavaScript to be enabled and working.</noscript>`

Absolutely must!  I had been under full impression that the search was simply broken (no much issue, googling works even better in some cases), until accidentally seeing this after several _months_ again have become curious enough to find this thread.

(Ideally, site-search should net depend on running client-side software, of course, and, irrc, some time ago, it did not; why had anyone decided to break it, I wonder.)

**Comment by caugner** [comment]
I have seen that "No query, no results" message today when testing MDN on an e-book reader, so let's accept a PR that adds a suitable `<noscript>` tag.
