### ISSUE TITLE
Improve message displayed by {{Specifications}} when not on a standard track and bcd present

### ISSUE THREAD

**Issue by teoli2003** [mdn/yari#4012]
As non-standard features should (most of the time) have no spec_url data in mdn/browser-compat-data, the following displayed message is misleading:
<img width="1029" alt="Screen Shot 2021-06-12 at 13 10 18" src="https://user-images.githubusercontent.com/1466293/121774175-514aac00-cb81-11eb-9bcb-77fa01a3d226.png">

I think that, when the three following conditions are met **at the same time**:
1) a bcd entry for this feature exists in mdn/browser-compat-data,
2) no `"spec_url"` specified in it,
3) `"standard_track"` is `false`,

we should display something like:
<img width="1065" alt="Screen Shot 2021-06-12 at 13 49 17" src="https://user-images.githubusercontent.com/1466293/121774936-0a5eb580-cb85-11eb-840b-1eacd74340d7.png">

(The text is just a rough idea, hastily hacked together)

In all other cases (no bcd entry, or a spec_url given, or on the standard_track) the current message would still be displayed.

**Comment by Elchi3** [comment]
I think the current messaging isn't great but I'm not sure I agree with having a banner at the location of the "Specification" section. It might be better to omit the whole "Specification" section in this scenario. Maybe authors should not call {{Specifications)}} / add a "Specification" section in this scenario or, if they do, we could check for your conditions and make it a no-op.

I think displaying BCD-sourced banners at the top of the page for non-standard/deprecated/etc is brainstormed about in some other issue and so I would like to move this problem over there as I think unified banners would be a much better experience for the reader.

**Comment by peterbe** [comment]
> I think displaying BCD-sourced banners at the top of the page for non-standard/deprecated/etc is brainstormed about in some other issue

https://github.com/mdn/yari/discussions/2905 and in particular https://github.com/mdn/yari/discussions/2905#discussioncomment-618185

But that particular plan one solved for "deprecated", not necessarily "non-standard". But it can be made generic. 

Which brings me to the next point...



> check for your conditions and make [the Specifications table] a no-op

Since the Yari builder controls the whole section (the `<h2>` and the `<table>`) it can pretty easily decide to return nothing. 
But isn't it a bit weird though? 

I think the author should choose to not include `{{Specifications}}` if it's wrong to get that yellow warning message. It puts the power into the hands of the writer instead of making in the Yari builder more business-logic'y. 

Also, @teoli2003 I know your suggested text was just a rough draft to inspire ideas but I think, in general, it's a safer bet to only say what's 100% certain. "No specification data found" is an indisputable fact but saying that browser vendors are not trying to implement it is too big a statement.  Does that make sense?

**Comment by Elchi3** [comment]
> I think the author should choose to not include `{{Specifications}}` if it's wrong to get that yellow warning message. It puts the power into the hands of the writer instead of making in the Yari builder more business-logic'y.

Yes, this makes sense to me. In many cases the standardization situation is weird when no spec could be found so a custom text explaining what's going on seems better than having the macro display anything generic.

**Comment by teoli2003** [comment]
I will try custom texts on different cases. I will make PRs for each API on mdn/content, we will se what we will learn from it (doing PRs/getting them reviewed). I'll link the meta-bug there to this one for future record.

Meanwhile I'm closing this.
