### ISSUE TITLE
Add (back) an Edit button in every MDN article

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#4048]
We can make every MDN article have a prominent <kbd><b>Edit</b></kbd> button once again.

Is there any reason not to?

What I mean is, given https://developer.mozilla.org/en-US/docs/Web/API/MediaStream, the <kbd><b>Edit</b></kbd> button would take the user to https://github.com/mdn/content/edit/main/files/en-us/web/api/mediastream/index.html. For users who already have GitHub accounts, that would immediately put them into the editing UI for that article. And for users who don’t yet have GitHub accounts or who are logged out, that would prompt them to create an account or sign in (and after signing in, they’d get redirected to the editing UI).

The good reasons for doing this include: for new users, it makes this very simple and straightforward to directly start editing an article for the first time — and for returning users who contributed in the wiki days, it gives them back the familiar <kbd><b>Edit</b></kbd> button they’re looking for. (*“Where’d the edit button go?”* is a question we regularly get from such returning contributors.)

If we had that <kbd><b>Edit</b></kbd> button, it seems clear we’re likely to significantly more users taking time to create PRs. So of course a possible cost of that it that we’d need to spend more time on reviewing PRs — and maybe need to have more reviewers. But I assert that it would also help *reduce* time that we’re already spending — which is time that we spend on reading and responding to *issues* submitted by users who otherwise might have created PRs if we’d made it easier for them.

**Comment by peterbe** [comment]
Drive-by comment; 

1. We could make the button only appear if you're signed in to MDN and you used GitHub. 
2. I like it in general! It's engaging. Definitely throws you into the deep-end but for 90+% of the people who have a GitHub account, it's not going to be surprising. 
3. What does @Rumyra think about this idea? She talked about possible low-tech solutions to get people to make more PRs instead of just issues. 
4. Perhaps a press on the button could pop up a menu with links to a bunch of other things such as "How to test it locally. How to file an issue. A link to a YouTube screencast of someone making a PR entirely via the GitHub UI."

**Comment by Rumyra** [comment]
I agree - this could be a good solution to persuading people to create PRs instead of issues - and yes we'd have to think about the overhead, but by and large issues will become PRs anyway, so we can take out one less step (we still have to triage the issue _and_ review the PR).

@sideshowbarker I'll reference this within my proposal for process review 👍

Yes @peterbe I think I'm coming to a conclusion much like point 4 - at least something which is clear about options

**Comment by peterbe** [comment]
@Rumyra To make this momentum of this issue moving forward I think the next action is, for you, to add this to the list of yari feature request triaging. I don't think it needs to be perfected before it can be filed as a feature request. People like Daryl, Hermina, and Schalk will have really good suggestions too. The feature request is ultimately to make it more inviting to make readers actively participating in changing the content. The rest is details :)

Personally, I think the suggestion is a good one. At least a very good start. @sideshowbarker definitely knows about improving the content. Making it better/easier/faster/more pleasant to edit the content isn't about making the writer's lives easier, it's about making MDN better because "content is king". With more/better content, it has a direct impact on the success of MDN Plus.

**Comment by sideshowbarker** [comment]
> 1. We could make the button only appear if you're signed in to MDN and you used GitHub.

I would advocate strongly for making the button appear all the time, regardless. Here’s why:

We currently have a total of 751 unique contributors who had a PR merged into mdn/content.

Among those 751 contributors, 574 are people who’ve contributed exactly once. That’s basically 75% of our contributors who are first-time contributors.

And every time I review a PR from a first-time contributor, I check their GitHub user profile to try to learn a little bit about what. And what I’ve found is that quite often, they created their GitHub account on the same day they contributed their MDN PR.

In other words, the reason many of our first-time contributors were motivated to create their GitHub accounts was directly for the purpose of making a change to some particular MDN article they found a problem in.

So for many of our contributors, getting onboarded to contributing to MDN also drove their onboarding to GitHub.

That seems like a pretty cool thing for us to be happy about having made happen — and I think it’s worth it to try to make that happen more, as much as we can.

So, I think to get more people involved, and contributing to begin with, it’s important that we have some form of an <b>Edit</b> button show up even for people who aren’t logged into GitHub or who don’t even yet have a GitHub account.

**Comment by sideshowbarker** [comment]
> The feature request is ultimately to make it more inviting to make readers actively participating in changing the content. The rest is details :)

Exactly. I have no domain expertise as all in UX, and my suggestion about the <b>Edit</b> button is really a broader suggestion that we do more to make it very clear to every reading that *“You have the power and opportunity to edit, change, and improve the article you’re reading right now.“*

That’s too much text to try to squeeze into one button :) but I’m certain that others with UX chops can figure out some good ways to have the MDN UI convey that message more clearly.

I just think the <b>Edit</b> is something that minimally and succinctly help to convey that.

**Comment by hamishwillee** [comment]
This is why I was pushing for an "edit on github" link rather than "source on github" last time this discussion came round. We need to make it easy to edit for the 90%.  This makes even more sense as we move to markdown and the chance of screwing up the layout is reduced. I feel vindicated ;-). 

FWIW
- I like the idea of an Edit button over the Edit link  #4175 - the edit link a good step, but it isn't particularly visible. 
- The simplicity of an edit button taking you to the open-for-edit github page is great and reasonable. But I love the flaw checker tools. So perhaps we should consider @peterbe suggestion in https://github.com/mdn/yari/issues/4048#issuecomment-864302405
  > Perhaps a press on the button could pop up a menu with links to a bunch of other things such as "How to test it locally. How to file an issue. A link to a YouTube screencast of someone making a PR entirely via the GitHub UI."
  
  Maybe have have click take you to github to edit, but hover give you a popup with simple options "Simple fix (e.g. typo)" and "Significant fix" (or similar).
