### ISSUE TITLE
Oddly placed <body> tag underneath Specifications for offset-path page

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4059]
On https://developer.mozilla.org/en-US/docs/Web/CSS/offset-path it doesn't look like the `<p><body></p>` tag is meant to be underneath the Specifications heading. I couldn't find any other pages that have text after the `<h2>Specifications</h2>` but before the `<table>`. Is this a bug or intended?

The `<th>` elements are also missing the `scope="col"`attribute which is assigned in `client/src/document/ingredients/spec-section.tsx` as another functional component `SpecficationSection` returning the fragment. All the other elements inside `<tbody>` received the classes and attributes as expected.

<img width="1085" alt="Screen Shot 2021-06-19 at 1 58 29 PM" src="https://user-images.githubusercontent.com/48612525/122655637-c3366e80-d108-11eb-81b6-68692493ba9b.png">

For some of the other pages, like https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path the `<table class="standard-table">` element is adjacent to the `<h2>Specifications</h2>` and doesn't have a parent div. But for some reason on the `offset-path` page, the `.standard-table` is wrapped in a `<div>` and has that weird `<p>` tag as the immediate child with the text `<body>` tag as plain text. Other pages indeed also have the `.standard-table` nested in a `<div>` but the `<table>` is the only nested content (no `<p>` tags or anything else as children).

**Comment by tannerdolby** [comment]
I found out where these tables are being created in `client/src/stories/atoms/tables.stories.js` with the functional component `standardTables`, I don't see any `<p>` tag that could have made its way above the `<table>` in the returned JSX, so that `<p><body</p>` must be trickling down from somewhere else.

**Comment by peterbe** [comment]
CC @Elchi3 
Here's kinda the explanation for the problem: https://github.com/mdn/content/blob/83a9d51b9d5c85fa29f08cd6cb24a8d64599a9de/files/en-us/web/css/offset-path/index.html#L152

If you remove that odd little tag, the Yari builder can now successfully work. 

In the Yari builder, it expects the Specifications table to come from a `{{Specifications}}` and if it doesn't it's supposed to let it be left as the legacy HTML it always was. Clearly, something isn't working. It sees the `<h2 id="Specifications">Specifications</h2>` in the HTML but can't process that. Going to take a look. We probably only want to add better error messaging or something. Because on this page it hasn't yet got the `{{Specifications}}` which it probably should.

**Comment by peterbe** [comment]
Actually, on closer inspection, there's no bug in the Yari builder. It was just an odd `<p>&lt;body&gt;</p>` that was of the content and has been like that since the initial Yari migration. 
In https://github.com/mdn/content/pull/6237 I not deleted the "junk" but I also took the opportunity to "upgrade" to `{{Specifications}}` which appears to work.

**Comment by tannerdolby** [comment]
> Actually, on closer inspection, there's no bug in the Yari builder. It was just an odd <p>&lt;body&gt;</p> that was of the content and has been like that since the initial Yari migration.

Ok good, it honestly seemed like a just a misplaced bit of HTML. Oh well, atleast this inspired conversation to "upgrade" the `{{Specifications}}` 😄
