### ISSUE TITLE
Some pages show raw math syntax (LaTeX?)

### ISSUE THREAD

**Issue by foolip** [mdn/yari#4197]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave

#### What information was incorrect, unhelpful, or incomplete?

"\left(a+bi\right)e^{i} , \left(c+di\right)e^{2i} , \left(f+gi\right)e^{3i}" appears on this page, which is unreadable. It looks a bit like LaTeX, presumably this was once turned into a math image?

#### Specific section or headline?

* https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave#example
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/PI
* https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

#### What did you expect to see?

No expectations, just not this :)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/periodicwave`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/PeriodicWave
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/periodicwave/index.html
* Last commit: https://github.com/mdn/content/commit/babc0473793bbe3cfa66cd96fae7f84348be373b
* Document last modified: 2021-02-08T10:05:46.000Z

</details>

**Comment by peterbe** [comment]
Solving this won't be easy because we can't add a polyfill that slows down people (with more JS) on every single page. 
99% of pages don't have MathML on them. The majority of our traffic is Chrome and Chrome would need the polyfill. So for 99% of pages, it would be a waste to have to download this polyfill. 

The ideal thing would be if *the document itself* could be aware that it needs polyfills and then that gets automatically injected into the DOM based on the document. Then, the 99% of pages don't get a heavy polyfill and the few pages that needs it get nice equations in Chrome (and any other browser that needs it). 

What if we put into the front-matter, some sort of clue about it needing a polyfill and then the `<Document>` component can be fed this and it then injects a `<script src="polyfills-r-us.biz/mathml"></script>`. Would that be a solution?

**Comment by wbamberg** [comment]
Personally I'm not too keen on using front matter for implementation specifics like this, but I take your point. Could the builder look for `<math>` elements in the page and insert a polyfill based on that?

**Comment by peterbe** [comment]
Here's how the old Kuma used to solve it: https://github.com/mdn/kuma/pull/6546/files
I think it's time to revive that because it didn't make it across to Yari. But this time, let's take a fresh look at it so we do it in an optimal way.

**Comment by hinell** [comment]
Cutting out formulae I think is viable option. It can be saved to Wikipedia and linked. Cheap & quick.

**Comment by its4zahoor** [comment]
The [Math.log10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10 ) is still showing raw math syntax.

![MathLog10_LaTeX](https://user-images.githubusercontent.com/24554084/142500705-8784c206-38fb-4dee-be09-de1d8fbef8e3.png)

**Comment by hamishwillee** [comment]
@schalkneethling Is this something you might help with?

**Comment by schalkneethling** [comment]
> @schalkneethling Is this something you might help with?

Yes! I will bump this up. We looked into this and then it lost momentum with all the things that happened. I will add these to my priority list. Thanks for the ping @hamishwillee and @its4zahoor

**Comment by himanshugarg** [comment]
> MathJax is gone for good.

Sorry for reusing this issue. The only one returned when searching for MathJax. Just for my own understanding for similar situations in future - we don't use MathJax because that would add a dependency on every page on MDN, right? Or is there more to it?

**Comment by schalkneethling** [comment]
> > MathJax is gone for good.
> 
> Sorry for reusing this issue. The only one returned when searching for MathJax. Just for my own understanding for similar situations in future - we don't use MathJax because that would add a potentially heavy dependency on every page on MDN, right? Or is there more to it?

From what I understand the examples on MDN does not warrant something like MathJax and the CSS solution we added is good enough? It might be worth considering MathJax as I note their statement regarding accessibility https://www.mathjax.org/#a11y

The way we currently do it does no add the CSS to every page but, only to pages that has ` math` element and then only if viewed in a browser that does not support MathML. We could probably do the exact same thing with MathJax.

Thoughts @ddbeck and @Rumyra? Is the current solution good enough and accessible? Should we consider MathJax? Thanks!

**Comment by Rumyra** [comment]
We'll be doing an accessibility audit over the coming months and will circle back to this should any issues arise 👍

**Comment by Josh-Cena** [comment]
Hi, bringing this up because the big chunks of MathML aren't really maintainable on MDN. If the entire MathJax bundle is too big, is server-side rendering an option? Can we use a Markdown plugin (Rehype, I suppose) and statically transform TeX to MathML with KaTeX/MathJax? This way we only need to send the CSS bundle, and we can even code-split that like we currently do.
