### ISSUE TITLE
Broken example link for German page

### ISSUE THREAD

**Issue by kilianpr** [mdn/yari#4237]
The examples on the German "Using CSS animations" page (https://developer.mozilla.org/de/docs/Web/CSS/CSS_Animations/Using_CSS_animations) do not work. 
Apparently the links to them are broken since example pages like this do not exist:
https://yari-demos.prod.mdn.mozit.cloud/de/docs/Web/CSS/CSS_Animations/Using_CSS_animations/_sample_.Making_it_repeat.html
![image](https://user-images.githubusercontent.com/66221972/126058859-41db02a2-7d64-43a1-9741-c827b0a6823e.png)

However, if you replace the "/de" in the link with "/en-US" it all works fine.

So apparently the links just have to be changed by replacing every "/de" with "/en-US" in order to make the German page work properly.

**Comment by peterbe** [comment]
The reason it's not working is boring trivial, at first. Arguments to `{{EmbedLiveSample("THIS_HERE")}}` needs to match some `<h2 id="THIS_HERE">` or `<h3 id="THIS_HERE">`. But as you can see, in the `de` content it says:

```html
<p>{{EmbedLiveSample("Making_text_slide_across_the_browser_window","100%","250")}}</p>
```

but there's no:
```html
<h2 id="Making_text_slide_across_the_browser_window">
```
that's why we're getting the error. 

We can fix the German page but we don't support the German translation because there is no German community of people willing to act as a team of reviewers. (We can talk more about this later, if you're interested)


Now, there's a more interesting effect. Because the `EmbedLiveSample` goes wrong, it means, in production, it can't create one of those `_sample_.Making_text_slide_across_the_browser_window.html` files. Because the `iframe` can't know that, what ultimately happens is you end up with this:

```html
<iframe src="this/page/will/404">
```
And because our 404 HTML page doesn't allow to be inside an iframe, it looks like this:

<img width="869" alt="Screen Shot 2021-07-19 at 10 58 13 AM" src="https://user-images.githubusercontent.com/26739/126181130-52490b33-6e60-4042-b6cc-6d4532e0decb.png">

Whereas in local development, at least it spits out the error:

<img width="936" alt="Screen Shot 2021-07-19 at 10 58 45 AM" src="https://user-images.githubusercontent.com/26739/126181228-7c26a871-fecc-45ad-9a16-bbbe047b5246.png">

What we *could* do is instead of *not* creating that `_sample_.Making_text_slide_across_the_browser_window.html` (because it didn't work), we create the file anyway but put the error message into it. What do you think about that @escattone ?
Another, similar, option would be to create a generic production-grade error message. E.g.:

```js
let liveSampleHTML = ''
try {
   liveSampleHTML = renderLiveSample(arguments...)
} catch (error) {
  // The live sample failed for some reason
  liveSampleHTML = "Generating the live sample failed. Perhaps file an issue or get involved with a fix yourself."
}
fs.writeFileSync(`_sample_.${ID}.html`, liveSampleHTML, 'utf-8')
```

Then it doesn't look so terrible when viewed in production. Because even if we fix the iframe problem with the `404.html` page, it would still not look nice.

**Comment by peterbe** [comment]
https://github.com/mdn/translated-content/pull/1611 fixes the content but that's just a quick fix. We still should seriously consider dealing with EmbedLiveSample errors better.

**Comment by Kilianpr** [comment]
Thank you for the detailed explanation of the error, now I understand why the link can't just simply be replaced.

Regarding the community of reviewers, I would be interested. However, I am still a student and have no sophisticated knowledge in any of these topics yet. So I don't know if I am qualified enough to do this.
Could you give me some more information about that?

**Comment by peterbe** [comment]
> Thank you for the detailed explanation of the error, now I understand why the link can't just simply be replaced.
> 
> Regarding the community of reviewers, I would be interested. However, I am still a student and have no sophisticated knowledge in any of these topics yet. So I don't know if I am qualified enough to do this.
> Could you give me some more information about that?

You don't need "sophisticated knowledge in any of these topics". It's just translations. But of course, it helps a little, when doing any translations, to understand some of the technical (web dev) terms in your own native language. 

@Rumyra What's the link to that page about starting a translation community?

**Comment by Kilianpr** [comment]
If it is only translations, I should be able to help with that.
Would the amount of work I'll put in be flexible?

**Comment by peterbe** [comment]
> Would the amount of work I'd put in be flexible?

Super flexible. No actual commitment. But if the team isn't large enough it won't be a team.

**Comment by Kilianpr** [comment]
> Super flexible. No actual commitment. But if the team isn't large enough it won't be a team.

Sounds good. Then what would be the first step?

**Comment by peterbe** [comment]
@Rumyra Can you point to the links where it describes how someone can start a translation community?

**Comment by Ryuno-Ki** [comment]
@kilianpr If you need another translator, let me know. I have some experience with translating as well as the subject matter (but translating everything alone would stretch me too thin).

**Comment by peterbe** [comment]
> @kilianpr If you need another translator, let me know. I have some experience with translating as well as the subject matter (but translating everything alone would stretch me too thin).

What would be HUUGELY helpful is for someone to just go through the `de` content and conclude: "This is too out-of-date compared to en-US that's best to just delete it."

I did that last week with a bunch of `de` docs that I found were mostly still in English. 
What used to happen in the old Wiki was that translators would first start by *cloning* from `en-US` to `de` and then get to work. What often happened, sadly, but understandably, is that the translator did the first 1-3 paragraphs and then got distracted or bored or just gave up. 

If you can find really inaccurate and out-of-date translations, it's much better for a German reader, we believe, to get up-to-date accurate content even if they have to read it in English. For example, a lot of translations don't have the new Browser Compatibility Tables. It might even make it easier for German translators to start over a lot of times than trying to diff and figure out what's missing in an existing translation.

**Comment by kilianpr** [comment]
> @kilianpr If you need another translator, let me know. I have some experience with translating as well as the subject matter (but translating everything alone would stretch me too thin).

I have not started translating anything since a German translation community has to be set up first.
But of course, once that is done, any help is greatly appreciated. In order to form such a community there are at least two people needed anyway.


@peterbe Is the following link the one you meant? https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1
