### ISSUE TITLE
suggestion: alternate lang <link />s missing in PageNotFound with page available in other lang

### ISSUE THREAD

**Issue by burtek** [mdn/yari#4239]
Consider https://developer.mozilla.org/pl/docs/Web/API/Node/nodeType

This URL references polish language page, that does not exist. There is an english version though, as indicated by the website:
![image](https://user-images.githubusercontent.com/2940958/126080300-6c0292fb-77bc-4a73-95e1-1739413679e7.png)

In page source I'd imagine a `link[rel="alternate"]` pointing to page about same API in different (exisiting) translations (incl. english one, since it's found as shown above, i.e. `<link rel="alternate" title="Node.nodeType" href="https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType" hreflang="en">`), but there is no such tag

Not sure if bug or lack of feature (I guess it's the latter), but it would be nice to have that, as browser extensions that force MDN language could use that to auto-redirect to other exisiting language

**Comment by peterbe** [comment]
What browser extension supports that?

**Comment by tannerdolby** [comment]
It seems `<link rel="alternate" hreflang="some-lang">` doesn't have very much documentation on its browser support (or atleast its not easily found). I checked https://caniuse.com/ and the data isn't supported for `<link rel="alternate">` and therefore `hreflang` as well. 

https://developers.google.com/search/docs/advanced/crawling/localized-versions provides some solid info on using `<link rel="alternate" hreflang="x">`. They state there are three ways to accomplish this:

1. HTML with `<link rel="alternate" hreflang="lang">`
2. HTTP headers
3. Sitemap

I think the HTML element route is probably most suitable here.

**Comment by tannerdolby** [comment]
I do agree, having the `<link rel="alternate" href="https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType" hreflang="en">` element added would make sure the alternate URL is redirect to when this scenario of page not found due to a certain language not being available. Without a `<link rel="alternate" hreflang="">` element (or defined in sitemap/headers) then google will do its best to choose the most relevant version to the user.

`rel="alternate" hreflang="lang"` signals that this page has a relationship to an alternate language version at a specified URL.

### Potential fix: 

At 11:31 in the [video](https://www.youtube.com/watch?v=8ce9jv91beQ), for the use case of full-translations with country-based variations, each page will list ALL alternates including itself with `<link rel="alternate" hreflang="">`. 

Adding `<link rel="alternate" hreflang="en" href="https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType">` will fix the problem discussed in this issue and redirect to https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType.

This was quite an information dump, but it is important how/where we define these alternates (ie in sitemap, markup or headers).

**Comment by caugner** [comment]
It's a nice idea, but if I understand it correctly, providing that additional `<link>` does not really have any effect beyond what we already achieve with our sitemap.
