### ISSUE TITLE
Issue with "Operator precedence": Code in tables is undreadable

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/yari#4254]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

The code blocks inside the table are unreadable.

#### Specific section or headline?

All `<pre>` blocks inside tables

#### What did you expect to see?

A code block similar to the ones outside of tables.

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.html
* Last commit: https://github.com/mdn/content/commit/820366ad598606491181dc7c38004347884e9660
* Document last modified: 2021-04-19T08:04:23.000Z

</details>

**Comment by peterbe** [comment]
@schalkneethling Wanna take this one?

**Comment by tannerdolby** [comment]
Yeah, this definitely needs to be updated. The color contrast is really bad and creates for a very hard to read code block.

<img width="987" alt="Screen Shot 2021-07-21 at 1 35 03 AM" src="https://user-images.githubusercontent.com/48612525/126458303-292ff38c-ac68-4a3a-9042-26289bdd4b5f.png">

the `pre code` styles are being overridden by `table code`

```css
table pre {
    background-color: #6d6d6d;
}

code, pre {
    background-color: #f4f4f4;
}
```

**Comment by tannerdolby** [comment]
> WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders). WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.

This might have been part of the redesign, but the `background-color` for `table pre` needs to be updated, as all the text in these code blocks are failing WCAG AA and AAA contrast ratio requirements.

Most of the `font-color`'s (red, black, green, blue) inside the code blocks are not meeting AA or AAA WCAG standards for contrast ratio by a long shot. Some of the text is even the same color as the background, like the `<span class="token punctuation">(</span>` elements.

https://webaim.org/resources/contrastchecker/ - verify contrast ratios

<img width="888" alt="Screen Shot 2021-07-21 at 1 39 37 AM" src="https://user-images.githubusercontent.com/48612525/126458763-c6efa518-677c-466f-9274-754ba1369111.png">

- Foreground: #005a38 - Background: #6d6d6d - 1.61:1 (Failed)
- Foreground: #1b1b1b - Background: #6d6d6d - 3.32:1 (Fails for everything except AA large text and graphical objects)
- Foreground: #005a38 - Background: #6d6d6d - 1.61:1 (Failed)
- Foreground: #005282 - Background: #6d6d6d - 1:6:1 (Failed)
- Foreground: #db000e - Background: #6d6d6d - 1:1 (Failed)

**Comment by tannerdolby** [comment]
Falling back to the `pre code` background of `#f4f4f4` could work, but because its so close to the background color of the table and its hard to differentiate between the two. And since the blue border on the left is there, I expect it to be "separate" content from the background color.

<img width="960" alt="Screen Shot 2021-07-21 at 1 48 26 AM" src="https://user-images.githubusercontent.com/48612525/126460063-394e0885-7823-46a0-a640-ca8bafa2bb5b.png">

If we instead change the background-color for `table pre` to be `#eee` then its much easier to read the code blocks and contrast ratios are met (AA and AAA). 

<img width="954" alt="Screen Shot 2021-07-21 at 1 59 45 AM" src="https://user-images.githubusercontent.com/48612525/126461705-376fbcf0-af3c-4666-b03b-718783fe842a.png">

It could also be changed to a white background `#fff` but that looks a bit "bright" compared to the grayish `#eee` color.

<img width="957" alt="Screen Shot 2021-07-21 at 1 57 48 AM" src="https://user-images.githubusercontent.com/48612525/126461482-1e64be1e-38f3-4d87-b1fc-f565b565bff8.png">

**Comment by tannerdolby** [comment]
Found the line in `mdn/minimalist` where this style declaration is happening, `sass/atoms/_tables.scss`

https://github.com/mdn/mdn-minimalist/blob/main/sass/atoms/_tables.scss#L45-L47

```css
  pre {
    background-color: $mdn-neutral600;
  }
```

Since the `$mdn-neutral` palette doesn't provide a "lighter" color than `#f4f4f4`, I added another Sass variable as `$lightgray: #eee` to then update the styles in `_tables.scss`

```css
pre {
  background-color: $lightgray;
}
```

**Comment by schalkneethling** [comment]
Will be fixed by https://github.com/mdn/mdn-minimalist/pull/711
