### ISSUE TITLE
Please don't force translated version of an article instead of English original

### ISSUE THREAD

**Issue by odragora** [mdn/yari#4271]
When I open an MDN article found by a search engine, it automatically loads a translated version of the page.
Previously there was a button "Switch to English" at the top of each article.
It doesn't exist anymore.

Please don't do that.

English is a sole language I use when doing any research related to my job.
I believe I'm not alone in this.
I don't need to be forced to read the technical documentation in any other language.

**Comment by odragora** [comment]
I think it's worth noting that when I click "Change language" button, there is no English language in the dropdown.
And at the top of the page there is a note saying that "This page was translated from English by the community".

**Comment by peterbe** [comment]
The reason you got the translated version was probably because Google presented a `/ru/` link to you. And it's very possible that the URL lead to a redirect which can happen if that URL is slightly out of date and thus doesn't existing in English anymore. So you end up in a URL that contains `/orphaned/`. 

The reason there is no "View in English" is because the page you're on can't work simply by replacing `/ru/` with `/en-US/`. 

But there are some things I don't understand. 

A) How did you stumble into this URL? 
B) Why does `/ru/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Array/some` exist at all when `/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some` exists?! 

We might have a problem with pruning @escattone

**Comment by odragora** [comment]
Thank you for looking into this and giving an explanation @peterbe .

> But there are some things I don't understand.
> 
> A) How did you stumble into this URL?

I just made a Google search, and this is where the top result led me.
It was also the only result from MDN leading to the _Array.prototype.some()_ article.

**Comment by odragora** [comment]
Also, when I hover over the search result, the link looks like this:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/8157117/126537187-033b603e-bbe3-4d41-800a-c3412cc2326f.png">
So it seems like the URL is indeed being changed at some point.

**Comment by caugner** [comment]
Hi @odragora, could you check whether this is still a problem after [our redesign](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/)? I feel like it could have been resolved.

**Comment by odragora** [comment]
@caugner Now the pages are loaded in my local language, and in order to get English version I have to dig through the options in the dropdown.

There is no separate "view original in English" button anymore.

It's a huge UX quality regression, in my opinion.

**Comment by caugner** [comment]
Closing in favor of https://github.com/mdn/yari/issues/2724.
