### ISSUE TITLE
Wrong path in production mode

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#4288]
- **problem:** The production search path for Promise.allSettled is orphaned based.
  - Please note that this isn't limited to the `Promise.allSettled()`: Any random pages of JavaScript I checked redirects to /orphanes/.... Maybe related to markdown conversion.

A while ago I went through a PR to remove conflicts/orphans for each locale of translated content. I don't know if it's because of that, but the current path is strange for several URLs. The path is orphaned based. It seems to be a yari problem, so I left an issue.

Below is the PR and the URL where the problem occurs. **(The URL is just one example among many.)**

- [delete conflicting/orphaned in ko](https://github.com/mdn/translated-content/pull/1423)
- https://developer.mozilla.org/ko/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

Another locales also have a problem.

- https://developer.mozilla.org/fr/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Promise/allSettled
- https://developer.mozilla.org/ja/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by hochan222** [comment]
@peterbe Was there something wrong with the related part at that time?

**Comment by alattalatta** [comment]
Please note that this isn't limited to the `Promise.allSettled()`: Any random pages of JavaScript I checked redirects to `/orphanes/...`. Maybe related to markdown conversion.

**Comment by alattalatta** [comment]
https://github.com/mdn/yari/blob/6f66eb8f670699766ea8be46a50accf72ddafe1d/build/sync-translated-content.js#L151

Difference of file extension (*.html vs. *.md) seems to be the cause.

**Comment by peterbe** [comment]
Definitely related to the Markdown conversion :(
See https://github.com/mdn/yari/blob/f6f528b654532572f24f682b5094dd67275d4a6b/build/sync-translated-content.js#L32

The last run of "Sync Translated Content", [yesterday](https://github.com/mdn/translated-content/actions/runs/1058095750), attempted a MASSIVE move of documents to `orphaned`. But if you look closely at https://github.com/mdn/translated-content/runs/3139496287?check_suite_focus=true you'll see that it failed. 

Anyway, the "Sync Translated Content" is currently broken and because of that, I've disabled the job. It can be re-enabled here: https://github.com/mdn/translated-content/actions/workflows/sync-translated-content.yml

**Comment by peterbe** [comment]
The sad news @hochan222 @SphinxKnight @alattalatta, because it's got wrong in the past, we have to now move them all back from the orphaned folders. I can help with that.

**Comment by peterbe** [comment]
See PR ^ links above. This should hopefully unbreak the files that incorrectly got moved into `orphaned`. 

@fiji-flo Can you take care of the bug in "Sync Translated Content" and re-enable the workflow?

**Comment by peterbe** [comment]
Actually, https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled is still a mystery. 
When I run it locally, it doesn't redirect 
I.e. http://localhost:5000/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled works fine. I don't see why it redirects in production. If it's just because production is slightly behind in time, I can't find where and what point it *was* a redirect.

**Comment by alattalatta** [comment]
Uh, so it looks like Korean wasn't affected file-wise? No redirect entries added, no slugs changed, so on. And yes, in production, even https://developer.mozilla.org/ko/docs/Web/JavaScript redirects me but not while running in local.

**Comment by peterbe** [comment]
> Uh, so it looks like Korean wasn't affected file-wise? No redirect entries added, no slugs changed, so on. And yes, in production, even https://developer.mozilla.org/ko/docs/Web/JavaScript redirects me but not while running in local.

Oh no! That's not good. 
What's also not good is that that 301 redirect will be cached by your browser so even if we can fix our deployment, *your* browser will unfortunately remember the old redirect.

**Comment by escattone** [comment]
Thank you @hochan222 and @alattalatta for reporting (and commenting) on this!

@alattalatta You were right on. It was due to the `yarn tool sync-translated-content` not taking into account the Markdown files. We've temporarily commented-out that call:

https://github.com/mdn/yari/blob/6fdcf037a6be037593e6b9a5868fba527c891180/.github/workflows/prod-build.yml#L174

until https://github.com/mdn/yari/issues/4297 is resolved.

The Javascript docs should be back to normal now (i.e., they shouldn't redirect to an "orphaned" URL), but you'll most likely have to clear your browser's cache of 301 redirects (e.g., in Firefox you'd go to `preferences --> privacy & security` and clear a day or two of your history).

**Comment by escattone** [comment]
@wbamberg FYI. Due to a bug in our `sync-translated-content` tool -- it doesn't yet take into account markdown files -- when the JS docs were converted to markdown, the JS doc URLs started 301 redirecting to new "orphaned" URLs (e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript started redirecting to https://developer.mozilla.org/en-US/docs/orphaned/Web/JavaScript). We temporarily fixed that by commenting-out our call to `yarn tool sync-translated-content` in our stage and prod builds. All of the JS docs should be back to normal, although users may have to clear any 301 redirects (from the last 1-2 days) from their browsers. Next week, we'll resolve it permanently by resolving https://github.com/mdn/yari/issues/4297.
