### ISSUE TITLE
Issue with "env()": compatibility description of "env()" on safari is ambiguous

### ISSUE THREAD

**Issue by siaikin** [mdn/yari#4332]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/env()

#### What information was incorrect, unhelpful, or incomplete?
Description of "env()" compatibility table on safari
![image](https://user-images.githubusercontent.com/24749324/127017935-984d846f-20cd-44c9-847a-a8fb31426c6d.png)

#### Specific section or headline?
Browser compatibility

#### What did you expect to see?
The description in [caniuse](https://caniuse.com/css-env-function) is like this, safari 11 and safari on IOS 11.2 supported as constant() instead of env(). and the newer version supports env().

But the description of the MDN page is,
 safari removed in version 11.1 and later(Alternate name: constant),
 safari on IOS removed in version 11.3 and later(Alternate name: constant).
It misled me to think that env() has been removed in 11.1+ and 11.3+.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/env()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/env()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/env()/index.html
* Last commit: https://github.com/mdn/content/commit/82749a5a907b6acceadfb7650326c2886cd2de58
* Document last modified: 2021-06-23T13:01:01.000Z

</details>

**Comment by peterbe** [comment]
caniuse displays it as:
<img width="192" alt="Screen Shot 2021-07-27 at 9 40 03 AM" src="https://user-images.githubusercontent.com/26739/127163931-26125cb8-afb2-40dd-8698-8bd465eea7e4.png">

And BCD displays it as just "Alternate name: constant".

And the point of this issue is that it's ambiguous. I would argue that it's simply less user-friendly :)
But I see the point. 
What's really going on is that; prior to 11.3 the function was called `constant()` but since 11.3 it's been renamed to `env()`. 

@vinyldarkscratch Can we simply put more a verbose and human readable note in there to resolve this confusion? Or, do you have other suggestions pertaining to the rendering?

**Comment by vinyldarkscratch** [comment]
It wouldn't really make much sense to add a note to BCD, since the data's structure covers the story, and other than an alternative name, it isn't something like non-spec behavior.  (Plus, if we added a note ourselves, then we should add one to all features with an alt. name, which just doesn't seem right when we already have the machine-readable version.)

I haven't given much thought to what we could do to update the wording, but one thought I have is perhaps we should swap the position of alt. name + prefix data and the support status?   (In other words, the row would read like "Alternative name: constant; Removed in 11.3 and later")

**Comment by queengooborg** [comment]
@schalkneethling This issue was affected by the idle-autoclose problem, can we reopen?

**Comment by caugner** [comment]
This issue seems to have been resolved with redesign or follow-up work on the BCD tables:

<img width="781" alt="image" src="https://github.com/mdn/yari/assets/495429/ea1dbbec-0593-44ad-84b5-496feea5c5ce">

(Thank you @mirunacurtean.)
