### ISSUE TITLE
Fuzzy search results aren't displayed in popularity order

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4346]
Go to the search widget and paste in `/foreach`. That should match every document that has the word `foreach` in the URI. 

We know from Elasticsearch that [searching for `foreach`](https://developer.mozilla.org/en-US/search?q=foreach&debug)
displays them in roughly this order:

1. `Array.prototype.forEach()`
2. `Map.prototype.forEach()`
3. `Set.prototype.forEach()`
4. `TypedArray.prototype.forEach()`
5. etc.

they all contain the word `foreach` in the title so all you have left to rank is the popularity. But it's clearly not working:

<img width="422" alt="Screen Shot 2021-07-28 at 10 07 41 AM" src="https://user-images.githubusercontent.com/26739/127337300-0928a92c-29d9-48f4-b11c-11aba96b68a0.png">

**Comment by peterbe** [comment]
This is kinda the explanation. When passed in throug the `import { match } from "fuzzyjs";` function from [`fuzzyjs`](https://www.npmjs.com/package/fuzzyjs) module, it produces those `score` values that are negative. 

I printed them out to try to understand how it filters things:
<img width="777" alt="Screen Shot 2021-07-28 at 10 22 57 AM" src="https://user-images.githubusercontent.com/26739/127339256-9fc62a05-32cc-463c-a90d-27d53b73e5d3.png">

Why does `/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach` get a score of -32?!
It has to do with the fact that it's long. 

I also see lots of new options in the latest version of https://www.npmjs.com/package/fuzzyjs but I don't think we're using that version.

**Comment by peterbe** [comment]
If you remove the filtering my `score > 0` this happens:
<img width="393" alt="Screen Shot 2021-07-28 at 10 32 46 AM" src="https://user-images.githubusercontent.com/26739/127341005-8c0d3ae7-6b83-4312-b6bf-d566f616761a.png">

**Comment by tannerdolby** [comment]
> Why does /en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach get a score of -32?! It has to do with the fact that it's long.

Hmm that is quite odd that the `score` would be negative. But it seems that from the console log output you provided that indeed, the longer the search result the more negative its score is. 

And when you remove the filtering score so that they must be > 0 we definitely get some search results that don't make much sense. Now that I've read the conversation in [#28](https://github.com/ajitid/fzf-for-js/issues/28) within `fzf-for-js`, I better understand why we would want a boolean `sort` property so like mentioned in the corresponding PR, we can better control how the sorting happens to get

```
Output: lisp, kotlin, elixir
```

and with the `sorted` boolean set to `false` we would have the natural sorting that appears in the `list` array option:
```
Output: kotlin, elixir, lisp
```
