### ISSUE TITLE
Doc page URL rewriting fails, adds extraneous /docs into path

### ISSUE THREAD

**Issue by tshinnic** [mdn/yari#4435]
Starting from StackOverflow answer [How to get character array from a string?](https://stackoverflow.com/a/34717402/471335) there is a link to `Array.from` using URL
>    https://developer.mozilla.org/Web/JavaScript/Reference/Global_Objects/Array/from

Clicking that rewrites to URL 
>    https://developer.mozilla.org/en-US/docs/Web/docs/JavaScript/Reference/Global_Objects/Array/from

The correct page is at URL 
>    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

The second extra "/docs" needs to not be added while rewriting URLs.

**Comment by escattone** [comment]
@tshinnic I think this is due to a flaw in our code here:

https://github.com/mdn/yari/blob/79a3cb92abfcbb557351ecdcd5aa9c4a191f3424/libs/fundamental-redirects/index.js#L1218

where the initial `/Web/` is interpreted by the `localeRedirect` function as a locale due to our too loose locale regular expression. We'll fix this, thanks for reporting!
