### ISSUE TITLE
UI updates for market research v3

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4460]
- [x] Reduce survey to a single page
- [x] Add show more link to deep dive article content
- [x] Replace author name with Twitter handle and link
- [x] Replace author title with the date and reading time
- [x] Change copy of CTA to "Take our 1 minute survey"
- [x] Change level 2 heading style as shown in Figma https://www.figma.com/file/y5mZ5Nt7AMSEppuGOfLvnB/MDN-Plus-Experiments?node-id=62%3A672

**Comment by dalexsy** [comment]
I also updated the scale for the body fonts and headers to reduce the space it was taking: https://www.figma.com/file/7lbOm57iOjSVIGORzXqrlW/MDN-Articles?node-id=276%3A3152

I know the actual headers are different than the ones in the file, but for simplicity's sake I'm just going to call them what's on the scale. H2 and below are now Inter instead of Metropolis. The correct font variables should be used in the Experiments file, but it's super possible I've missed some.

**Comment by schalkneethling** [comment]
@mirunacurtean Would a list like this be useful for you when testing? https://github.com/mdn/yari/issues/4460#issue-968298564
