### ISSUE TITLE
Create a github action to move issues

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#4497]
Issues that are raised on mdn/content aren't necessarily content related, some of them pertain to platform (here), examples or bcd.

A github action should be run every evening or week to automatically move issues with certain labels to the correct repositories

**Comment by tannerdolby** [comment]
> A github action should be run every evening or week to automatically move issues with certain labels to the correct repositories

+1 to this! I see so many issues that start off in `mdn/content` and end up being more Yari related than content. Thus having to be manually transferred from `mdn/content` to `mdn/yari`. Creating an action to pluck issues from other `mdn/*` repos and transfer them to the correct project based on their assigned labels sounds excellent.

**Comment by schalkneethling** [comment]
@Rumyra I wonder if this is also one we should move to the content team repo?

**Comment by Rumyra** [comment]
Same as before - this should be part of the issue triage process (we may decide actually it's not a great idea) but should have engineering support. However I am happy to include it in our project board.

**Comment by bsmth** [comment]
Hi all, it looks like the occurrences of issues landing on the wrong repo has significantly reduced in the last few months. Therefore, we are going to make minor improvements to the [GitHub issue templates](https://github.com/mdn/content/tree/main/.github/ISSUE_TEMPLATE) to make sure readers are opening an issue in the correct place instead of this automation for moving issues between repositories. We're going to continue moving them manually when this happens as it's so infrequent.

Thanks a lot :)
