### ISSUE TITLE
Sidebar text can overlap content

### ISSUE THREAD

**Issue by ghost** [mdn/yari#4635]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
Methods on the left are overlapping with the content in the middle of the page. It makes it difficult to read through this page. 

#### What did you expect to see?
I expected to see a clear separation between the main content and the menu on the left. 

#### Did you test this? If so, how?
I tried to alter the zoom percentage but it didn't make a difference. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md
* Last commit: https://github.com/mdn/content/commit/260094b613de640ff7eff377ffb0a0ef072016eb
* Document last modified: 2021-08-16T05:07:13.000Z

</details>

**Comment by KartikSoneji** [comment]
> ![image](https://user-images.githubusercontent.com/2392803/132166775-dbe36804-918b-4f62-966d-77ac014613c6.png)

Firefox seems to have a strange line-wrapping algorithm, where it breaks a word early and fills the next line.
In fact, there should be no line-wrapping according to the CSS:
https://github.com/mdn/yari/blob/9c98e2cd5bb699893d017bc2c4eb06c5416b55fc/client/src/document/organisms/sidebar/index.scss#L42

Most of the longer titles in the sidebar can be naturally broken on the dot (`.`), so it might be worth inserting `<wbr>` tags instead of relying on different browser's line-wrapping algorithms.
They would have to be inserted during the server-side rendering of the markup ([here](https://github.com/mdn/yari/blob/e4b305093bb2daba8916e057ecbc2513e610cd46/build/document-extractor.js#L23)).
Something like:
```js
Array.from($("code"))
  .map(e => $(e))
  .forEach(e => e.html(e.html().replace(/\./g, "<wbr>.")))
```

Before:
![image](https://user-images.githubusercontent.com/25801283/135431132-c7ea2f9c-fdd6-4add-b532-cb7763b36659.png)

After:
![image](https://user-images.githubusercontent.com/25801283/135431045-c5e1eaee-e3c2-4eb1-a04c-71ae03c91db1.png)

**Comment by schalkneethling** [comment]
@teoli2003 Can you have a look and see if this is still a problem with the new design? Thanks!

**Comment by teoli2003** [comment]
So the overlapping is not happening anymore (but I think it was before the redesign).
The comment about MDN not breaking at the dot, but before is still valid. I don't know if you wanted to change this with the redesign or not. Anyway, the original report (left sidebar overlapping text) is fixed.

![Capture d’écran 2022-03-03 à 12 34 16](https://user-images.githubusercontent.com/1466293/156557117-0cc31141-98e1-402c-b1c7-d37c70c0e788.png)

**Comment by schalkneethling** [comment]
> So the overlapping is not happening anymore (but I think it was before the redesign). The comment about MDN not breaking at the dot, but before is still valid. I don't know if you wanted to change this with the redesign or not. Anyway, the original report (left sidebar overlapping text) is fixed.

Thank you for getting back to me @teoli2003. There is a PR to address the new issue you mentioned. I will close this one as the specific issue mentioned here is no resolved.
