### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by GSMFURQAN** [mdn/yari#4731]
Hey there,
       The below screen shot describes the box shadow attribute. Here in the Vertical offset POSITIVE value creates shadow at the BOTTOM and NEGATIVE creates at the TOP. As, vertical line refers to Y-axis shouldn't the positive value create top shadow and negative value create bottom shadow! I mean it's not wrong. But, it would be easier to remember while comparing offset values with X and Y-axis...
              
![image](https://user-images.githubusercontent.com/52992635/135133183-2a3f56ae-3eb4-4bda-acba-7acb5e28a324.png)

**Comment by KartikSoneji** [comment]
- In computer graphics, the convention is to have the origin (0, 0) at the top left of the screen, with x increasing towards the right and y increasing towards the bottom:
   ![Cartesian coordinate system starting at top left](https://user-images.githubusercontent.com/25801283/135412561-c1329407-f2da-4ed4-8e62-dbf363f41cad.png)
   The reason for this convention is mostly historical:
   - https://learn365project.com/2015/08/01/why-do-computer-coordinates-start-from-the-upper-left-corner/
   - https://gamedev.stackexchange.com/q/83570
   - https://softwareengineering.stackexchange.com/q/252386

- Most other CSS properties follow this convention of y increasing towards the bottom.

- This is part of the CSS3 specification maintained by W3: https://www.w3.org/TR/css-backgrounds-3/#shadow-offset-y  
   MDN is just a reference. If you want to suggest changes to the spec then you can do so here ([w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/blob/main/css-backgrounds-3/Overview.bs)).  
   Note that even if you do submit this suggestion, it almost certainly will be rejected because in addition to the aformentioned reasons, it would break backwards compatibility.

**Comment by wbamberg** [comment]
Closed per @KartikSoneji 's excellent response at ^
