### ISSUE TITLE
"bug" macro only one used in non-archived content that relies on the network

### ISSUE THREAD

**Issue by escattone** [mdn/yari#480]
### Summary
The `bug` macro is the only macro used within non-archived content that [relies on the network for its resolution](https://github.com/mdn/kumascript/blob/1f4b93faf68095f0b69b2d3d0e9e487793bdc18e/macros/bug.ejs#L28). Let's try to find a way to resolve that macro without a network call.

**Comment by peterbe** [comment]
There are 1,721 of these macro calls in the not-to-be-archived content. Of which is 236 are en-US. So little hope to clean it all up in time. 

[Here's a list of the 100 most popular pages that use the `bug` macro](https://gist.github.com/peterbe/60236c0e2313de5350f49623429a026b)

What I think we should do is NOT server-side render the `<a>` tag to Bugzilla with details such as resolution. It's a terrible idea anyway. It'd be much better to either not do it or to change it into an ad-hoc web component with client-side resolution. Because, as it stands today, if it extracts the summary and resolution from `https://bugzilla.mozilla.org/rest/bug/` today, when you edit the Wiki page, it'll solidify that forever until the next time someone triggers a re-render of that page. And that can be weeks or months. 

I think we need to escalate this out and away from yari and deal with it kuma.

**Comment by peterbe** [comment]
@escattone How about, next time you copy the macros from mdn/kumascript  into the `kumascript` workspace, you can close this one.

**Comment by peterbe** [comment]
@escattone Can we close this now?
