### ISSUE TITLE
Improve Subresource Integrity

### ISSUE THREAD

**Issue by pjenvey** [mdn/yari#4823]
Per the [Mozilla Observatory](https://observatory.mozilla.org/analyze/developer.mozilla.org), MDN fails (-5 score) the [Subresource Integrity](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity) check:

```
Subresource Integrity (SRI) not implemented, but all external scripts are loaded over HTTPS
```

This can be implemented by adding integrity hashes to `<script>` tags loading content from third parties.

An alternative to implementing SRI fully and producing a "neutral" (0 score) for this check is to have "all scripts come from secure origins (self)" -- that is loading all scripts from developer.mozilla.org (or just mozilla.org).

**Comment by caugner** [comment]
Meanwhile, we score A+ with 100/100, and have no penalty for not implementing Subresource Integrity, because all scripts are loaded from a similar origin.

![Image](https://github.com/mdn/yari/assets/495429/0d945808-f067-4eec-9a02-cab791cc023f)

![Image](https://github.com/mdn/yari/assets/495429/11d78e14-fe94-4d41-8527-c3895ff6306f)

So I'm closing this as resolved.
