### ISSUE TITLE
Remove TemplateLink macro

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#4848]
This wasn't particularly useful and has been removed from en-US source in https://github.com/mdn/content/issues/9914

Should it also be removed in Yari?

I have taken no action on translated content.

**Comment by escattone** [comment]
@hamishwillee Yes, we can remove the `TemplateLink` macro as soon as it is no longer used within the translated-content. I see that there are still about 43 translated documents that use it.

**Comment by schalkneethling** [comment]
There still are 38 files that use this macro extensively. Do we have a way to mark a macro as deprecated with a date when it will be removed? I am thinking we need it if we do not already have it.

**Comment by hamishwillee** [comment]
> There still are 38 files that use this macro extensively. 

Sorry, I thought I'd removed all of them - at least in English content. 

> Do we have a way to mark a macro as deprecated with a date when it will be removed? I am thinking we need it if we do not already have it.

@escattone That would be a question for you. I would assume not. I suspect that the right way to do this is co-ordinate a project with content team.

**Comment by schalkneethling** [comment]
> > There still are 38 files that use this macro extensively.
> 
> Sorry, I thought I'd removed all of them - at least in English content.
> 
> > Do we have a way to mark a macro as deprecated with a date when it will be removed? I am thinking we need it if we do not already have it.
> 
> I would assume not. I suspect that the right way to do this is co-ordinate a project with content team. But it is complicated if these cases are in translations, since no one owns those. I don't even know where the translations live.
> 
> @escattone That would be a question for you.

Hey @hamishwillee, @escattone is no longer at Mozilla :( @Rumyra, @ddbeck I am also curious which macros we can remove, render out etc. We should have a chat about this

**Comment by Rumyra** [comment]
Yes we should have a chat about it - I can discuss with translated-content with what we decide 👍

**Comment by hamishwillee** [comment]
You might want to talk to @wbamberg about what the previous plan for removal of macros was. I'm working on the Page macro but I think there was a list somewhere of the first macros to be removed. Some can't be removed of course unless we have a different approach for sidebars etc. Would like to be kept in the loop please.

**Comment by wbamberg** [comment]
> > There still are 38 files that use this macro extensively.
> 
> Sorry, I thought I'd removed all of them - at least in English content.

I didn't see any in mdn/content. I do see 385 in translated-content, and as Hamish says, that's a big problem with actually removing macros. Florian and I had the same problem back when we were trying to remove macros. For example all the old Compat* macros, like for example  CompatGeckoDesktop, which appears 0 times in mdn/content (and has not appeared in en-US for about 4 years) but appears 3985 times in translated-content. There are about 10 just of these.

> You might want to talk to @wbamberg about what the previous plan for removal of macros was. 

I wrote a thing about this about a hundred years ago, most of which seems to still apply: https://docs.google.com/document/d/1G5KwoJNi8mLmbzcWo-eawH0xw4spVvHGY4Wc4ZEuMYg/edit.

I think at the time I wrote that though I thought moving to a new platform meant we would need to deal with KS, but I', no longer so sure about that. For one thing, we are on a new platform now. So I guess at the moment I think we should focus more on removing macros where that can deliver other value than just "fewer macros". For instance I think we should start generating "experimental" and "deprecated" banners from BCD, and as part of that we should remove the macros. And I think we should remove `page` (1) because it's a content antipattern IMO and (2) because it's one of the two macros that makes KS a lot more complicated than it needs to be (although there's no actual value in that unless we also go ahead with the KS refactoring that it enables).

I think if time/labour were unlimited a project to just remove macros would be worth doing, but they're not.

**Comment by schalkneethling** [comment]
> * start generating "experimental" and "deprecated" banners from BCD, and as part of that we should remove the macros.

@wbamberg If you want to chat about getting on the roadmap for MDN Web Docs engineering, please let me know.

**Comment by wbamberg** [comment]
Thanks @schalkneethling ! We have https://github.com/openwebdocs/project/issues/81 for it, and I hope we might be able to get started on it in Q2?

**Comment by schalkneethling** [comment]
> Thanks @schalkneethling ! We have [openwebdocs/project#81](https://github.com/openwebdocs/project/issues/81) for it, and I hope we might be able to get started on it in Q2?

Sounds doable to me.

**Comment by caugner** [comment]
As of today, the `TemplateLink` macro is deprecated, but still used in es/ru/pt-br locales. There is an ongoing and very active effort to remove deprecated macros from translated-content, yet it's not necessary to track the removal of individual deprecated macros in a yari issue.
