### ISSUE TITLE
Issue with "Operator precedence": Missing CSS border in some columns

### ISSUE THREAD

**Issue by brunexgeek** [mdn/yari#4894]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

This is about the table in the "Table" section. Some lines (except the first) in the second column (_Operator type_) do not have a left border due to a `border-left: 0;` CSS entry. This happens when the previous column (_Precedence_) uses `rowspan`. This problem does not occur in the last column (_Individual operators_).

The complete CSS rule for the columns missing the left border (from `https://developer.mozilla.org/static/css/main.a43ed10c.chunk.css`):
```
table td:first-child, table th:first-child {
    border-left: 0;
    min-width: 150px;
}
```

#### Specific section or headline?

Table

#### What did you expect to see?

Every row in the second column must have a left border.

#### Did you test this? If so, how?

Page rendered with Firefox 94.0 (64-bit) under GNU/Linux.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/80591d2eda357ab33580af0eeeec695e398160d4
* Document last modified: 2021-08-15T13:24:35.000Z

</details>

**Comment by tannerdolby** [comment]
Good catch @brunexgeek! You were spot on, the CSS causing issues is:

```css
table td:first-child, table th:first-child {
    border-left: 0;
    min-width: 150px;
}
```

and specifically its the `table td:first-child` that is overriding the `border-left` declaration to be `border-left: 0`. This is because each new table row `<tr>` has a `<td>` element as the first nested element e.g. "first-child" so thats why were seeing each row start off with `<td>` elements that are missing left borders. 

If we remove that first selector combination and keep `table th:first-child` the table borders will appear for each table row and `<td>` cell on the left like we expect them to without negatively affecting any other part of the BCD table.

This `.scss` source for the partial file `_tables.scss` is located in [mdn/minimalist](https://github.com/mdn/mdn-minimalist) but the most up-to-date source for minimalist doesn't show the `border-left` declaration, which makes me think by the time Yari runs a new build (within the next <24hrs most likely) the style changes will be picked up from minimalist and this issue should be resolved.

**Comment by tannerdolby** [comment]
And seeing this [comment](https://github.com/mdn/mdn-minimalist/issues/833#issuecomment-963350115) by @schalkneethling leads me to believe that whenever the most recent release of minimalist is out of the dependency queue it will be ready for Yari to use and the issue we see of `<td>` elements within `<tr>`'s not having a visible border-left style will be fixed.

**Comment by tannerdolby** [comment]
Now that the changes from `minimalist` are being utilized here in Yari, all of the cells in the BCD tables have the appropriate borders and look good!

<img width="921" alt="Screen Shot 2021-11-11 at 8 33 01 PM" src="https://user-images.githubusercontent.com/48612525/141410076-8701cb6a-0083-41c1-9196-d7c874332dc1.png">


I reckon this is ready to be closed whenever @schalkneethling
