### ISSUE TITLE
PR review companion seems flaky?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4972]
[On this build](https://github.com/mdn/content/runs/4273123315?check_suite_focus=true) the PR review companion keep failing with the following stack:

```bash
Run actions/github-script@v5
  with:
    script: var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
     owner: context.repo.owner,
     repo: context.repo.repo,
     run_id: 1480759121,
  });
  var matchArtifacts = artifacts.data.artifacts.filter((artifact) => {
    return artifact.name == "build"
  });
  if (matchArtifacts.length === 0) {
    console.warn(
      'No artifacts to download probably just means nothing ' +
      'was built in the "PR test" workflow. That\'s OK. ' +
      'This is actually not a genuine CI error.'
    );
    throw new Error(
      'No matched build artifacts. ' +
      'Perhaps nothing built in the "PR test" workflow'
    );
  }
  var matchArtifact = matchArtifacts[0];
  var download = await github.rest.actions.downloadArtifact({
      owner: context.repo.owner,
      repo: context.repo.repo,
      artifact_id: matchArtifact.id,
      archive_format: 'zip',
  });
  var fs = require('fs');
  fs.writeFileSync('/home/runner/work/content/content/build.zip', Buffer.from(download.data));
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
(node:1562) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
No artifacts to download probably just means nothing was built in the "PR test" workflow. That's OK. This is actually not a genuine CI error.
Error: No matched build artifacts. Perhaps nothing built in the "PR test" workflow
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:17:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:20)
Error: Unhandled error: Error: No matched build artifacts. Perhaps nothing built in the "PR test" workflow
```

We recently changes `github.actions.listWorkflowRunArtifacts` to `github.rest.actions.listWorkflowRunArtifacts` because of the breaking change in the underlying GitHub action. The same change was made by @SphinxKnight on translated-content. It looks like the error is not related to the change, but based on the fact that there was no artefacts. However, there is this `console.warn` in the code:

```bash
console.warn(
      'No artifacts to download probably just means nothing ' +
      'was built in the "PR test" workflow. That\'s OK. ' +
      'This is actually not a genuine CI error.'
    );
```

There is also [this run](https://github.com/mdn/content/runs/4277213931?check_suite_focus=true) that did _not_ error. We will need to have a look at what the actual cause is and resolve the issue.

**Comment by wbamberg** [comment]
FWIW I'm also not seeing built pages for https://github.com/mdn/content/pull/10646 (the first time it worked, but after review the author made some changes, and those I am not seeing).

**Comment by schalkneethling** [comment]
I have not kept an eye on this one. @wbamberg, @SphinxKnight, or @ddbeck, is this still behaving inconsistently?

**Comment by SphinxKnight** [comment]
From https://github.com/mdn/translated-content/actions/workflows/pr-review-companion.yml?query=is%3Afailure I can see https://github.com/mdn/translated-content/actions/runs/1831126327  / https://github.com/mdn/translated-content/runs/5171601783?check_suite_focus=true and https://github.com/mdn/translated-content/runs/5176772124?check_suite_focus=true "recently".
Most of the time it goes without issues though.

I'll be back later with more time to have a deeper look at those failures.

**Comment by ddbeck** [comment]
Yes, I _think_ the PR review companion workflow is prone to failure. But because of the way the PR companion is wired up, it's not very obvious when it has failed, why it has failed, or what PR it failed _for_.

For reasons unknown to me, it's triggered by [the completion of the `PR Test` workflow completion](https://github.com/mdn/content/blob/main/.github/workflows/pr-review-companion.yml), instead of being a second ([dependent](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#creating-dependent-jobs)) job in the same workflow as the `PR Test` job. This creates a few problems:

- Companion reviews are invisible. Since it's triggered by another workflow, the companion doesn't show up in the "Checks" tab for any particular PR. [Here's an example](https://github.com/mdn/content/pull/13062/checks), where the companion ran, but you have no indication of such in the "Checks" tab; you only get a comment on the PR.
- Failures are difficult to investigate. There's no way to see, in [the list of Actions runs](https://github.com/mdn/content/actions/workflows/pr-review-companion.yml), which PR a companion run is associated with (the `#` is the workflow run count, not a PR number). Sometimes I have received emails about companion failures long enough after opening a PR that I have no idea which PR or commit caused it or why.
- Failures are difficult to recover from. For example, if the PR companion gets stuck, you can't re-run it from the "Checks" tab. I think the only way to re-run the PR companion is to push a new commit, though I've never investigated this closely.

I think the first step would be to combine the [PR Test](https://github.com/mdn/content/blob/main/.github/workflows/pr-test.yml) and [PR review companion](https://github.com/mdn/content/blob/main/.github/workflows/pr-review-companion.yml) workflows, with two dependent jobs. That will probably give us some better information on why the companion is misbehaving.

(There's also some other suspect stuff in those workflows, but I've been reluctant to mess with them since I'd have no way of knowing if or why they'd fail.)

**Comment by awxiaoxian2020** [comment]
I still have this problem. See https://github.com/mdn/translated-content/actions/runs/2896760814

**Comment by caugner** [comment]
**To fix case 1**, we could run the "PR review companion" workflow conditionally only if the "PR Test" workflow run concluded with "success":

> `if: ${{ github.event.workflow_run.conclusion == 'success' }}`
> _Source_: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

🤔 However, it should already do that, see: https://github.com/mdn/content/blame/d987faaf1b65fbc11323327d82ce13a004cb96d4/.github/workflows/pr-review-companion.yml#L18-L20

**To fix case 2**, we could modify the "PR Test" workflow to ...

- conditionally run only if anything inside `files/` was changed, and/or
- always upload an artifact (and optionally [suppress the warning](https://github.com/actions/upload-artifact#customization-if-no-files-are-found)).

**Comment by caugner** [comment]
Decreased priority, because it's just annoying, not _really_ a problem that the workflow fails.

**Comment by bsmth** [comment]
I think it's safe to close this for now as there's been multiple refactoring efforts completed on these workflows; a significant one being the following that's landed in content and translated content:

- [x] https://github.com/mdn/content/pull/30064
- [x] https://github.com/mdn/translated-content/pull/16891

A few things that add stability:

- Replace `actions/github-script@v5` that handled artifacts with hand-written logic with `actions/download-artifact@v3` 
- Make PR companion dependent on Tests: https://github.com/mdn/content/blob/a320ca3ba41cde9b385f249a1519194f20c35d5c/.github/workflows/pr-test.yml#L148-L152

And there are a number of other small but important fixes:

- [x] https://github.com/mdn/content/pull/30286
- [x] https://github.com/mdn/content/pull/22898

__Related issues:__

- https://github.com/mdn/content/issues/28579

**Comment by caugner** [comment]
Closing as suggested by Brian in https://github.com/mdn/yari/issues/4972#issuecomment-1935586970.
