### ISSUE TITLE
In-line images not displaying correctly

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#5029]
## What page(s) did you find the problem on?

Various tools pages e.g.[Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) use images of icons within sentences but by default, these images are displayed as block elements and therefore on separate lines.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/7352080/144285427-45aa2529-230f-48ad-81c6-d12271813b8d.png">

These images need to be updated to include the `style="display: inline"` directive to display them in-line. They might also look better if resized e.g. `height="20" width="20"`

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/7352080/144285942-255cbf6f-387f-445b-9664-3df21ecc84da.png">

**Comment by Rumyra** [comment]
A couple of things:

- I think we should avoid adding inline styles within images - we are undergoing a redesign so this issue will become obsolete in the very near future and keeping everything within markdown until then seems a good course of action
- @schalkneethling has moved this issue over and will fix it from the platform side of things, rather than from within page content 👍
