### ISSUE TITLE
BCD table doesn't show children if parent has no BCD data itself

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#5041]
With reference to:

- [Web extensions privacy API not showing compatibility data mdn/content#10969](https://github.com/mdn/content/issues/10969)
- [webextensions.api.privacy - Compatibility data is not available mdn/browser-compat-data#13895](https://github.com/mdn/browser-compat-data/issues/13895)

Although the compatibility data for the Privacy API is formed in a similar way to other APIs, such as that for Permissions, it is not rendering (although the compatibility data for its function is).

**Comment by danielhjacobs** [comment]
This is entirely possible @caugner, but I'm not sure it's what's always wanted. It leads to something that didn't used to show; depth level 3. See the screenshots:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels#browser_compatibility

Before:
![Screenshot from 2022-09-15 14-15-05](https://user-images.githubusercontent.com/29206584/190479958-4c012324-8029-4488-a612-b19b498d59ce.png)

After:
![Screenshot from 2022-09-15 14-14-50](https://user-images.githubusercontent.com/29206584/190479795-a0d899fa-8471-41dc-95d0-05029a57ed73.png)

After of http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools#browser_compatibility:
![Screenshot from 2022-09-15 14-16-06](https://user-images.githubusercontent.com/29206584/190479800-15743b63-f2e3-4c04-bb55-226eb2bbfd48.png)

**Comment by caugner** [comment]
@danielhjacobs Sorry, I was a bit too vague in my specification.

I would like the BCD table for [devtools.panels](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/panels#browser_compatibility) to stay exactly as it is (4 entries), and only for [devtools](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools#browser_compatibility) to show the grandchildren (`devtools.panels.create/elements/onThemeChanged/themeName` etc), but **only because** neither the parent (`devtools`) nor its immediate children (`devtools.panels` etc) have any data.

If we could determine at what depth we have the first data, we could then show that depth + 1. Would that work?

**Comment by caugner** [comment]
@queengooborg What are your thoughts on this issue and my proposed solution?

(Maybe the BCD data itself would need to be adjusted, e.g. by adding intermediate entries?)

**Comment by danielhjacobs** [comment]
> If we could determine at what depth we have the first data, we could then show that depth + 1. Would that work?

@caugner That can only work by doing a loop or extra recursion before the current recursion. Especially with devtools.panel, I can't find the first depth of data without looping through all the data beforehand.

Look at https://github.com/mdn/browser-compat-data/blob/c21f86ba62d6b9fd297fe27d8bd9e79f367e464c/webextensions/api/devtools.json#L242. "panels" has no compat data, and neither does "ElementsPanel". So the first depth at which I find data is the grandchild. However, a later child has data (https://github.com/mdn/browser-compat-data/blob/c21f86ba62d6b9fd297fe27d8bd9e79f367e464c/webextensions/api/devtools.json#L476)

**Comment by danielhjacobs** [comment]
PR adjusted.

**Comment by danielhjacobs** [comment]
PR #7167 does what https://github.com/mdn/yari/issues/5041#issuecomment-1248598636 describes. The question remains though on whether this change makes sense or changes should be made in BCD itself instead/as well.
