### ISSUE TITLE
Proposal: make it easier to search for DOM interface for HTML elements

### ISSUE THREAD

**Issue by Erutuon** [mdn/yari#5276]
I often search for HTML tag names trying to find the DOM interface corresponding to a HTML element. I usually have to do a search for the tag name, go to the page for the HTML element, find the `class="properties"` table near the top or bottom of the page, and click the `DOM interface` link at the bottom of the table. It would be nice if a search for the tag name would yield the DOM interface. It would cut out the intermediate steps.

For instance, when I type `textarea` into the search box, it only shows a link to the [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) element. It would be nice if it showed [`HTMLTextAreaElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement) too.

It would also be easier to find DOM interfaces if searching by an equivalent of the string after `HTML` in the name of the DOM interface yielded the DOM interface as a result. For instance, `tablerow` or `table row`  -> [`HTMLTableRowElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement).

I guess this might require setting up an additional type of index by crawling HTML element pages to find the `class="properties"` table and the table cell after the `DOM interface` table header, adding something to read the index, and deciding how to rank the results from this index. Or maybe there's another source for this information, because it's pretty basic. Perhaps the DOM interface could always be directly below the HTML tag in the results, to make it a bit clearer why it's there, when the name doesn't necessarily contain the search query.

Hopefully I'm not missing that there's already a way to do these things, or an existing issue on this topic. Searching "search engine" and "DOM interface" didn't turn up anything.

**Comment by schalkneethling** [comment]
@Rumyra there is definitely an engineering component to this but, could there also be a content aspect here? i.e. Perhaps there is an improved way we can expose these? Thought I would ask.

**Comment by Rumyra** [comment]
I think search is probably the key feature here. There's interlinking between both examples pages 👍

**Comment by Rumyra** [comment]
Ahh - thanks for the history @teoli2003 :)

**Comment by schalkneethling** [comment]
@Erutuon, I just searched `textarea` as you mentioned, and it shows both the `textarea` element and `HTMLTextAreaElement`, which you were after, I believe. Was this just luck, or has this issue been resolved? Let me know; thanks!

![Screenshot of search drop down showing both textarea and HTMLTextAreaElement](https://user-images.githubusercontent.com/10350960/170142909-b5c9a702-d8bf-41d7-9cd7-86f6988d75be.png)

**Comment by caugner** [comment]
We have intentionally kept the in-page search simple, so the results are ordered by popularity of the pages, and this explains why `HTMLTextAreaElement` shows up as the second item when searching for "textarea".

When searching for "input", `HTMLInputElement` is not included in the results, because there are several more popular pages:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/495429/197821792-8479972b-e0c8-4a51-9ef4-1f89149a1a85.png">

However, if you searched for "html input", it would be the second result:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/495429/197822092-19d11f79-fd22-4d0a-93cf-cb73fe2a4d5b.png">

One solution for this might be to introduce "priority search terms" in the pages' frontmatter, so both the `<textarea>` and the `HTMLTextAreaElement` pages could be directly assigned to "textarea" and would then appear first in in-place searches for that term.

**Comment by Rumyra** [comment]
> One solution for this might be to introduce "priority search terms" in the pages' frontmatter, so both the <textarea> and the HTMLTextAreaElement pages could be directly assigned to "textarea" and would then appear first in in-place searches for that term.

The only thing I would be cautious of here is authorship - it'd complicated to keep search terms up to date (it's similar to tags which we currently have and the consensus is we shouldn't). Possibly easier to expand more on this in person @caugner

**Comment by caugner** [comment]
We discussed this shortly in the team, and we would recommend to add an "e" to the HTML element name to get the `Element` interface:

![image](https://user-images.githubusercontent.com/495429/200316691-58d26974-dbdc-4d23-96bc-8168f0ee50b8.png)

Other than that, we have no plans on improving specific search queries.
