### ISSUE TITLE
New browser-compat table format is less helpful; please display browser-versions instead of checkmarks

### ISSUE THREAD

**Issue by MichaelAllenWarner** [mdn/yari#5353]
I already filed an issue in the `mdn/content` repo about this (mdn/yari#5366), but maybe this is the better place for it? I'll just repeat what I wrote there:

The browser-compatibility table now displays just a checkmark if any version of the browser has adopted the feature in question, and you have to click the checkmark to see _which_ version was the earliest to adopt it. To be frank, this makes the table useless—developers now need to click every checkmark to glean the information they're looking for.

Please go back to the old way of displaying the _earliest_ version to adopt the feature.

**Comment by loilo** [comment]
I second this. There is almost no scenario where I woud _not_ need additional version information because for virtually every project, there is a baseline of browser version support which you could previously just check by skimming over the compatibility table.

Looks great & clean, but is unfortunately less useful.

**Comment by Schweinepriester** [comment]
While I fully agree, #5366 has been moved and as such this one here (#5353) is kinda duplicate now.
I propose to keep #5366 as it got more traction already :)

**Comment by caugner** [comment]
Closing this in favor of #5366, thanks for the heads-up, @Schweinepriester. 👍
