### ISSUE TITLE
Issue with "BigInt": Browser compatibility table crashes on clicking `toLocaleString.options` for `Deno`

### ISSUE THREAD

**Issue by 80avin** [mdn/yari#5385]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?
None (crashes)

#### Specific section or headline?
Browser Compatibility

#### What did you expect to see?
On Clicking `toLocaleString.options` for `Deno`, the table shouldn't crash

#### Did you test this? If so, how?
Clicked on the cell corresponding to `toLocaleString.options` for `Deno` and the Browser Compatibility table crashed

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md
* Last commit: https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450
* Document last modified: 2022-02-18T09:53:31.000Z

</details>

**Comment by schalkneethling** [comment]
@fiji-flo What I have found here is that `item` is `undefined` here https://github.com/mdn/yari/blob/4136f02846b127b580630ff05f6081bc208ef0e0/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L314 because `support` is `undefined` here https://github.com/mdn/yari/blob/4136f02846b127b580630ff05f6081bc208ef0e0/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L311

**Comment by schalkneethling** [comment]
@80avin we landed a fix https://github.com/mdn/yari/pull/5386 - Please let us know if you still experience the issue.
