### ISSUE TITLE
First paragraph of notes and warnings is small

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5517]
For example: https://pr12930.content.dev.mdn.mozit.cloud/en-US/docs/Learn/JavaScript/Asynchronous/Promises#using_the_fetch_api

<img width="804" alt="Screen Shot 2022-03-07 at 3 44 16 PM" src="https://user-images.githubusercontent.com/432915/157137193-582bcda1-b487-473e-a0b8-a9bffa8e4f45.png">

I'm not sure why we are reducing the font size in notes and warnings at all (to my old eyes that text is pretty small) but I'm even less sure why we are only doing it for the first paragraph.

**Comment by sharonytlau** [comment]
Hi @e3dio, thanks for linking me to this issue!

Replying to your suggestion "The note text should probably be made larger to match the other text", I think either a regular or smaller font size for notes work for me. I believe the original intent of the author was to make it smaller than the body text. But considering the issue brought by @wbamberg, we should consider making the font a little larger.

I still want to bring up the point that we need to make all text inside a notecard have a consistent size. 
So, in the  `./client/src/ui/molecules/notecards/index.scss` stylesheet, we should consider adding more rules to target all kinds of text that may appear inside a notecard, including `ol li`, `p`, `code`, `a code`, etc. I think this issue found by @wbamberg is caused by the rule on `.notecard li` overridden by the rule on `.main-page-content ol li`. So, we should also make sure that the declarations are actually working (not overridden by other rules).

**Comment by wbamberg** [comment]
Thank you!
