### ISSUE TITLE
UI suggestion: Make header and breadcrumbs sticky

### ISSUE THREAD

**Issue by galich** [mdn/yari#5521]
# Summary

MDN header (with search button) and breadcrumbs (with language selector) can be scrolled away.

## Where did you spot the bug?

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

## What is the problem?

It is quite inconvenient to browse MDN page, then decide to find something else and not having search box anywhere on screen because the page was scrolled down.

## What did you expect to happen?

Search box must be one click away all the time.

### Browser

- [ ] Chrome: (what version?)
- [x] Firefox: 99
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: 10
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

## Screenshots

![image](https://user-images.githubusercontent.com/3718155/157168289-8c5dd979-254e-478a-a183-38d8e43973d3.png)

**Comment by e3dio** [comment]
My CSS fix https://github.com/mdn/yari/issues/5389 keeps the headers sticky on top for the search and nav (breadcrumbs). It also makes the header shorter so it takes less space. If the header is larger it's more of an issue. I think I prefer having search/nav available without needing to scroll to top, some may prefer more content space

**Comment by bacontime** [comment]
Funnily enough, I spent the time tracking down these feedback pages to ask that the header stickiness be removed on desktop for accessibility reasons. I'll just post a comment here instead of creating a new issue. 

@[galich](https://github.com/galich), you correctly point out the advantages of a sticky header, but there are some major downsides. Namely: 

1. It reduces the space available for content, which is especially problematic on horizontally oriented displays and when the page is zoomed in for eyesight reasons.
2. As currently implemented, it breaks the table of contents in the sidebar.  

### Example of problem number 2:

Take a look at the following screenshot. This was taken immediately after clicking the "Specifications" navigation link in the table of contents on the right. There are three problems here:
- The page has been scrolled to the wrong position. The navigation button must sometimes be clicked twice to properly scroll to the correct position (This behavior occurs inconsistently, but on both Windows and Mac OS.)
- The "Example" section is highlighted as the current position in navigation, despite no portion of that section being visible. 
- Despite not moving my cursor, it is now hovering over the "Browser Compatibility" link. (This wouldn't be such an issue if not for the need to double click the navigation.) 

![image](https://user-images.githubusercontent.com/42920487/164959414-f7fcd028-7845-4b84-a157-6fe27bc12296.png)

The first two problems are caused by the sticky header. The third is in some sense caused by the navigation bar not being sticky enough.

### Suggestions

My general feeling is that sticky headers are sensible design on mobile, because the screen is vertically large, there is no room for sidebars, and scrolling to the top of the page is difficult. But on desktop, a sticky header is poor design because there is less vertical space available and more horizontal space, because returning to the top of the page requires only a single keystroke, and because the always-visible url renders breadcrumbs largely redundant.

Ideally, what I would like to see is to:

- Keep the sticky header on mobile.
- Completely remove header stickiness on desktop. 
- On desktop, move the search bar from the header to one of the sidebars.
- Give the table of contents a more fixed position, instead of having it scroll but only a tiny amount.
