### ISSUE TITLE
Bug: Greyed out theme switch on Light mode

### ISSUE THREAD

**Issue by e3dio** [mdn/yari#5533]
# Summary

Greyed out theme switch on Light mode

## Where did you spot the bug?

Every page

## What did you expect to happen?

Colored switch on Light mode

## Screenshots

![image](https://user-images.githubusercontent.com/85405955/157261907-de9e8a70-6d7f-4776-bccc-d2d3f58ce635.png)

This PR broke the light switch ? https://github.com/mdn/yari/pull/5506

**Comment by e3dio** [comment]
The point I am making is this is different than it was yesterday and for the 1st week of your new design rollout. That PR changed the design of the site, where there was once a nice bright colorful icon is now grey bland and boring, I wanted to confirm you actually intended to make that change as I see no issue or commentary anywhere about it

**Comment by e3dio** [comment]
To me this is a design regression and a bug, I added CSS to fix this and get some color back in the upper right corner: https://github.com/mdn/yari/issues/5389

**Comment by caugner** [comment]
We're continuously improving the MDN experience, and this includes design aspects like the theme switch.

After the redesign, we noticed that our new theme switch does not follow the [general consensus](https://duckduckgo.com/?q=material+design+switch&iax=images&ia=images) of how the off state should look.

We addressed this by changing the off state's background color accordingly, so that users see the same pattern they're used to from other sites.

And this won't be the last adjustment we're making. For example, we will roll out new icons to make the theme switch even more self-explanatory:
![image](https://user-images.githubusercontent.com/495429/157324051-bf1d79f7-3608-46cd-ae4d-ea581eaeab6c.png)

Thank you for your understanding.
