### ISSUE TITLE
Issue with "Key Values": table of contents overlaps with page content

### ISSUE THREAD

**Issue by 0kku** [mdn/yari#5574]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

#### What information was incorrect, unhelpful, or incomplete?
Information itself was OK. The page layout is just completely broken. There's a lot of empty space on the left, whereas the page requires sideways scrolling to see the full tables, and the tables overlap with the table of contents. If it helps, I viewed it on a screen where the CSS pixel size of the window was 1368x800, and the problem seems to present itself when the screen CSS width is above 1200px. 

Screen recordings of the isssue:
<details>

![Scrolling down on the page](https://cdn.discordapp.com/attachments/726005873465360435/951573619769769984/msedge_4wXVtfO5BX.gif)

![Scrolling sideways on the page](https://cdn.discordapp.com/attachments/726005873465360435/951574587278241842/msedge_kgjBKpKZuz.gif)

</details>

#### Specific section or headline?
Every section.

#### What did you expect to see?
A correctly formatted page

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent/key/key_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/key/key_values/index.md
* Last commit: https://github.com/mdn/content/commit/88b57678d8c4cf07f02a2853788027dff0b2f18e
* Document last modified: 2022-02-15T08:06:18.000Z

</details>

**Comment by caugner** [comment]
Hi @0kku, thanks for taking the time to report this, and kudos for the screen recording! 👋 

As for the empty space on the left, I believe we are missing a sidebar (menu) there.
(@dipikabh Is the missing sidebar [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values) part of the issue you're currently investigating/working on?)

As for the overlap, we have addressed this in #5560 by wrapping the table in a scrollable div, but it's still not a perfect solution, because the scrollbar only appears at the bottom of the table. Implementing #5421 would allow users to collapse the sidebar if necessary.

**Comment by dipikabh** [comment]
> As for the empty space on the left, I believe we are missing a sidebar (menu) there.
> (@dipikabh Is the missing sidebar [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values) part of the issue you're currently investigating/working on?)

Yes, it is related but not the same issue I guess. But it is definitely the same macro that generates the sidebar - the macro call seems to be missing on this page.

**Comment by caugner** [comment]
The sidebar is also missing on the [KeyboardEvent: code values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values) article:

```console
$ grep --include='*.md' -irL 'ApiRef' files/en-us/web/api/keyboardevent        
files/en-us/web/api/keyboardevent/code/code_values/index.md
files/en-us/web/api/keyboardevent/key/key_values/index.md
```

Probably the reason for this is that the these two articles are "just" lists related to the `KeyboardEvent`, but they don't _directly_ document a part of the API (and are therefore not linked in [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) sidebar). 🤔 

Anyways, I will create a separate mdn/content issue for this, because adding a sidebar there doesn't fix the reported layout problem.

**Comment by caugner** [comment]
Actually, I will go ahead and close this issue, because the overlap is addressed, and collapsing the sidebar is tracked in #5421.
