### ISSUE TITLE
Flask icon for experimental features looks strange

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5588]
We use a flask icon to represent experimental features. In the redesign the sides of the flask are almost invisible, making it not at all obvious what it's supposed to be:

<img width="145" alt="Screen Shot 2022-03-11 at 7 36 19 PM" src="https://user-images.githubusercontent.com/432915/158002240-f7446f02-5f53-4cc9-83da-43906959afee.png">

<img width="150" alt="Screen Shot 2022-03-11 at 7 36 27 PM" src="https://user-images.githubusercontent.com/432915/158002241-07b836fe-b296-4e47-a965-c8e375a2b020.png">

(from https://developer.mozilla.org/en-US/docs/Web/API/Selection)

**Comment by caugner** [comment]
@wbamberg I don't know why, but I don't see those icons on https://developer.mozilla.org/en-US/docs/Web/API/Selection anymore. 😮 

Would you have other articles in mind that have those?

**Comment by caugner** [comment]
I found this issue in the main content here: https://developer.mozilla.org/en-US/docs/Web/API/Window#methods

**Comment by caugner** [comment]
And here's how the looked before ([source](https://web.archive.org/web/20220222220616/https://developer.mozilla.org/en-US/docs/Web/API/Window#methods)):

![image](https://user-images.githubusercontent.com/495429/158183387-04c21380-7a33-4bd3-b72a-cf3f1e85b0c9.png)

Since the redesign:

![image](https://user-images.githubusercontent.com/495429/158183546-c8c0aad4-eb73-47e4-82b9-eb1fe32c054e.png)

**Comment by danielhjacobs** [comment]
The pre-redesign icons were probably the dinocons: https://github.com/mdn/mdn-dinocons/blob/main/general/flask.svg

Now it's the icon asset: https://github.com/mdn/yari/blob/main/client/src/assets/icons/experimental.svg
