### ISSUE TITLE
add pt-BR strings to markdown/locations

### ISSUE THREAD

**Issue by victor0x16** [mdn/yari#5682]
I want to add translated versions of Notes, Warnings and Callouts, so we can use in the .md pages (pt-BR).

Following @SphinxKnight PRs #4251, other l10n-* languages already have done that like es, ko, et al.

See it here:
![warnings](https://user-images.githubusercontent.com/100092662/159142624-cf23bc04-c983-49d8-900c-b61cbc29e79c.jpeg)

Is it anything that I should know/do before doing a PR to add that ? Or I'm good to go.

**Comment by cw118** [comment]
@victor0x16 adding those translations is quite simple (just create a `pt-BR.json` file in the [markdown/localizations folder](https://github.com/mdn/yari/tree/main/markdown/localizations) and structure it the same way as the other locales) so I think you're good to go. 

I would consider [discussing with the pt-br community](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#brazilian_portuguese_pt-br) in order to use translations that everyone agrees with, or at least pinging the pt-br team for a review :)

**Comment by victor0x16** [comment]
> I would consider [discussing with the pt-br community](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#brazilian_portuguese_pt-br) in order to use translations that everyone agrees with, or at least pinging the pt-br team for a review :)

@cw118, Thanks for your helpful thoughts and I'll do it over the [discussing with the pt-br community](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#brazilian_portuguese_pt-br).

**Comment by caugner** [comment]
Fixed by https://github.com/mdn/yari/pull/6804.
