### ISSUE TITLE
Using relative URLs to refer to audio/video/font files

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5727]
In https://github.com/mdn/content/pull/14183 I want to include a live sample using an `<audio>` element. With, `<img>` elements I can download the source, keep it alongside `index.md`, and reference it using a relative path, like this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#alternative_text.

I don't seem to be able to do the same with audio files (and maybe video too, haven't tried these). I need to refer to them using an absolute URL, like https://pr14183.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLMediaElement/preservespitch#example . This doesn't seem ideal - it would be good to keep all the assets for a page together.

**Comment by caugner** [comment]
The magic for images (`img[src]`) is happening here:

https://github.com/mdn/yari/blob/68d8fa10437f62d1230964c9f09642c6bd7fa55c/build/index.js#L462-L463

https://github.com/mdn/yari/blob/68d8fa10437f62d1230964c9f09642c6bd7fa55c/build/check-images.js#L35-L39

The same approach should work for `audio[src]`, but it will be slightly trickier to extract fonts as well.

**Comment by caugner** [comment]
⚠️ Avoid authoring new PRs that modify `build/*` until https://github.com/mdn/yari/pull/6683 has landed (possibly today).

**Comment by hamishwillee** [comment]
> I think the buffer would be fairly straightforward to illustrate/shade within QGC similar to the exclusion shading. Given that QGC has access to the buffer distance param, hopefully no mavlink messages would be required.

Yes. Also font files like woff and woff2. Can we get these supported too @caugner ?

**Comment by caugner** [comment]
> Yes. Also font files like woff and woff2.

That will definitely be trickier, because you wouldn't be referencing those fonts in an HTML attribute, but rather inline in JavaScript or in a `<style>` tag. 🤔 

@hamishwillee Would those woff/woff2 files be used in multiple examples?

**Comment by hamishwillee** [comment]
@caugner Yes. For my case I'll be accessing them programmatically using [FontFace](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace) - that means it's a fetch under the hood, which is why I need this same-site.
But yes, also handy in styles via [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face).

> @hamishwillee Would those woff/woff2 files be used in multiple examples?

Yes. At least the FontFace and @font-face examples.

There are some alternatives that might be used. I want to be able to have them locally because then they are easier to manage, and I know that the font will be present when needed. You can't fetch these fonts from github because the aren't served with the right headers, but you could serve them from a CDN or whatever that allowed it. 
Personally I have been trying to serve from Google Fonts, but the fonts I am trying are not working for things like font-stretch.
If I could load these locally then I could use a font that I know works (e.g. the one from the interactive examples).

So this is not the only option, but it will significantly improve the options available.

**Comment by Rumyra** [comment]
Possibly related https://github.com/mdn/mdn-community/discussions/94

**Comment by hamishwillee** [comment]
@Rumyra It isn't related. https://github.com/orgs/mdn/discussions/94 is about what is the best way to store or define images such that when you have to update them you don't have to start from scratch. So for example, you might use SVG which is both editable and displayable, or you might use a drawing package and supply access to the source file or a sharable file.

**Comment by Rumyra** [comment]
Thanks @hamishwillee I was driving by - removing 👍
