### ISSUE TITLE
Consider not having different link colors for different site areas

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5755]
I haven't seen this reported anywhere else, so maybe it's an unpopular opinion, but I think MDN should not have different link colors for different areas of the site.

I do understand the desire to indicate that we are in "the CSS docs" with some accent color, but link colors are tricky to get right: we have to care about contrast, conventional expectations, not-found links (and conventional expectations about them), contrast against `<code>` formatting. And then do all that for both themes. Then having to do that for every bit of the site makes it really hard to get good colors.

I think it's also possibly confusing for users, who probably see MDN as a single site, to see different link colors on different pages.

**Comment by schalkneethling** [comment]
@wbamberg Thank you for bringing this up. I am actually going to propose that as part of the readability rework.

**Comment by spartanatreyu** [comment]
Yeah, supporting so many different colors next to code blocks might end up resulting in code blocks with diminished readability.

I still really like having the website sectioned into different colors though.

It would be very helpful for users who are new to the website, or just new developers in general. It works as a nice safety net since as soon as the colors change, you're immediate aware that you've travelled to the wrong part of the website when you're only interested in a specific section or web development.

This can happen a lot when navigating to something that the same name across two different sections.

For example:
1. https://developer.mozilla.org/en-US/docs/Web/CSS/animation
2. https://developer.mozilla.org/en-US/docs/Web/API/Animation

Some pages may both lie in the same section with very similar titles, but the solution here would be to rephrase the title.

For example:
- https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
  - The title of this page should probably be "An overview of Touch Events"
- https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent
