### ISSUE TITLE
Privacy tools like uBlock could cause problems with Plus

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5792]
From Slack, reported by Craig Cook:

> Just wanted to let you know that the subscribe section of the page is hidden for me by the "Fanboy's Annoyance" filter in uBlock Origin, which may be a pretty common filter in a popular addon, especially with tech-savvy users. So if you get reports of the subscribe button not working, that could be the reason.

**Comment by Yuki2718** [comment]
If you know the cause is FA, report the problem to https://github.com/easylist/easylist/issues

**Comment by bershanskiy** [comment]
Can confirm this, repro steps:
 - install uBlock Origin and enable "Fanboy’s Annoyance" list
 - go to the bottom of https://developer.mozilla.org/en-US/plus
 - toggle visual filters on and off, observe that the "Choose a plan" section disappears

The cause is [`##.subscribe-wrapper`](
https://github.com/easylist/easylist/blob/2435db8e5df6ff9b5f3cbf0d5600764b27ea552a/fanboy-addon/fanboy_newsletter_general_hide.txt#L2085) filter rule which matches identical class in Yari:
https://github.com/mdn/yari/blob/24c211f15181a177c0a03ded02d0da24108e070a/client/src/plus/offer-overview/offer-overview-subscribe/index.tsx#L310
Here is the corresponding CSS:
https://github.com/mdn/yari/blob/24c211f15181a177c0a03ded02d0da24108e070a/client/src/plus/offer-overview/offer-overview-subscribe/index.scss#L3

I see a trivial solution here: to just rename `subscribe-wrapper` to something else, e.g., `plus-subscribe-wrapper`.
