### ISSUE TITLE
Unreadable, terribly colored and designed website. Return to the old design

### ISSUE THREAD

**Issue by Krelyshy** [mdn/yari#5817]
### Summary

Hello,

I have not visited MDN for a bit, but I needed to look something up again. However, after getting to the site, I was confused and I thought that I was on a completely different webpage, and definitely not MDN. The logo? Awkward and ugly. But the colors and overall layout of the site? **Terrible!**

I do not know _how_ did someone even manage to do this, but the text really hurt my eyes (in all seriousness) and even though I tried really hard to adapt to it, I could not. The website is now, literally, impossible to read. Not only that, but the actual text content and explanations now take up a lot less space on my screen for some reason. So half of my screen is just blank. 

This is another case of someone breaking a completely functional, working and for years tested product which satisfied everyone except for a few douchebags who felt the need to do it "their own way" and have failed miserably.

I believe that I will speak for the absolute majority of developers and supporters of web when I say: **bring the old design back.** 
Altogether. I seriously do not want useless and dumb messages at the bottom of the page saying things such as "Your blueprint for a better internet", when it's not even true anymore.

If you don't, then I am telling you that the current MDN _is_ going to die off, as it is in a state far worse than unusable right now.

I do not know what led to this change, but I doubt that anyone wants it. If you think that the majority of developers actually does want this horrific style, then prove it.

Yes, there are a few good changes, such as that the content list of the page is now "sticky", but that can be applied to the original, good design as well.

As for now, I am going to use alternative hosts which still use the nice and old, yet modern style. One of such is https://mdn1.moz.one/en-US/docs/Web
and I encourage everyone who hates this _"design"_ to do so as well.

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. Visit the MDN web docs site
2. Expect to read and learn about something
3. Site makes it impossible to

### Expected behavior

I expected readability.

### Actual behavior

I see a complete mess

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Hi @Krelyshy, 👋 

Thank you for taking the time to open this issue, but please let me remind you to **be respectful** at all times, in accordance with our [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) that you have read. 

Your point has been [made before](https://github.com/mdn/yari/issues/5364) and one fellow MDN user has even [curated a set of CSS styles](https://github.com/mdn/yari/issues/5389) to revive the old design.

Since the MDN redesign, we have been receiving a good amount of positive and constructive feedback, upon which we have acted and continue to act. As for our new MDN logo, this was actually chosen by the MDN community (see [this article](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) to learn more), and we love it.

Changes can be hard at time, and we acknowledge that it can take some time getting used to the new MDN design. But we do ask you to give the MDN redesign a fair chance, and should you find issues that [haven't been raised before](https://github.com/mdn/yari/issues?q=is%3Aissue), to please report them in a constructive, actionable and respectful manner.

Please note that we have just [introduced MDN Plus](https://hacks.mozilla.org/2022/03/introducing-mdn-plus-make-mdn-your-own/) in the US & Canada as our first step to providing a personalized and more powerful experience, and we're definitely open to suggestions such as a minimalist theme, combining the simplicity of the old design with the power of the new design.

For now, I will go ahead and both close and lock this issue, because it violates our [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).

Thank you for your understanding, and thanks for using MDN. 🙏
