### ISSUE TITLE
Increase width of content column to fit 80 characters in example code

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5875]
(Original title: _Wrapping example code makes it unreadable sometimes_)

See for example: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters#basic_example . The example expects the code not to be wrapped, in which case it looks like:

```
body {
  counter-reset: section;                      /* Set a counter named 'section', and its initial value is 0. */
}

h3::before {
  counter-increment: section;                  /* Increment the value of section counter by 1 */
  content: "Section " counter(section) ": ";   /* Display the word 'Section ', the value of
                                                  section counter, and a colon before the content
                                                  of each h3 */
}
```

...but in the new design it is wrapped, so it looks like:

<img width="758" alt="Screen Shot 2022-03-31 at 11 05 12 AM" src="https://user-images.githubusercontent.com/432915/161121059-37525464-3746-498c-9651-f768e3b47c52.png">

**Comment by caugner** [comment]
@wbamberg Can we fix this in content?

**Comment by wbamberg** [comment]
I think we could, yes, with a bit of help from Yari.

We're gradually running Prettier over all our code samples. Prettier will wrap them nicely at 80 characters. However Yari wraps at a bit less than this, like 75 characters. Also, Prettier won't wrap strings or comments.

So I think we could fix this by:
- making Yari wrap at 80 characters rather than the current (which I think would be doable, and which would I think be better anyway)
- running Prettier
- eventually adding another check that errors for any line >80 characters

What do you think?

**Comment by caugner** [comment]
> * making Yari wrap at 80 characters rather than the current (which I think would be doable, and which would I think be better anyway)

We would have to reduce the font-size of `.code-example, code, pre` by 10% to `0.9rem` in order to fit 80 characters, which will impact a11y/readability.

1rem (status quo):
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/495429/201910192-ff448f70-5b93-4683-834d-5268a723415c.png">

0.9rem:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/495429/201910284-a76f5481-d6e8-41b2-8e2c-80fcd7fcc5a3.png">

However, mobile would still wrap:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/495429/201910402-763086f8-2955-48dd-aead-9b642877d8a3.png">

So we should still avoid same-line comments.

**Comment by wbamberg** [comment]
> > * making Yari wrap at 80 characters rather than the current (which I think would be doable, and which would I think be better anyway)
> 
> We would have to reduce the font-size of `.code-example, code, pre` by 10% to `0.9rem` in order to fit 80 characters, which will impact a11y/readability.

And/or you could steal a bit of width from the sidebar and/or ToC. It's just that:
- 80 characters is such a common standard for code width, it seems perverse for MDN's design to be just a bit less
- because 80 characters is a standard, we can use Prettier to get to 80 in content. But if it's 75 it's not practical for us to avoid wrapping in content.

But if it's impossible to get to 80, then we just have to live with it I suppose.

**Comment by Rumyra** [comment]
I agree with @wbamberg here - code should wrap at 80 chars. The font size in code blacks was increased recently due to changes _anyway_ - see https://github.com/mdn/yari/issues/7586 - so I'd be interested to see what a11y implications are with slightly smaller font size in code blocks.

Also (aside) short-titles should help with sidebars being large in the long run and allow us to open up the article a bit 🤞
