### ISSUE TITLE
Offline Settings: Does clear really clear?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5885]

**Comment by caugner** [comment]
Offline data is stored in the Service Worker [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache). When pressing the "Clear storage" data, we call [Cache.delete()](https://developer.mozilla.org/en-US/docs/Web/API/Cache/delete), and that should indeed clear all Offline data:

https://github.com/mdn/yari/blob/837e5d00d28dd8507f58846836db4e0dd71e7534/client/pwa/src/service-worker.ts#L294

If it doesn't, it's most likely a browser bug, but since nobody upvoted the issue, I will close this as "can't repro" for now.
