### ISSUE TITLE
Pages remain in dark mode with OS Default selected

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5981]
### Summary

Even though on the OS level I have set the color mode to automatic, pages stay in dark mode even during the day.

https://user-images.githubusercontent.com/10350960/163555569-5035b58c-dd70-43c5-b9af-5e900f1ffa84.mov

This seems to only happen in Firefox. I am running the latest stable version - `99.0.1 (64-bit)`

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

### Reproduction steps

1. Open a page in Firefox
2. Switch to OS default
3. The page is displayed in dark mode

### Expected behavior

1. Open a page in Firefox
2. Switch to OS default
3. The page matches the mode of the OS which is light mode

### Actual behavior

1. Open a page in Firefox
2. Switch to OS default
3. The page is displayed in dark mode

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@schalkneethling Most likely you have enabled the "Dark" theme in Firefox, and this takes precedence over the OS theme. If you would enable the "Light" theme in Firefox, "OS Default" in MDN will always show you the "Light" theme.

In order to have the "OS Default" option on MDN reflect your OS theme, you need to enable the "System theme - auto" in Firefox:
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/495429/189974317-bd78b2a8-6f3c-4a3f-9945-b1b3951dd7fd.png">
