### ISSUE TITLE
Can't view all items on  the page content sidebar fully unless I scroll to the bottom

### ISSUE THREAD

**Issue by LoyalPotato** [mdn/yari#6144]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys

### What information was incorrect, unhelpful, or incomplete?

Need  to scroll all the way to the bottom in order to see the full list of the side bar

![image](https://user-images.githubusercontent.com/10759876/166221293-81d1a131-8933-4cbf-874c-017ce63bb4f2.png)
![image](https://user-images.githubusercontent.com/10759876/166221191-491a03ae-3e2c-493c-9d11-9f501fa03d4d.png)

### What did you expect to see?

Be able to see the full list regardless of the main content scroll.

**Comment by caugner** [comment]
The root of the problem is that the sidebars scroll behind the `.article-actions-container`:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/495429/166294537-b81970a5-2455-4d6b-b128-27a68fa144a0.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/495429/166294564-b3b3c8e7-05ad-4a31-9212-c8d9f2a53d9b.png">

As a workaround, we added `top: var(--top-navigation-height)` to the `.sidebar`, but we forgot reducing the `max-height` by the same amount.

So, to fix the workaround, I will reduce the `max-height` of the `.sidebar`. The real solution would be to prevent the sidebar from scrolling behind the `.article-actions-container` (I couldn't figure this out right now), and I will add a follow-up issue for that.
