### ISSUE TITLE
Add Ukrainian language by default for Ukraine

### ISSUE THREAD

**Issue by alex-chaliy** [mdn/yari#6309]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/CSS/:root

### What specific section or headline is this issue about?

default language

### What information was incorrect, unhelpful, or incomplete?

Good afternoon. I'm Ukrainian, I live in Ukraine, I speak Ukrainian. I don't want to see any search results in ruzzian language. I want to access Mozilla Developers site with Ukrainian language by default. 

### What did you expect to see?

 I want to access Mozilla Developers site with Ukrainian language by default. I don't want to see any search results in ruzzian language.

**Comment by bershanskiy** [comment]
Disclaimer: I'm writing this as an occasional MDN contributor who identifies as a Ukrainian, lives in Ukraine, and speaks both Ukrainian and Russian on a daily basis. I read only English MDN since it's the most frequently updated one.

I think the real issue here is that MDN currently does not support Ukrainian at all. Ukrainian is not listed under ["Active locale"](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#active_locales): there is simply no content in Ukrainian that you could read on MDN.

@alex-chaliy Do you see any Ukrainian content on MDN? Perhaps, you are reading an automated translation? [Google Translate is integrated into Google Chrome](https://support.google.com/chrome/answer/173424) and can be activated accidentally. [Firefox supports translation extensions](https://support.mozilla.org/en-US/kb/how-add-translate-feature-firefox) which you might have installed and forgotten about. Also, you can use these translators to read MDN in Ukrainuan: just set MDN to English (since it is the most active and best-maintained locale) and set a translator to translate from English to Ukrainian.

@schalkneethling I tried the methods you [suggested](https://github.com/mdn/yari/issues/6309#issuecomment-1130124472), but I don't think they work since there is no Ukrainian content. These methods would work for all the supported locales, though.

**Comment by caugner** [comment]
Closing in favor of https://github.com/mdn/yari/issues/275, which covers this scenario.
