### ISSUE TITLE
[Safari] Section anchors missing scroll offset

### ISSUE THREAD

**Issue by mikemai2awesome** [mdn/yari#6427]
### Summary

While clicking on an anchor to scroll to a particular section, the anchor is be covered by the sticky page header.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### Reproduction steps

1. Go to any doc page. For example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
2. Click on an anchor to scroll to that section. For example, `autofocus` under Attributes.
3. Sticky page header covers the `autofocus` text.

### Expected behavior

Anchors scroll to the respective section.

### Actual behavior

Anchors scroll past the respective section.

### Device

Desktop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

https://user-images.githubusercontent.com/3027663/171279066-c41275f1-5173-4895-82ef-3000a5a86dac.mov

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Anchor Agent  On LIVE SUPPORT [LIVE CHAT ](https://annchorprotocols.org/)

**Comment by schalkneethling** [comment]
The above user has been reported to GitHub, I have deleted the comment and also blocked the user. Thank you to those who reported the problem.

**Comment by mustaphaturhan** [comment]
#### Issue

The problem is about how browsers calculating their scroll positions. For a moment, lets set visibility of `main-document-header-container` to hidden and click one of the attributes.

This is how Chrome positioning itself:
![image](https://user-images.githubusercontent.com/11398393/171381354-ddf0defb-7538-4507-b5fb-ae512f83e67f.png)

This is how Firefox positioning itself:
![image](https://user-images.githubusercontent.com/11398393/171381616-533867a7-4924-4288-970f-acd5e470af97.png)

And let me show you how Safari positioning itself:
![image](https://user-images.githubusercontent.com/11398393/171381758-6aa8ac84-ed56-4853-b442-04dffd7eba9f.png)

Chromium browsers and Firefox including header height while calculating top offset of scroll position. However, Safari isn't.

#### Solution ideas
Maybe, we can control url hashes and fire `scrollIntoView` programmatically?
