### ISSUE TITLE
Page titles should not wrap

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#6440]
When page titles are long they wrap:

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createChannelMerger

<img width="1114" alt="Screen Shot 2022-06-01 at 11 45 43 AM" src="https://user-images.githubusercontent.com/432915/171479467-2bdfd605-c24d-474f-b596-f5295fcba78b.png">

It's not a good look, and will happen more after the Great Renaming of Pages. Once upon a time I think title font size scaled to avoid wrapping.

**Comment by OnkarRuikar** [comment]
May I work on this?

How about using word break opportunity before `.`?
![screenshot](https://i.imgur.com/CJrIRIq.png)

**Comment by wbamberg** [comment]
It might also help to consider what page titles will look like after https://github.com/mdn/content/discussions/5121.

[It seems we will get things like](https://github.com/mdn/content/discussions/5121):

### BaseAudioContext: createChannelMerger() method

I'm no designer, but as a reader I'd prefer it on one line even if it meant the font size had to be smaller. I guess that would also affect the other headings (wouldn't want H2 headings to be bigger than H1).

**Comment by caugner** [comment]
> How about using word break opportunity before `.`?

I talked with our designer today, and we would accept a PR that makes the word break before `.` rather than in the middle of the method name, provided that it doesn't add a hyphen on the previous line. (I tested with `&shy;` and that added a hyphen on the previous line.)

**Comment by wbamberg** [comment]
Thanks @caugner ! I think this issue is affected/mostly obsoleted by https://github.com/orgs/mdn/discussions/248, see in particular https://github.com/orgs/mdn/discussions/248#discussioncomment-3919672 .

https://github.com/mdn/content/pull/21810 shows what these new titles would look like.

**Comment by caugner** [comment]
Since some titles (like [this one](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable)) will still wrap after implementing the discussed solution, we can extend [the specification above](https://github.com/mdn/yari/issues/6440#issuecomment-1292460258) to add soft wraps not only before `.`, but additionally between all camelCased words (`Public|Key|Credential|.is|User|Verifying|...`). Probably there should be a CSS property to achieve this behavior (but I don't think there is yet).

Anyways, we can improve the wrapping here *and* improve the titles, it doesn't conflict with each other.

**Comment by wbamberg** [comment]
Would this still preferentially break at spaces? I mean it would be better to have:

```
PublicKeyCredential:
isUserVerifying
```

than:

```
PublicKeyCredential: isUser
Verifying
```

**Comment by caugner** [comment]
> Would this still preferentially break at spaces? I mean it would be better to have:

Hm, good point, it would indeed probably not look good in that case. 🤔

**Comment by wbamberg** [comment]
@caugner , I think we can close this, probably, now we have new page titles in Web/API?

-> https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createChannelMerger
