### ISSUE TITLE
Search box overrides Home and End key

### ISSUE THREAD

**Issue by Nickwiz** [mdn/yari#6466]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

Search box

### What information was incorrect, unhelpful, or incomplete?

The search box has bound `Home` and `End` to jump to start / end of suggestion list. 

This interfere if one want to jump in the *text* one is writing. I.e.

```
some text| here
         |
         +---- cursor here
```

By pressing:
* `Home`: Cursor is not moved to start but one navigates the start of suggestion list.
* `Shift` + `Home`: One do not select all text before cursor, but navigates to start of suggestion list.

Further if there is one or no suggestions it appears as if the `Home` and `End` keys are not working as nothing happens.

Believe one should do a check for `Shift` and `Ctrl` when `Home` and `End` is pressed.

* `Home`: Start of suggestion list
* `End`: End of suggestion list
* `Ctrl` + `Home`: Jump to start of input (Default behavior)
* `Ctrl` + `End`: Jump to end of input (Default behavior)
* (`Ctrl` +)<sup>1</sup> `Shift` + `Home`: Select text from cursor to start (Default behavior)
* (`Ctrl` +)<sup>1</sup> `Shift` + `End`: Select text from cursor to end (Default behavior)

<sup>1: `Ctrl` not needed as it is not a textarea but behavior is the same with / without</sup>

In other words, *"simply"* not navigate the suggestion list if either modifier is pressed and let the browser do it's default action.

One could of course also turn it around and say:

* `Ctrl` + `Home`: Jump to start of suggestion list
* `Ctrl` + `End`: Jump to end of suggestion list

And leave `Home` and `End` as their defaults - but think this would perhaps be more confusing.

### What did you expect to see?

When pressing `Shift` + `Home` for the text to be selected.

### Do you have anything more you want to share?

Not sure if this is the correct place to submit this bug / suggestion, but closest I found.

### Addition

*(Unable to add Comment in thread without also Closing the ticket - so added this section as an edit).*

Forgot to change: (Sorry about that) 

If suggestion list is empty: leave all key-presses as default. 

I.e. Home, End keys move around in text of input field and and not suggestions.

Believe that would be more end-user friendly as it does not seem like disabled keys.

So, should have been:

* `Home`: Start of suggestion list if any, else start of input field
* `End`: End of suggestion list, else start of input field

**Comment by caugner** [comment]
Hi @Nickwiz, thank you for taking the time to open this issue. 👋 

Please note that we're using [Downshift.js](https://github.com/downshift-js/downshift) and their [Combobox](https://www.downshift-js.com/use-combobox/) implementation for the search suggestions, and we haven't customized their [default event handlers](https://github.com/downshift-js/downshift/tree/1c7698080805e05f5180dd223cbc17932a85fd42/src/hooks/useCombobox#event-handlers), nor do we plan to do so.

However, you should be able to use `Ctrl+LeftArrow` and `Ctrl+RightArrow` to go to the start / end of the input value. 😉

**Comment by captainbrosset** [comment]
I would like to note that this is often frustrating to me on MDN. I don't have the muscle memory of using Ctrl (with Shift) to select text, and I always use Home / End (with Shift) to do this instead, only to realize that it doesn't work on MDN.

Here is my most common scenario: I type something incorrect, which leads to 0 results, then I want to select the entire text quickly with Shift+Home to type over it.

I never realized that Home/End moved in the suggestion list, because I always use Home only and the selected item is already the first one. Or, because there are no items in the list.

I also never realized that Ctrl+Arrow could be used to move around in the field. I mean, I know and use this shortcut in plenty of other places, but I know it moves to the previous word, and what I almost always want to do on MDN, is move to the beginning of the field. So I guess it never occurred to me that I could use this here.

Here are examples of a combo boxes that I use all the time and where Home/End move within the text field:

* The URL bar of my web browsers. That's where my muscle memory largely comes from.
* The search field in Gmail.
* The Windows' Start Menu. Once you start typing, you can still move within the field with Home/End but also navigate within the app/document suggestions with down/up arrow keys.

Another couple of interesting data points:

* MDN's page about the [Aria combox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role#keyboard_interactions) doesn't mention that Home/End should be used to navigate within the list
* The [Aria Combobox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/) says:
  
  > Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.

I'm all for keyboard navigation in the suggestions list, but I don't think this should be at the expanse of disabling means of navigation within the text field itself. A combo box is first, and foremost a text field, and most of the interaction (at least for me) happens within the text field, by iterating a few times on different values until the expected list of suggestions is reached. At that point, I personally reach for my mouse, but will sometimes use the down arrow key to reach the item I want (which is often within the first few results). I've never had to jump directly to the end of the list.

I would love for the MDN team to reconsider your position on this.

Thanks all!

**Comment by Juraj-Masiar** [comment]
See also:
https://github.com/downshift-js/downshift/issues/1162
