### ISSUE TITLE
[kumascript] Display error on invalid Live Sample

### ISSUE THREAD

**Issue by karlhorky** [mdn/yari#6577]
### Summary

Originally reported in mdn/kumascript#1214, which was just recently closed by @schalkneethling 

Hi there! First of all, thanks for all of the work that is done as part of MDN and the Learn Web Development documentation. It is an invaluable resource for developers of all skill levels.

Live samples can be invalidated if the matching id does not exist (see @SphinxKnight's [tweet](https://twitter.com/Sphinx_Twitt/status/1159698206281932800)):

> Basically the "live sample" system uses the id of the headings and is case sensitive aaaand the last edit on the page changed those headings.

As mentioned in [my tweet](https://twitter.com/karlhorky/status/1159857168096616455), it would be awesome if an error was displayed when an invalid live sample was saved:

> Would be cool if these types of errors wouldn't be possible

[One solution proposed](https://bugzilla.mozilla.org/show_bug.cgi?id=1572444#c4) by @SphinxKnight was to edit macros/EmbedLiveSample.ejs and macros/LiveSampleURL.ejs:

> I guess a realistic solution could be an edit on [https://github.com/mdn/kumascript/blob/master/macros/LiveSampleURL.ejs](https://github.com/mdn/kumascript/blob/master/macros/LiveSampleURL.ejs?rgh-link-date=2019-08-12T09%3A17%3A25Z) or [https://github.com/mdn/kumascript/blob/master/macros/EmbedLiveSample.ejs](https://github.com/mdn/kumascript/blob/master/macros/EmbedLiveSample.ejs?rgh-link-date=2019-08-12T09%3A17%3A25Z) to check for the existence of the section/id.

Although not completely preventing these errors from happening, this would at least be a step in the right direction.

---

Better, more complex solution: Validate live samples as they are saved and do not allow saving an invalid document state.

Although, [as Julien G mentioned](https://bugzilla.mozilla.org/show_bug.cgi?id=1572444#c4):

> This would only display an alert on the saved page but I'm afraid that solution 1 (checking beforehand) is "too far" regarding the current state of Kuma (the underlying backend for MDN)

### URL

https://developer.mozilla.org/en-US/docs/Learn

### Reproduction steps

1. Create and deploy an invalid live sample
2. It's broken without any notice to the author or user

### Expected behavior

Some notice should be displayed during authorship / usage of the website

### Actual behavior

It's broken without any notice to the author or user

### Device

Other (specify below)

### Browser

Other (specify below)

### Browser version

Other version (specify below)

### Operating system

Other (specify below)

### Anything else?

Not browser or operating-system specific

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by wbamberg** [comment]
I think this is a good idea. One slightly different version could be to run it as a CI check in mdn/content - we already do this for various things like uncompressed image files. I think this would be better than having these errors escaping into production pages.

One issue is that technically the ID argument is now optional in live samples, although there are some unresolved issues with this (https://github.com/mdn/yari/issues/5005, https://github.com/mdn/yari/issues/5006) so it's not widely used. But we could at least validate the places where the ID argument is used.

@OnkarRuikar , you've done a lot of stuff in this area lately, wdyt?

**Comment by OnkarRuikar** [comment]
The issue mentioned in OP is no longer valid because, now if the id is not found then the live sample generator goes one level up and collects all css, html, and js code blocks. 
But this automatic collection of code blocks some times grabs unwanted code as well. This has generated a lot of silent errors on the content pages. Noticeable ones have been fixed recently. But I believe many are still lingering.

There other issues related to the macro. To be on the same page here are some issues:
````md
## Example 1

### HTML

```html
<h1>one</h1>
```

Works fine shows "one".
{{EmbedLiveSample('Old title', '100', '100')}}

---------------------------------------------------------------------

## Examples 2

```html
<h1>2</h1>
```

This shows "2" but "two" is ignored
{{EmbedLiveSample('b', '100', '100')}}

### HTML

```html
<h1>two</h1>
```

---------------------------------------------------------------------

## Examples 3

### Html

```html
<h1>three</h1>
```

This shows "one".
{{EmbedLiveSample('html', '100', '100')}}

---------------------------------------------------------------------

## Example 4

```js
let let a = 3;
```
Logs syntax error in user's browser.
{{EmbedLiveSample('Example 4', '100', '100')}}

````
To reproduce the issues, paste this entire section in a content page.
If you know/find any then let us know.

***
@karlhorky 
> Better, more complex solution: Validate live samples as they are saved and do not allow saving an invalid document state.

For contributors using `git`, we do not have git `pre-commit` hooks in mdn/content repo. It is not as strict as mdn/yari.
For contributors using `GitHub`, we have PR Companion that tells us errors found in modified files. For example, https://github.com/mdn/content/pull/17365#issuecomment-1158428931 look for the macro related flaws listed under `macros:` sections. The reviewers are supposed to look at the preview URLs and check the flaws before merging the PRs.

***
@wbamberg 
> But we could at least validate the places where the ID argument is used.

How about we add flaw cheeking for these issues? ID checking can be done in the macros. And for syntax errors we can have dedicated flaw checker in [mdn/yari/tree/main/build/flaws](https://github.com/mdn/yari/tree/main/build/flaws)

**Comment by karlhorky** [comment]
> For contributors using `GitHub`, we have PR Companion that tells us errors found in modified files. For example, [mdn/content#17365 (comment)](https://github.com/mdn/content/pull/17365#issuecomment-1158428931) look for the macro related flaws listed under `macros:` sections. The reviewers are supposed to look at the preview URLs and check the flaws before merging the PRs.

Seems also fine to me 👍 (although I'm not experienced with the codebase / processes)
