### ISSUE TITLE
Copy change request - https://developer.mozilla.org/en-US/community

### ISSUE THREAD

**Issue by HerminaC** [mdn/yari#6619]
Hi, 

Please make the following changes:
Section -> How to contribute
- end of first paragraph -> drop the word 'please' and leave only [Join us](https://developer.mozilla.org/en-US/docs/MDN/Contribute)!, all in blue color (exclamation mark included)
- same paragraph - the word 'web' should be all lowercase - please change in two places 

Thanks!

**Comment by caugner** [comment]
@HerminaC Should we replace all four occurrences of `Web` on the page, or just the two (3+4) you pointed out:

1. "Community for a better **Web**" (heading)
2. "MDN is an influential resource and the PAB helps ensure that MDN’s influence puts the Web first (...)" (section "The Product Advisory Board")
3. "We are an open community of developers building resources for a better Web (...)" (section "How to contribute")
4. "Together we can continue to drive innovation on the Web (...)" (section "How to contribute")

**Comment by caugner** [comment]
@Rumyra Does [this page](https://developer.mozilla.org/en-US/community) require any other changes apart from the ones mentioned above?

**Comment by Rumyra** [comment]
Hey @caugner - the following:

* Under 'Licensing' there's a link which should be updated to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license
* Under 'How to contribute' the 'join us' link should point here https://developer.mozilla.org/en-US/docs/MDN/Community
* Also in this section the 'making your first contribution' link should go here https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Getting_started

Otherwise copy seems good 👍

**Comment by caugner** [comment]
> Should we replace all four occurrences of `Web` on the page

As clarified with @Rumyra, all occurences of `Web` on the Community page should be replaced with `web`.
