### ISSUE TITLE
More and more links are running into a 404

### ISSUE THREAD

**Issue by alexander-schranz** [mdn/yari#6629]
### Summary

More and more links to mdn docs are landing on page not found. Not sure what was restructered but it would be nice to track 404 and check where the content was moved.

### URL

https://developer.mozilla.org/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement

If I don't forget I will add here over the time more links, but I would recommend tracking the 404 and redirect them correctly.

### Reproduction steps

Somewhere today I clicked a link like this: [https://developer.mozilla.org/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement](https://developer.mozilla.org/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement) and this content seems to be gone or not correctly redirected.

### Expected behavior

Redirect to to most new page with for that content.

### Actual behavior

ends in 404

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

Filled a bug report because of: https://twitter.com/MozDevNet/status/1541832746334650369

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by teoli2003** [comment]
If I remember correctly we moved _Core_JavaScript_1.5_Guide_ pages to their current location in 2014 or 2015. I'm surprised there are still links to these old URLs out there. Out of curiosity, where did you find such links?

**Comment by alexander-schranz** [comment]
Not sure where but for example stackoverflow answers link to it: https://stackoverflow.com/questions/5963045/can-syntax-errors-be-caught-in-javascript.
The internet never forget something 😄

**Comment by teoli2003** [comment]
Yes, it is worth fixing (and not too difficult)
@schalkneethling Do you think you can provide the list of 404 pages with _Core_JavaScript_1.5_Guide_ in their slug over the last year, then we can add the modern pages and add redirects.

**Comment by alexander-schranz** [comment]
I found my general issue the links on caniuse are directed based on my `Accept-Language`: `de` which ends on 404 pages:

 - https://developer.mozilla.org/docs/Web/CSS/aspect-ratio -> https://developer.mozilla.org/de/docs/Web/CSS/aspect-ratio
 - Found on: https://caniuse.com/mdn-css_properties_aspect-ratio
 
 - https://developer.mozilla.org/docs/Web/API/ImageBitmap/width -> https://developer.mozilla.org/de/docs/Web/API/ImageBitmap/width
 - Found on: https://caniuse.com/mdn-api_imagebitmap_width

 - https://developer.mozilla.org/docs/Web/CSS/flex-direction -> https://developer.mozilla.org/de/docs/Web/CSS/flex-direction
 - Found on: https://caniuse.com/mdn-css_properties_flex-direction
 
Personally prefer english docs so I would be fine with a none language specific redirect here :). But thats just me.

**Comment by schalkneethling** [comment]
@mdn/core-dev I have also run into this with `/community` if used without a `locale`. https://developer.mozilla.org/community is a 404 but https://developer.mozilla.org/en-US/community is fine

**Comment by caugner** [comment]
First of all, we do track 404s and we add missing redirects for frequently visited urls from time to time.

In the case of the URL you're citing, it appears that https://github.com/mdn/content/pull/1857 removed the corresponding _explicit_ redirects from `_redirects.txt` (in mdn/content), because they were added to our [fundamental redirects](https://github.com/mdn/yari/blob/main/libs/fundamental-redirects/index.js) (here in mdn/yari) in https://github.com/mdn/yari/pull/2698. And they still seem to be (except that they require the `/docs/` part in the url):

https://github.com/mdn/yari/blob/3c9d149aef2a4d6c747ab1f4e55a321e36d48a89/libs/fundamental-redirects/index.js#L1215-L1225

And indeed, while [/en-US/Core_JavaScript_1.5_Guide](https://developer.mozilla.org/en-US/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement) does NOT redirect (due to the missing `/docs/` part), [/en-US/docs/Core_JavaScript_1.5_Guide](https://developer.mozilla.org/en-US/docs/Core_JavaScript_1.5_Guide/Exception_Handling_Statements/try...catch_Statement) does redirect to [/en-US/docs/Web/JavaScript/Guide/](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Exception_Handling_Statements/try...catch_Statement), except that this specific page (and the whole "Exception Handling Statements" area) was moved into a section of [Web/JavaScript/Guide/Control_flow_and_error_handling](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#exception_handling_statements).

@alexander-schranz If you like, you could try and open a PR in mdn/content to add the following redirects to the `_redirects.txt`, but I cannot guarantee that they would be accepted:

```
/en-US/docs/Web/JavaScript/Guide/Exception_Handling_Statements /en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#exception_handling_statements
/en-US/docs/Web/JavaScript/Guide/Exception_Handling_Statements/throw_Statement /en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#exception_handling_statements
/en-US/docs/Web/JavaScript/Guide/Exception_Handling_Statements/try...catch_Statement /en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#exception_handling_statements
```

> Not sure where but for example stackoverflow answers link to it: https://stackoverflow.com/questions/5963045/can-syntax-errors-be-caught-in-javascript.

This StackOverflow post links to `/en-US/Core_JavaScript_1.5_Guide/Statements#try...catch_Statement`, and the redirect would work if the URL had `/docs/` in it. I believe StackOverflow users with enough reputation could actually update the links in the answer.

> I found my general issue the links on caniuse are directed based on my Accept-Language: de which ends on 404 pages:

This is a separate issue, see e.g.:

- https://github.com/mdn/yari/issues/275
- https://github.com/mdn/yari/issues/2724

> I have also run into this with `/community` if used without a `locale`. https://developer.mozilla.org/community is a 404 but https://developer.mozilla.org/en-US/community is fine

I think only `/docs/*` without a locale get redirected to `/{locale}/docs/*` though, but we could look into redirecting meta pages as well.

**Comment by alexander-schranz** [comment]
I think the main problem is that not all pages are translated so example [https://developer.mozilla.org/docs/Web/CSS/aspect-ratio](https://developer.mozilla.org/docs/Web/CSS/aspect-ratio) redirect me to [https://developer.mozilla.org/de/docs/Web/CSS/aspect-ratio](https://developer.mozilla.org/de/docs/Web/CSS/aspect-ratio).

So the strategy would need to be implemented there. If the page does not exist in the "target locale" it should not redirect to a 404 page.

There are 2 possibilites. Show default locale / english content on https://developer.mozilla.org/de/docs/Web/CSS/aspect-ratio or do a redirect to `/en/...` instead of `/de/...`.

**Comment by caugner** [comment]
> I think the main problem is that not all pages are translated so example https://developer.mozilla.org/docs/Web/CSS/aspect-ratio redirect me to https://developer.mozilla.org/de/docs/Web/CSS/aspect-ratio.

In that case, you do already get a message "The page you requested doesn't exist in German but it exists in English":
<img width="793" alt="image" src="https://user-images.githubusercontent.com/495429/186127358-3f2cbefa-f5f3-47d1-a0a2-685424b162e7.png">

Note that the German locale [will be archived](https://github.com/mdn/mdn-community/discussions/147) in the next few weeks, so from that moment on there will be a redirect to `en-US`, like already in place for other retired locales: https://developer.mozilla.org/tr/docs/Web/CSS/aspect-ratio
