### ISSUE TITLE
Use <nav> rather than <aside> for the ToC

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6852]
### Discussed in https://github.com/mdn/yari/discussions/4693

<div type='discussions-op-text'>

<sup>Originally posted by **ladrabanana** September 17, 2021</sup>
I just realised by looking at the aside [page ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside#examples) that the Table of contents on the left side is an aside element. 

As this Table of contents displays navigation links I think that it should be a nav. Not that it would make a huge change, but it makes more sense semantically and in a page that explains what the HTML elements are it'd be the thing to do. 

This is element is the same in several pages so I'm not sure how the mark-up could be changed to nav, could anyone tell me how to make this happen?

Any help would be really appreciated :) 

Thanks a lot!</div>

**Comment by caugner** [comment]
_Note: Since the redesign in March 2022, the TOC in question is now on the right side, but still an `aside` element._

I agree with the OP (@ladrabanana) that a `nav` element might be better suited.

However, a solution has to consider the two responsive breakpoints at which navigation layout changes:

1. On large screens, there is a `nav.sidebar-quicklinks` on the left and a `div.toc` containing `aside.document-toc-container` on the right.
2. On medium screens, there is only a `nav.sidebar-quicklinks` on the left, **but** it contains a `div.in-nav-toc` with the `aside.document-toc-container` from the right.
3. On small screens, the sidebar can be toggled via a button, which reveals the `nav.sidebar-quicklinks` on the left, containing a `div.in-nav-toc` with the `aside.document-toc-container` like on medium screens.

Maybe it would make sense to change:
- `aside.document-toc-container` to `nav.document-toc-container`.
- `nav.sidebar-quicklinks` to `div.sidebar-quicklinks`
- Wrap the remainder of `div.sidebar-inner` in a `nav` element.

This would essentially avoid nesting `nav`s, and avoid using an `<aside>` for something that isn't aside.
