### ISSUE TITLE
Suggestion for improving JS/API sidebars — add labels to indicate page types.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#6968]
@valango commented on [Fri Sep 25 2020](https://github.com/mdn/sprints/issues/3725)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The left-side navigation column at (https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript) 
is somewhat confusing for people not experienced in Javascript - labels for _constuctors_, _interfaces_ and global object _instances/namespaces_ all look the same.

Perhaps it would be helpful to have a "type tag" next to object name, like below (do not mind the bullets in the left):

* [Math](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math) `namespace`
* [NaN](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) `constant`
* ...
* [TypeError](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) `constructor`
* [TypedArray](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) `interface`

Almost everything is an object in Javascript, so the current presentation _is_ correct, of course.
Adding some specifics would just make it a little more helpful for newbies.

Sorry, I am newbie myself to the Wiki editor, so could not find the right place to make those changes. ;)

---

@chrisdavidmills commented on [Mon Sep 28 2020](https://github.com/mdn/sprints/issues/3725#issuecomment-699929591)

I like this idea, but we don't have the capacity to look into it now. I'm going to transfer this to the Kuma (MDN platform) repo, and we can hopefully put it the backlog to consider as we redesign sidebars in the next iteration of MDN.

**Comment by caugner** [comment]
@wbamberg What are your opinions on this?

**Comment by wbamberg** [comment]
AFAICT this is talking about the "Global Objects" section of the sidebar, which does include things that don't look like objects, such as `NaN` and `parseInt()` (and of course namespaces have come up in https://github.com/mdn/yari/issues/3826).

But I don't think the solution would be to label every entry. That would make the sidebar very noisy. It would be better to reorganize the sidebar so that section does only contain objects, and if necessary have other sections for things like global functions and maybe namespaces, and label each section properly. This is also tied to https://github.com/mdn/content/issues/16156 .

So maybe we should close this one and track that work inhttps://github.com/mdn/yari/issues/3826?

**Comment by caugner** [comment]
> So maybe we should close this one and track that work in #3826?

Sounds good to me! Closing in favor of https://github.com/mdn/yari/issues/3826.

I guess the problem also is that `NaN` is a child of `Global_Objects`, so the hierarchy itself is misleading and the JS sidebar is merely building on top of that.
