### ISSUE TITLE
Integrate Flaw detection with CI

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#715]

**Comment by peterbe** [comment]
Let's simply do this:

1. Some day after the big-bang migration, we manually take a stab at fixing all the fixable flaws (broken links, xref redirect macros, remote file attachments) and that'll bring down the number of flaws into the hundreds. 
2. Once that's done, simple set `BUILD_FLAW_LEVELS="*:error"` in the PR Build CI workflow and if your PR fails because of a pre-existing flaw, either...
2.a. You take responsibility for fixing what you didn't even cause in your PR
2.b. You ask the reviewer to make an exception and merge it with the PR Builds CI failing.
