### ISSUE TITLE
Cannot display other `<input>` types on sidebars at some localized page

### ISSUE THREAD

**Issue by jasonren0403** [mdn/yari#7394]
### Summary

When going through localization work under HTML "`<input>` types", I found it hard to navigate between different pages of `<input>` type, and for other languages' page(en-US/zh-TW/ja/fr/es), however, can correctly display related `<input>` type page on sidebar.

### URL

1. https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input 
2. https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input 
3. https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input

### Reproduction steps

1. Go to any of the URL listed in URL section.
2. Only 'HTML Elements' is displayed on the 'Related Topics' section.
3.

### Expected behavior

"`<input>` types" and any other elements related also display on the 'Related Topics' section like the English version

### Actual behavior

"`<input>` types" does not display

### Device

Desktop

### Browser

Edge

### Browser version

Stable

### Operating system

Windows

### Screenshot
here is what all localization page should be:
![should be](https://user-images.githubusercontent.com/40999116/196943416-18fad27e-da61-4395-89ca-7cf0787d4a50.png)

zh-CN page is not displaying "`<input>` types" section, some other elements are not displaying either.
![current zh-cn](https://user-images.githubusercontent.com/40999116/196943527-48660626-6be4-4f36-9616-590b43f53a04.png)

ko page is not displaying the "`<input>` types" section
![current ko](https://user-images.githubusercontent.com/40999116/196943652-a0454bb3-c9bf-4b9d-9ff6-0a3cc8a8a840.png)

ru page is not displaying the "`<input>` types" section, and some elements are missing
![current ru](https://user-images.githubusercontent.com/40999116/196944041-d4c96826-dad4-44a9-b4b6-a6670fa444a5.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@jasonren0403 Thank you for taking the time to report this issue. 👋 

The problem arises from the fact that the sidebar uses tags from the page metadata:

https://github.com/mdn/content/blob/935b38a26ee3a3951403f5a0f459963678540c27/files/en-us/web/html/element/input/index.md?plain=1#L4-L14

And the translated page doesn't have any tags:

https://github.com/mdn/translated-content/blob/d0eddff2c6ceaa13557130ff80dfddaf1698a1c7/files/zh-cn/web/html/element/input/index.md?plain=1#L1-L4


@wbamberg Should metadata like `page-type`, `tags`, `browser-compat` and `spec-urls` be duplicated into translated-content, or should we rather infer these from the original page?

**Comment by wbamberg** [comment]
> @jasonren0403 Thank you for taking the time to report this issue. 👋
> 
> The problem arises from the fact that the sidebar uses tags from the page metadata:
> 
> https://github.com/mdn/content/blob/935b38a26ee3a3951403f5a0f459963678540c27/files/en-us/web/html/element/input/index.md?plain=1#L4-L14
> 
> And the translated page doesn't have any tags:
> 
> https://github.com/mdn/translated-content/blob/d0eddff2c6ceaa13557130ff80dfddaf1698a1c7/files/zh-cn/web/html/element/input/index.md?plain=1#L1-L4
> 
> @wbamberg Should metadata like `page-type`, `tags`, `browser-compat` and `spec-urls` be duplicated into translated-content, or should we rather infer these from the original page?

Good question! I think we should infer them (they should always be the same). I guess only `title` is localizable? cc @SphinxKnight  though.

`tags` is tricky because they can mean anything. Maybe tags should be concatenated? But then that doesn't necessarily help with this case, where we look for [the **first** tag of the form "HTML XYZ"](https://github.com/mdn/yari/blob/1ecb6cd2f07bec1872bbc48740583cf0b8f8d2e2/kumascript/macros/HTMLRef.ejs#L33). Long term though I would like to remove all(?) tags.

But also note that https://github.com/mdn/content/pull/21617#issuecomment-1286240392 proposes to remove HTMLRef and just use HTMLSidebar across all our HTML docs, so this will be a non-issue (assuming that HTMLSidebar's handling of input types is good enough).

*********

It's worth thinking a bit about what this sidebar is trying to do. It wants to say: there are different categories of HTML page, and we want to treat them differently in some way (like, displaying them in their own sections of the sidebar). We do something similar in https://developer.mozilla.org/en-US/docs/Web/HTML/Element#inline_text_semantics, and maybe this grouping is supposed to reflect the categories in the specification: https://html.spec.whatwg.org/multipage/text-level-semantics.html#text-level-semantics.

The sidebar does it using this slightly cryptic rule about "first tag starting 'HTML '". If we did want to support something like this we might prefer to use a dedicated front matter key like "html-category" (not a particularly good name) which explicitly identifies the specification category. Maybe in some future webref might give this to us.

There are questions though. The categories in the spec (and in https://developer.mozilla.org/en-US/docs/Web/HTML/Element) are just for elements. Is this tagging system also just for elements? It appears to be, but it's unclear.

**Comment by wbamberg** [comment]
(I should also say that I don't like the behavior of HTMLRef here. I think sidebars should stay consistent when you navigate across pages, and it's better to do what HTMLSidebar does and show all the elements (including all the `<input>` types, which are effectively independent elements), and always be the same.)

**Comment by SphinxKnight** [comment]
@caugner / @wbamberg `tags` should be inferred from the English "reference" document (see https://github.com/mdn/translated-content/issues/7412)
In other words "the set of tags of a localized page should at least contain the tags of the English page"

IMO, both Yari and KS macros should obey the same logic while resolving metadata. (see https://github.com/mdn/yari/blob/5d8d88976164b6f653c3f2de688f3cd76f8537bb/kumascript/index.js#L56-L69 / now https://github.com/mdn/yari/blob/main/kumascript/index.ts#L66-L68)

I guess a fix for the `HTMLRef` macro could be a palliative or we could directly go forward in localized docs and use `HTMLSidebar`
@jasonren0403 would the second option solve the issue for you?

**Comment by yin1999** [comment]
ah, I found the problem.

in `en-US`, the slug will startswith `Web/HTML/Element/input` but in some locale, the slug startswith `Web/HTML/Element/Input`

which is not match with `/HTML/Element/input` (`Input` not match with `input`)

![image](https://user-images.githubusercontent.com/15844309/198772515-80ea8510-c23f-4bef-b45d-f93432c2c416.png)

I'm going to fix this.

**Comment by yin1999** [comment]
I've created #7452 to fix this. But only fix the issue, **not a redesign**.

**Comment by yin1999** [comment]
> It seems that we are deprecating this macro.

After we have [replaced the {{HTMLRef}} macro in translated-content](<https://github.com/mdn/translated-content/pulls?q=is%3Apr+HTMLRef+-%3E+HTMLSidebar+>). It's no more an issue.

![image](https://user-images.githubusercontent.com/15844309/199709956-f98e28bd-b663-4750-b429-85badcd99413.png)
