### ISSUE TITLE
Q Raw data of docs for JsonSchema

### ISSUE THREAD

**Issue by askirmas** [mdn/yari#768]
I want to collect CSS docs and save as JsonSchema like
```json
{
  "border": {"propertyNames": {"enum": ["left","right"]}} 
}
```
Is somewhere more structured data than HTML values @ _client/build/**/index.json_ ? To not produce weird exporter.

**Comment by peterbe** [comment]
Wrong repo.

**Comment by askirmas** [comment]
@peterbe Oops, sorry. Can you say which one is correct?

**Comment by peterbe** [comment]
> @peterbe Oops, sorry. Can you say which one is correct?

Hehe. I was wrong in saying wrong repo. Sorry. 
If you want to get structured data out of MDN there are some options:

1. The [Stumptown initiative](https://github.com/mdn/stumptown-content) which is about turning unstructured blobs of documentation (in HTML with macros) into Markdown with structured data. This project might be hard to understand because it's early stages and a lot of flux. 
2. The [browser-compat-data](https://github.com/mdn/browser-compat-data/) is more about compatibility than anything. 
3. What yari produces is just blobs of text to support the rendering of complete HTML pages. Those `index.json` are considered implementation details. Not an API. But you can still attempt to use it and do your own post-processing.

**Comment by askirmas** [comment]
So yari is first of all template system. Therefore quick question - how do you obtain those `index.json`?

**Comment by peterbe** [comment]
> So yari is first of all template system. Therefore quick question - how do you obtain those `index.json`?

`node content build -l en-us`

The `-l en-us` is just an example of many parameters you can do to filter and stuff. This one just means "filter locales to 'en-US' only".

**Comment by askirmas** [comment]
That's exactly my question :) How do all *index.json* appear after `node content build -l en-us`? Should be one of 2 options
1. Content is already in repo but in different shape/format. Looks like not this
``` bash
$ grep -rl "The background shorthand CSS property sets all background style properties at once" --exclude-dir=build .

./content/_all-titles.json
```

2. Obtained from external source - that was my question

**Comment by peterbe** [comment]
There are sources in `content/files/**/index.html` files. On disk. And checked into git.
The `node content build ...` command transforms that into `index.html` and `index.json` files. These can be found in `client/build/**/index.json` afterwards. On disk. These are all part of the `.gitignore` just like any build artifact like `client/build/static/**`
