### ISSUE TITLE
Font size in code blocks is too large in Safari

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#7695]
### Summary

To me the font size in code blocks in Safari is too large.

### URL

Any MDN page with code blocks.
For example, https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/nextHopProtocol

### Reproduction steps

1. Open Chrome and Safari
2. Make the both windows the same width
3. See how the code example in Safari wrap lines a lot and how large the font size is.

### Expected behavior

- Safari renders the code font as small as Chrome does.
- Line wrapping in Safari is the same as in Chrome.

### Actual behavior

Safari renders font in code blocks too large.
Lines are wrapped a lot making the code unreadable.

### Device

Laptop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

Safari
![Bildschirm­foto 2022-11-29 um 10 58 25](https://user-images.githubusercontent.com/349114/204498274-1cd98bc9-d4c6-491c-b561-d5ec033f9a09.png)

Chrome
![Bildschirm­foto 2022-11-29 um 10 58 41](https://user-images.githubusercontent.com/349114/204498285-f61c6f55-b195-4d64-8e18-77c395173f86.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
This regression is caused by https://github.com/mdn/yari/pull/7131, but it's weird:

- In Firefox, the computed font-size of the `<code>` block is 16px:
  <img width="440" alt="image" src="https://user-images.githubusercontent.com/495429/204552840-c3f1ab3b-6d94-4387-a109-c2536a10b963.png">
- In Safari, the computed font-size of the `<code>` block is 19.692308px:
  <img width="302" alt="image" src="https://user-images.githubusercontent.com/495429/204552674-8a9dee12-3ff1-47f8-8e79-44cbd5603b15.png">
- In Safari, the computed font-size of the parent `<pre>` block is 13px:
  <img width="297" alt="image" src="https://user-images.githubusercontent.com/495429/204553745-fa6b9d97-8d9a-426a-89e3-e44a49d8cab2.png">
- When disabling `font-family: var(--font-code);` OR `font-size: var(--type-base-font-size-rem);` in Safari, the font-size is 16px.
