### ISSUE TITLE
A link in Demos of Open web technologies refers to 'Page not found (404)'.

### ISSUE THREAD

**Issue by anirudhganwal06** [mdn/yari#777]
The link provided in the mdn docs leads to a 'Page not found'. The page which this link refers does not exist. So, please remove this link from the MDN web docs.
https://github.com/mdn/yari/blob/master/content/files/en-us/web/demos_of_open_web_technologies/index.html#L28

**Comment by peterbe** [comment]
Given that the data here in Yari is, as of mid-2020, just a snapshot of the true source, content changes don't actually apply. 
I hope this was sufficiently explained in https://github.com/mdn/yari/pull/778

I hope you can @anirudhganwal06 continue to participate in Yari and make developer.mozilla.org better once this (git) project because *the* source of truth of the data.

**Comment by anirudhganwal06** [comment]
Okay, now I understand.
