### ISSUE TITLE
Required linter/validator for frontmatter

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#7900]
### Summary

Can we please create a linter/validator for front matter that gets run on commit?

### URL

Raised in https://github.com/mdn/yari/pull/7828/files#r1054963370

### Reproduction steps

NA.

### Expected behavior

Every page should minimally have a front matter section with `title` and `slug`. 
- (As I understand it) in some cases that the title have quotation marks around it `'` - would be good to test for these existing if needed.
- Slug should exist. Also be validated and fixed if possible.

```
---
title: Some title
slug: Web/API/Background_Fetch_API
---
```

In addition, some pages will have the following:
- `page-type`:
  - If this exists, it should be one of the supported types.
  - If it is one of the supported types then the page should be in the appropriate matching `slug`.
  - If a page is under a particular slug that "should" have a page type - such as `Web/API` then an error should be reported for a missing page type.
- `browser-compat`
  - Pages of certain types should have a browser compat - specifically reference. We should (probably) require the compat key on pages with the right types even if the key does not exist yet.
  - We should perhaps report warnings on pages that have a page type where we would not expect a key and there is one. 
- `status`
  - This is optional
  - The only allowed (case sensitive) values are `deprecated`, `non-standard`, `experimental`.
- `tags`
  - We're in the process of deprecating these.
  - It would be good to set up infrastructure to disallow tags for particular page types initially. Eventually when all tags are removed we'd disallow them.
- Other: No other metadata currently supported - any other types should be an error.

The front matter should also be linted to standard format (automatically).

### Actual behavior

NA

### Device

Other (specify below)

### Browser

Other (specify below)

### Browser version

Other version (specify below)

### Operating system

Other (specify below)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by wbamberg** [comment]
Thanks so much for filing this Hamish!

For page-type, I would like the linting to capture the fact that different parts of the tree have different sets of allowable page types, as we document in places like https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/Page_type_key#css_page_types.

I think we could perhaps have a file in jsondata something like:

```json
{
  "global": [
    "guide",
    "landing-page"
  ],
  "/en-US/docs/Web/CSS": [
    "css-module",
    "css-shorthand-property",
    "etc"
  ],
  "/en-US/docs/Web/JavaScript": [
    "javascript-class",
    "etc"
  ]
}
```

...that drives it.

**Comment by nschonni** [comment]
Here is an example for a Remark-lint plugin https://github.com/JulianCataldo/remark-lint-frontmatter-schema. Maybe something simlar could be leveraged in Markdownlint, or use the approach of using ajv in Yari with a schema

**Comment by hamishwillee** [comment]
@OnkarRuikar FYI this is a general issue created for front matter linting.

**Comment by OnkarRuikar** [comment]
All, if no one has started working on it may I be assigned this issue?
I've already started working on it as BCD_sync script desperately needs uniform front matter.

@hamishwillee please add `browser-compat` and `spec-urls` attributes to the list.

**Comment by OnkarRuikar** [comment]
@hamishwillee we also have `browser-compat` and `spec-urls` attributes.

I am working on a front matter linter/validator because BCD_sync script needs it due to new `status` attribute. But it is being written as a separate npm package, that way we can have it in VSCode to see bugs in real time.

**Comment by OnkarRuikar** [comment]
> Here is an example for a Remark-lint plugin [JulianCataldo/remark-lint-frontmatter-schema](https://github.com/JulianCataldo/remark-lint-frontmatter-schema). Maybe something simlar could be leveraged in Markdownlint

The Markdownlint [ignores front matter](https://github.com/DavidAnson/markdownlint/#configuration). I tried writing a plugin for it but it is [not possible to refer to line numbers in front matter](https://github.com/DavidAnson/markdownlint/blob/eb2a3c092223fbce7b01d02399de5f9a3152c667/lib/markdownlint.js#L601). So I am working on a separate package using ajv/tv4.

**Comment by OnkarRuikar** [comment]
Adding to the requirements.

I've been told we do need fixed order. Is following order ok?
```
title: Abc Api Property
slug: Web/Api/Abc/property
page-type: api-property-page
status:
  - experimental
  - non-standard
browser-compat: api.abc.someProp
spec-urls:
  - https://www.w3c.com/abc/someProp
  - https://drafts.wg.com/feature
```

Also ATM we are switching between array and single value depending on the number of values for an attribute:
```yaml
# for single value
status: experimental
# and not using this
status:
  - experimental


# use array if multiple values
status:
  - experimental
  - non-standard
```
Let me know if we want to change this.

/cc @teoli2003

**Comment by teoli2003** [comment]
I confirm that fixed order should be enforced (eventually automatically, not blocking a PR)

For the single/multiple value, I have no strong feelings, as long as we have a convention.

**Comment by hamishwillee** [comment]
Currently the format for status is:
```
status:
  - experimental
```
It never occurred to me it could be anything else. I somewhat prefer it like this, because I just converted everything to use this format :-). But easy enough to script a change if needed.

**Comment by OnkarRuikar** [comment]
> It never occurred to me it could be anything else.

The reason I am asking is `spec-urls`, though the plural name and are arrays, have been laid on single line `spec-urls: https://drafts.csswg.org/css-box/#intro` which is a wrong syntax. Same is the case with `browser-compat`.

> I somewhat prefer it like this, because I just converted everything to use this format :-).

I think for sake of consistency we'll have to convert all single line `spec-urls` and `browser-compat` to arrays. Otherwise we'll have confusing standard for array attributes.

**Comment by OnkarRuikar** [comment]
One more issue should title use `"`(double quote) or `'` (single)?
```
title: '<rtc>: The Ruby Text Container element'
```
vs
```
title: "<rtc>: The Ruby Text Container element"
```

Both have been used ATM. Single=531 vs double=613

**Comment by nschonni** [comment]
Prettier I believe has opinions on the frontmatter keys and will update them except for some edge cases. Note that it also leverages remark for the parsing/writing, so the rules on when it changes thme are probably there

**Comment by wbamberg** [comment]
> > It never occurred to me it could be anything else.
> 
> The reason I am asking is `spec-urls`, though the plural name and are arrays, have been laid on single line `spec-urls: https://drafts.csswg.org/css-box/#intro` which is a wrong syntax. Same is the case with `browser-compat`.
> 
> > I somewhat prefer it like this, because I just converted everything to use this format :-).
> 
> I think for sake of consistency we'll have to convert all single line `spec-urls` and `browser-compat` to arrays. Otherwise we'll have confusing standard for array attributes.

I'm not wild about `browser-compat` and `spec-urls` being always arrays, because (especially for browser-compat), 99% of the time they are a single value, and single value is really the happy path. Having multiple values causes problems when we want to try to use the data. I feel that making the array the default (apart from making front matter longer) will make that seem like the normal case.

I understand the concern about inconsistency with `status` but feel that `status` is different: it feels to me like always an array of flags, even if the array only has one flag.

**Comment by nschonni** [comment]
Although it's now archived (and I think developed only internally) https://github.com/microsoft/vscode-docs-authoring might have some ideas on how Microsoft tackled the frontmatter leaning and single/many attributes

**Comment by OnkarRuikar** [comment]
@nschonni Looks like the vscode-docs-authoring used RegEx to support the union type `string|array`:
- https://github.com/microsoft/vscode-docs-authoring/blob/ac0c293e6105ac93ca03188ca7bd206608283a57/packages/docs-markdown/src/controllers/cleanup/handleYamlMetadata.ts#L11
- https://github.com/microsoft/vscode-docs-authoring/blob/ac0c293e6105ac93ca03188ca7bd206608283a57/packages/docs-markdown/src/controllers/metadata/metadata-expressions.ts

Regarding Remark and the plugin `JulianCataldo/remark-lint-frontmatter-schema`, JSON schema does support union types so remark(also AJV) could be used to achieve it. But for pretty printing yaml one more plugin `remark-prettier` is required which uses Prettier under the hood.

Regarding prettier, it just extracts the front matter and prettifies the yaml using it's yaml processor, there is no option for validation. It's been suggested to use it like `prettier --write file.md && yaml-lint file.md` :(

In [the PR](https://github.com/mdn/yari/pull/8295) I am going with Ajv because:
- JSON schema doesn't support fix order for properties on objects
- also custom logic is needed [for providing specific valuse based on file location](https://github.com/mdn/yari/issues/7900#issuecomment-1370084343)
- AJV does similar JSON schema validation as the Remark plugin does
- we can compile different schema per document type e.g, CSS, HTML, API etc.
- AJV.dump() does the required pretty printing
- we have markdownlint for body, prettier is going to be for code blocks, and if we add remark for frontmatter it'll complicate things, so custom solution sounds more suitable.

**Comment by nschonni** [comment]
> * we have markdownlint for body, prettier is going to be for code blocks, and if we add remark for frontmatter it'll complicate things, so custom solution sounds more suitable.

Yeah, sorry for the confusion, I wasn't suggesting doubling the markdown linters, just pointing out some prior art in how these can be tackled.

**Comment by caugner** [comment]
Front matter linting has meanwhile been implemented in content (https://github.com/mdn/content/pull/26410).
