### ISSUE TITLE
T - BUG: constants.js is relying on BUILD_ROOT envar which is causing problems

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#795]
Yari used to work w/o specifying BUILD_ROOT in your .env file.

Now, it does not because constants.js appears to rely upon it.

**Comment by peterbe** [comment]
I think the solution lines in fixing this line: https://github.com/mdn/yari/blob/165c30967e58a40cf578edf282c80f840a9b685b/server/document.js#L11 so that it can use a default instead. 

Maybe something like this:
```javascript
const { DEFAULT_BUILD_ROOT} = require("content/scripts/constants");
const CONTENT_ROOT = DEFAULT_BUILD_ROOT
```

**Comment by peterbe** [comment]
I should also explain something.
Between when you *started* the CRUD branch and it getting merged to master I did this: https://github.com/mdn/yari/commit/844bdffbcedaa5d3daff12a542baee62e9e574d7
It's bit hard to see but basically, now you no longer need to have a `.env` to get started because the few things that were in there can be "inferred" from defaults. 

The only reason you *had* to have `BUILD_ROOT` in your `.env` was because it was the only way I could think of, at the time, to run `stumptown-renderer` with *only* the `stumptown-content` stuff. 

Now, you *always* get `content/files/` added as a source, and `BUILD_STUMPTOWN_ROOT` and `BUILD_ARCHIVE_ROOT` are optional ones. 

I like the idea that you don't need to create a `.env` just to get started. Instead all defaults should be sensible and adding stuff to `.env` should be for the hard-core yari hackers and potentially unique things that is genuinely different from human to human such as setting their `EDITOR` (if their shell doesn't already always set it).
