### ISSUE TITLE
Remove "Inheritance" sections from JS sidebar

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#8052]
### Summary

As discussed in the London work week, consider removing the "Inheritance" section in JS sidebars as we assume it is not really needed to say on every sidebar that JS built-ins inherit from Function and/or Object. Web APIs also don't list them. It makes long sidebars even longer.

### URL

Any JS standard built-in object, for example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
2. Scroll down to see the "Inheritance" section in the sidebar

### Expected behavior

No such "Inheritance" section. Less long sidebars.

### Actual behavior

An "Inheritance" section listing Object and/or Function and all of their members.

### Device

Desktop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

Meeting minutes where this was discussed: https://github.com/openwebdocs/project/blob/main/steering-committee/meetups/london-2023/session-content.md

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by Josh-Cena** [comment]
Instead of removing inheritance everywhere, we should replace it with something more useful. For example, I think mentioning it inherits from `Object` is not entirely useless, but things like `Int8Array`, `AsyncFunction` etc. should have a proper note that they inherit from `TypedArray` and `Function`, respectively. In https://github.com/mdn/content/pull/22881 I'm adding a one-sentence mention about inheritance, but I'm still not a fan. In web API this is fixed by having an inheritance diagram in the landing page; but, short of such structured data in JS, I think the sidebar is still a nice place to have the data around.
