### ISSUE TITLE
U - Assess integrating Yari1 template with Kuma (SSR/API/DevOps)

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#819]
See Epic #815

### **Acceptance Criteria:**

Please put notes here: [https://docs.google.com/document/d/1WxdKSydtCt1Wttt_i-T49pfI2313Lw50J_dY2YLUXEE/edit#](https://docs.google.com/document/d/1WxdKSydtCt1Wttt_i-T49pfI2313Lw50J_dY2YLUXEE/edit#)

- [x] A list defining what changes/work/tasks , new features (if any), and deprecations  would be required to get Yari1 content/template to work with Kuma.
- [x] Estimates or t-shirt sizes (S/M/L) for each item on the list above
- [x] Overall, assess developer experience/maintainability of the work you've defined (which will be harder to maintain/change in the short and long-term?) 
- [x] Overall, assess how (if at all) it will change end user experience 
- [x] Overall, assess effects on performance
- [x] If there are multiple possible approaches to each solution (each  with tradeoffs), define those approaches. E.g fast w/high tech debt, slow w/low tech debt.

**Comment by escattone** [comment]
### Summary
My original approach to this task was to see how we could bring the existing Kuma document front-end machinery (HTML, JS, CSS, fonts, bundling, minifying, etc.) into the world of Yari. That proved to be a very frustrating and complicated path for several reasons. First, there is the world of Kuma front-end assets, like JS and CSS/SASS files, and these are managed by Kuma's `django-pipeline` and `webpack` tools (for bundling and minifying), and so it's not straightforward to find a way to bring those assets into Yari. Second, there is the Kuma React code, which is not built on the `create-react-app` foundation, and that has to be somehow brought into Yari for server-side rendering. There are other issues, but those are two of the biggest.

@Gregoor deserves the credit for suggesting that we reverse the approach. What if we bring the Yari build results into the Kuma document machinery? That has proven to be an interesting, viable path, and that's the path I'm going to document here.

### List of Work Items

In summary, this option involves four main areas of change (each preceded with its T-shirt size estimate):
1. (**S-M**) We'll have to add a piece to the Yari builder that creates a special JSON file for each document. This JSON file provides the essential document data that Kuma needs to render a document page (see https://github.com/mdn/kuma/blob/608ae04bab9e7dd9b19512ed8f856fe022dae4ef/kuma/wiki/views/document.py#L1015 -- of course, the `wikiURL` attribute doesn't make sense in the world of Yari, and the `translateURL` and `translationStatus` may not be needed depending upon our L10n approach). These JSON files will be the primary build artifacts from Yari that we use for the stage and production sites, while the existing HTML and JSON files that Yari creates will continue to be used for the local preview server, and probably for any temporary sites created for review purposes. These JSON files will be uploaded to S3.
1. We'll need to be able to upload files to S3, but that's already part of the Yari plan no matter what approach we select.
1. (**S**) Document page requests will **not** be routed from the CDN to S3 to retrieve fully-rendered pages (as we will do once we move to our completely static JAMStack approach). Instead, they will continue to be routed to our Django service, and a modified version of our document view within Django will process the request and return a fully-rendered page.
1. (**M**) As mentioned above, we will have to modify Kuma's current React-based document view (see https://github.com/mdn/kuma/blob/608ae04bab9e7dd9b19512ed8f856fe022dae4ef/kuma/wiki/views/document.py#L867). That view will be modified to retrieve the document data it needs from S3 (our special JSON files) instead of MySQL, and use that data to return a fully-rendered page (using Jinja templates, `django-pipeline`'s template tags `javascript` and `stylesheet`, Kuma's React-based server-side-rendering including the `express`-based SSR service, etc.). Content-based redirects will be indicated within the JSON file, and handled by that modified view as well.
1. (**S**) The Kuma React components used for document pages will have to be modified to reflect the new world of Yari (for example, no more Wiki, different edit and translation links, etc.). These changes shouldn't be too complicated, but we'll need to go through all of the components and make sure we remove or modify pieces that no longer make sense.
1. (**M**) Since all of the document-related requests will be served from Django instead of being routed by the CDN to S3, we'll need to disable/remove all of the other document-related endpoints/views served by Django that no longer make sense in the world of Yari (e.g., all of the `$` endpoints like `$json`, `$edit`, `$move`, `$translate`, `$children`, and so on)

**Comment by escattone** [comment]
### Developer-Experience/Maintainability Assessment
In terms of developer experience, it has the really significant drawback that all of this code is temporary. Eventually, all of it will be thrown away. **None of it contributes to the long range future of Yari**. On the positive side, I don't see a heavy maintenance burden for the period of time this code is used.

**Comment by escattone** [comment]
### End-User Experience
The only risk to the end-user experience is the possible increase in average response time for document pages due to using S3 instead of AWS RDS (although if that turned-out to be the case, we could try an alternative approach like baking the JSON files directly into the Kuma image, avoiding S3 altogether). Nothing else about the user experience should change.

### Performance
As mentioned earlier, I think the unknown here is how using S3 instead of AWS RDS for document page requests will affect performance/reliability. It might be slower and it might be enough slower that we have to use an alternative approach (two alternatives come to mind: first, increase the CDN TTL such that S3 is only used for the first request and all subsequent requests are served from the CDN until the cache is invalidated; second, bake the document JSON files directly into the Kuma Docker image).
