### ISSUE TITLE
T - 'Edit on Github' link 404s, base URL to repo should be configurable.

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#826]
**Steps to reproduce:**

If you click on 'Edit on Github' you'll get a 404 if you've forked the Yari repo, because it assumes your repo/branch is in the MDN org.

**Possible fix:**
It'd be nice if this was configurable in the .env so that if you're editing locally on your own fork, you can have that link point to your own github repo/branch (and not get a 404).

**Comment by Gregoor** [comment]
We could get the remote's name using the git CLI (which we already use to get the branch name). Then again I'm not sure whether people's expectation is that the link takes one to the main repo or one's fork? 🤔 I guess you're right and it's the latter. But given that the code gets the repo URL from the package JSON, @peterbe might think differently about it? I guess we could also have two links: `Edit on GitHub: [main repo] or [fork]` (or sth like that)

**Comment by peterbe** [comment]
I think it should hardcode the `mdn` fork and the `master` branch. Also, the primary use case for this link is not for content editors who've taken the time to `git clone` and `yarn start` and `open http://localhost:3000`. These people have many much more powerful tools. 

No, the primary use-case is for completely uninitiated readers of MDN who might spot a typo or a content bug in and knowing where the hell to start. We could just make it a link to `<a href="https://github.com/mdn/yari">MDN is maintained on GitHub</a>` but it's hoping to be a little bit more. I.e. that link but with a hint of what the folder was. 

The problem is that if a user is dumped into [a `index.html` page like this](https://github.com/mdn/yari/blob/master/content/files/en-us/web/javascript/index.html) it might not be entirely clear what to do next. Perhaps more ideal would be to make it link to a page about **how** to contribute. Kinda like the Quickstart in the README.md but with better verbiage around it. 

BCD is doing something similar. But it's not great. 
Look at [a BCD table like this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility) and in the upper right-hand corner there's a 
```
<a class="bc-github-link external" 
 href="https://github.com/mdn/browser-compat-data" 
 rel="noopener">Update compatibility data on GitHub</a>
```
which just dumps you into the root of the GitHub project without any reference to the page you *were on*. (There's a technical reason/limitation for this). 

I'm just hoping we can do something slightly better. 

PS. Another typical inspiration is the prevalence of Readthedocs which almost always have a "Edit on GitHub" link near the upper right-hand corner. [Example](https://tecken.readthedocs.io/en/latest/)

**Comment by peterbe** [comment]
We changed how that works. Drastically.
