### ISSUE TITLE
Change form / document preview to be vertically separated

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#837]
We likely also would want to by default hide the sidebar in that view, to maximize the useful horizontal space.

**Comment by peterbe** [comment]
I'm actually a bit hesitant about this. Suppose you make a thing like this;

```html
<div id="both">
  <div id="read">
    <p>Bla bla bla...
  </div>
  <div id="edit">
    <textarea>
       &lt;p&gt;Bla bla bla...
    </textarea>
  </div>
</div>
```
And we make `#read` and `#edit` be two 50%-width columns. 
And we probably make the `#read` innerHTML be *without the sidebar* so that it's feasible at all to fit it all on a desktop display. 

The raw source (on the right) will most definitely **be shorter**. You'd have to scroll inside both containers in a somewhat odd way. And it'd be pretty hard to implement an auto-scroller that follows the position of the cursor. 
When you translate docs on the current Wiki you get a nice effect (except, maybe fore Finnish because it's so much more verbose in word length) because they're pretty similar in height.
