### ISSUE TITLE
Summary in front-matter and the text-area of the web editor is confusing in multiple ways

### ISSUE THREAD

**Issue by escattone** [mdn/yari#841]
The `summary` in the front matter as well as the text area of the web editor is confusing in the following ways:
- Can it contain macros or not?
- Is it automatically added to the document, or do I have to also add/modify it within the document?

**Comment by peterbe** [comment]
We *need* to have a summary, right? Because it's used for the tooltip in the links in the sidebars, right?
So it's not an option to always, runtime figure this out. 

A super simple solution would be to rearrange the Create Document form so that it's 1) Title 2) Body 3) Summary and near the summary (smaller) textarea, there's a button that says "Suggest summary" and it uses the body (and some `cheerio`) to figure out what the first paragraph is saying and it removes any HTML or KS macros from it. 

And when you're editing a document (in-browser) the "Suggest summary" can still be there but we could also have a piece of code that checks if the summary to body relationship is still intact. Only as a notice/warning, not an error.

**Comment by peterbe** [comment]
Another thing that we should consider is to literally explain what the Summary is for. On the form. 

I'm pretty sure it's only used for the sidebar(/breadcrumb?) link tooltips but I can't guarantee that without auditing the code.

**Comment by wbamberg** [comment]
> We need to have a summary, right? Because it's used for the tooltip in the links in the sidebars, right?

We don't always have tooltips in sidebar links in Kuma. Remember that there are ~30 different sidebar implementations, so it's hard to generalize about them.

You might want to consider not supporting title attributes at all in sidebars. As a similar case, links generated by the `jsxref`, `domxref`, `bug`, and `glossary` macros used to include title attributes. In https://github.com/mdn/sprints/issues/2787 we stopped doing that, and to my knowledge we have had 0 complaints about this change (and especially `jsxref` and `domxref` are some of our most commonly-used macros of all).

**Comment by peterbe** [comment]
Is there an important SEO thing about having lots of good full-fat `title` tooltips on links @atopal ?

One thing I know is that all the summaries appearing in all of those `<a>` tags in the sidebar do make the final HTML document very heavy. Gzip helps but a lot of this is uniquely different words. And users don't benefit from it unless they hover over every single link.

**Comment by atopal** [comment]
I'm not sure about the tool tips and their SEO impact. What do you mean by heavy, Peter?

**Comment by peterbe** [comment]
> I'm not sure about the tool tips and their SEO impact. What do you mean by heavy, Peter?

Short answer is that the combined size of all the `title` attributes in the sidebar, on a page [like this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), is 24KB. 
When comparing compressed, the difference is 6.5KB. And that's 6.5KB downloaded and parsed, entirely in vain if you never hover over any of the links long enough to read the tooltip.

But because the HTML, in both Kuma and in Yari, contains a JSON encoded copy of the React state, all of that is repeated. So, uncompressed, the penalty is 24KB * 2. 

A smaller HTML footprint means the browser will be able to start rendering sooner. 

Truth is; HTML is fast compared to heavy CPU stuff like JavaScript. It wouldn't be surprised if we do a web perf experiment that optimizations like this don't register nearly enough compared to other bigger ticket items. 

One potential thing we *will be able to* do in Yari is have an event listener (`onMouseOver`) that fetches the tooltip title on-the-fly. That means that users, albeit a small delay, will get exactly what they got before.

**Comment by atopal** [comment]
I'd say that worrying about performance impact of title attributes is a bit premature. Certainly something we can deal with once we have an MVP

**Comment by peterbe** [comment]
Simply [removing the summary](https://github.com/mdn/yari/issues/902) `textarea` might change the debate here a little bit.

**Comment by peterbe** [comment]
Moot! Moving on with life.
