### ISSUE TITLE
Incorrect browser compatibility labels?

### ISSUE THREAD

**Issue by FozzieHi** [mdn/yari#8586]
### Summary

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer#browser_compatibility

If you go to Edge under the `messageerror event` row you will see no support for 17 - 18:
![image](https://user-images.githubusercontent.com/23139726/230484557-a744602a-0b6d-4712-9fb0-78ed8c6b1b1d.png)

This doesn't seem to correlate with what is in `brower-compat-data`:
https://github.com/mdn/browser-compat-data/blob/e84630bad754dee9f6422fc18e325df4ce2342d5/api/ServiceWorkerContainer.json#L273
```json
"edge": [
  {
    "version_added": "80"
  },
  {
    "version_added": "17",
    "version_removed": "79"
  }
],
```
I'm not entirely sure what it should say here, but this doesn't look right.

There is also an odd label for the "Removed in 79 and later" icon saying "User must explicitly enable this feature.":
![image](https://user-images.githubusercontent.com/23139726/230484886-d4f904e8-b12a-4be8-8aac-19a27fd24c81.png)

### URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer#browser_compatibility

### Reproduction steps

Detailed above

### Expected behavior

Detailed above

### Actual behavior

Detailed above

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
> If you go to Edge under the `messageerror event` row you will see no support for 17 - 18:

Even though it does not seem to correlate, it actually does and is correct:

- The feature was first supported in Edge 17 and last supported in Edge 18, because it was removed in Edge 79 (which followed Edge 18).
- The feature has been supported again since Edge 80.

But the tooltip is indeed wrong. Could you please [open a separate bug report](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) for it? 🙏

**Comment by FozzieHi** [comment]
> > If you go to Edge under the `messageerror event` row you will see no support for 17 - 18:
> 
> Even though it does not seem to correlate, it actually does and is correct:
> 
>     * The feature was first supported in Edge 17 and last supported in Edge 18, because it was removed in Edge 79 (which followed Edge 18).
> 
>     * The feature has been supported again since Edge 80.

Oh right! That's interesting Edge version numbering. Although then shouldn't it be "Full support" for "17 - 18" as it was supported in these versions? At the moment it's indicated as "No support" for these versions which doesn't seem right.
> 
> But the tooltip is indeed wrong. Could you please [open a separate bug report](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) for it? pray

Will do, thanks!

**Comment by danielhjacobs** [comment]
> Although then shouldn't it be "Full support" for "17 - 18" as it was supported in these versions?

It was a purposeful, although admittedly sometimes confusing decision that the icon for features that were fully supported but later removed would be the "No support" icon. This works well for things like the error event on this same page: if the icon were the full support icon it would look like the event was still supported, as you'd see green instead of red. It is a bit more confusing for features that are removed and then re-added, like this one, but that's just a consequence of the decisions that were made for other situations.
