### ISSUE TITLE
Move toolbar out of <Document/> and into <App/>

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#871]
Today, most of the stuff in the Toolbar is related to documents (e.g. "Delete document", "Show flaws")
But it doesn't have to be so. We have always had plans for adding interesting metadata in there such as "You have 3 unstaged changes in git". And generally, it's a nice to have thing that assures you you're in previewing mode even if you click around on something that isn't a document (e.g. home page). 

The other useful use case is the document spy. If it's loading on an "app level" rather than "document level", it means we can re-use the WebSocket connection between router clicks. The WebSocket will always need to be destroyed and recreated when you refresh the browser. 

We have another issue somewhere about the document spy being "louder" about which page just got an update (on disk) and that that document might not be the one you're viewing. This is applicable to being on a page that isn't a document too.

**Comment by peterbe** [comment]
I looking into it and it's doable. But complicated. 
Perhaps I can try something like https://paco.sh/blog/shared-hook-state-with-swr#usesharedstate as a simple hook to get notified, in the `<App>` when the `<Document>` changes the doc.

**Comment by schalkneethling** [comment]
@peterbe is this still something we want to do?

**Comment by peterbe** [comment]
Well, what do you think? 
I think we've toned down our dreams about an amazing toolbar that can do all sorts of things (like Wordpress) even on pages that aren't documents. For example, we've decided you can't create or move documents using the Toolbar. 

The way this issue is phrased is to just rearrange how the React code works without an visual difference. Perhaps if we had a compelling design for a new toolbar implementation it'd be different. Do we have any compelling new design implementations for a better toolbar?

**Comment by schalkneethling** [comment]
> Do we have any compelling new design implementations for a better toolbar?

At the moment I have to say I am way too disconnected from how this is currently used, and what the future for this might look like. If we feel that the way it is now(visually) is the way it is because of time constraints and dedicating time to improve it visually makes sense, then I am _sure_ between myself and Daryl we can come up with ideas.

The question is, is it the best use of our limited resources. If not, then it is probably not worth it. If it still makes sense to make the architectural change on the React side irrespective of the UI representation, then let's keep this open.

If not, I would vote to close this one.

**Comment by peterbe** [comment]
If we do magically decide to come back to this, we'll phrase it differently; state exactly what we want to build and then how we do the React component implementation details is something that'll be part of the PR. Not the issue.
