### ISSUE TITLE
preconnect to iframes if applicable

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#88]
Since stumptown-renderer is stateless and relatively dumb our best bet is to use meta tags for sending pre-fetching type of hints. 

When rendering a page that will have `<iframe src="https://someotherdomain/...` in it, we should inject something like `<link rel="preconnect" href="https://someotherdomain/...` in the HTML.

**Comment by peterbe** [comment]
@joedarc how much do you know about preconnect and iframes and stuff like that?

**Comment by joedarc** [comment]
Since the creation of the `<iframe>` seems contingent upon the JSON response, I’m not sure I understand the benefit of adding a preload (unless I’m not understanding).

**Comment by joedarc** [comment]
Unless you mean hard-code the <link rel=“preconnect”> tags for the domains of the code examples?

**Comment by peterbe** [comment]
That's the kinda interesting feedback I was looking for. Thing is, look at line 149-150 on production: view-source:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video 
[Why there's two of them I don't know](https://github.com/mozilla/kuma/issues/5680).

I think the idea is that the browser is first confronted with the HTML document from that first HTTP connection. It then starts to parse the HTML and can spawn worker-threads for various stuff. For example, it sees a `<script defer src="/foo.js">` and can start preparing that as it continues through the HTML. Then, hopefully, when it's ready to layout and paint, and triggering events, it'll eventually start dealing with those `<iframe>` tags it saw. Then, was it worth preconnecting to those?? 

Adding in the tag into the HTML would be easy. Doing the research to see if it makes any valueable performance impact might be premature. What do *you* think?

**Comment by joedarc** [comment]
> Why there's two of them I don't know.

I think it would be due to browser-compatibility differences. With modern browsers the difference in compatibility between the two is negligible. `dns-prefetch` is more supported than `preconnect` overall, so i would guess that's why it performs both. `dns-prefetch` only does DNS lookup while `preconnect` does DNS + TCP + TLS.

> Doing the research to see if it makes any valueable performance impact might be premature. What do you think?

I did some really non-scientific testing, and there's a negligible difference with or without it within a margin of error. I hard-coded the tag in the `<head>` and profiled it with the dev-tools in the network tab. It seemed to make no noticeable difference, at least nothing consistent enough to say "this really made a difference" or anything.

**Comment by joedarc** [comment]
Having said that, it probably wouldn't hurt to add them, but it doesn't seem to be helping much either.

**Comment by peterbe** [comment]
> wouldn't hurt to add them, but it doesn't seem to be helping much either

Then let's not bother. For the benefit of hacking on other cooler things. But let's not close the issue just yet. 
Mind you, sometime soon I hope we can turn PRs into fully deployed subdomains. Then we can make one production site with and one without and then it's be easier to measure.

**Comment by peterbe** [comment]
Just not important enough, now, in the grand scheme of things going on.
