### ISSUE TITLE
"Update compatibility data on GitHub" link

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#92]
The link here...
<img width="871" alt="Screen Shot 2019-08-28 at 10 31 34 PM" src="https://user-images.githubusercontent.com/26739/63905870-a7b61d00-c9e3-11e9-9394-8cfff70e2737.png">
Plainly goes to https://github.com/mdn/browser-compat-data
It's the same on prod as of today: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Browser_compatibility

Why can't it go to https://github.com/mdn/browser-compat-data/blob/master/html/elements/video.json instead?

The data needed to build the table looks like this:
```

{
  "html": {
    "elements": {
      "video": {
        "__compat": { ...
```
So, to make the right URL you just need to take each key of the JSON until you dug down to "__compat" and join them with a `/` and add `.json` to the end and prefix the whole thing with `https://github.com/mdn/browser-compat-data/blob/master/`.

**Comment by peterbe** [comment]
What do you think @Elchi3 and @ddbeck ?

**Comment by ddbeck** [comment]
I like the idea of the feature itself, linking to the JSON file directly, _a lot_. I'd use this on a daily basis. There are a few caveats though.

And the method you've suggested would work in a lot of cases—probably the overwhelming majority—if we passed the full BCD hierarchy into the stumptown JSON (right now it cuts off at the `__compat` object, though it would be trivial to add the full BCD identifier as part of the `browser_compatibility` content object type).

Unfortunately, there are still a lot of cases where it wouldn't quite work as you've described. Consider [`Response.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) as an example. Its BCD identifier is `api.Response.ok`, but feature data is in the file `/api/Response.json` (since it's a subfeature of `api.Response`).

If you had the full hierarchy, you could hard code the depth of features that correspond to a file. You'd have to do this for each of the feature categories (`api.*`, `css.{at-rules,properties,selectors,types}.*`, etc.). A better, smarter thing to do might be to give the `browser-compat-data` package a real API for this sort of thing (e.g., call some method with a feature identifier to get back the GitHub URL for that feature—it'd be possible to get the exact line number, even). I imagine such a thing would be useful for more than just stumptown.

Either way, we could have the stumptown content JSON look something like this:

```
{
      "type": "browser_compatibility",
      "value": {
        "__compat": { … }
      },
      "source_id": "api.Response.ok",
      "github_source_url": "https://github.com/mdn/browser-compat-data/blob/master/api/Response.json"
}
```

**Comment by peterbe** [comment]
I don't think I really understood the `source_id` because if you can make that above JSON block, stumptown-renderer just needs the `github_source_url`.

**Comment by peterbe** [comment]
So, what would it take to make that stuff a reality in stumptown-content? Can it be done?

**Comment by peterbe** [comment]
@ddbeck Can we close this now? (now that we have the new new-issue link)
Or did you have in mind to do more fine-tuned links directly into the files in the bcd repo.

**Comment by ddbeck** [comment]
Yep, this is good enough for now. Thank you!
