### ISSUE TITLE
DOMContentLoaded event doesn't fire in playground

### ISSUE THREAD

**Issue by KarnuteBeard** [mdn/yari#9409]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script#example

### What specific section or headline is this issue about?

Example

### What information was incorrect, unhelpful, or incomplete?

The example with the circle doesn't seem to work properly.

### What did you expect to see?

The color of the circle is supposed to change when clicking on it, but it doesn't.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/element/script`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/element/script/index.md
* Last commit: https://github.com/mdn/content/commit/fa8a44b8bff24a4032181c4fd155c459c0dc9161
* Document last modified: 2023-03-13T07:09:38.000Z

</details>

**Comment by LeoMcA** [comment]
This is a fun one :)

Doesn't appear to be a CSP error, but an issue where we don't fire the `DOMContentLoaded` event in the playground.
See this example: https://developer.mozilla.org/en-US/play?id=0l%2FeI08tjIqgWZP2zZBryri0RiOuXkktPfOYw6yHLjFFBEhke%2BMWR31v%2B5o8dQFUIStcMITJzz3agKgu

We need to discuss this, and fix it, but this example can be fixed in its own right by just removing the event listener and re-ordering the `<script>` - I'll open a PR to this effect: https://developer.mozilla.org/en-US/play?id=2g%2FZNMSCuQTl4CIaSHWgPjkFPAQeRqk%2FwbYjPbBE%2FABwlkEomUrIxmLjHJ24LmpZGBKjKwtzETEeDnZJ
