### ISSUE TITLE
color-mix() does not show in printed version

### ISSUE THREAD

**Issue by alolalo** [mdn/yari#9555]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix

### What specific section or headline is this issue about?

#using_hue_interpolation_in_color-mix

### What information was incorrect, unhelpful, or incomplete?

When you print this article, the CSS in the print does not apply any of the color-mixing! It's interesting to see if the spec itself was thought out as such, or that there might not be a print.css in place for when people actually print documentation, but I do

See for yourself; Hit CTRL+P or CMD+P to see that MDN-docs nicely show a print-version that is all about the content. But the CSS color-mix() is not applied (yet) due to the fact print might not even handle it. 

This could be caused also by not having a fallback-color in place, or showing png's on print as an alternative.

### What did you expect to see?

The actual image you see in the article created with CSS using color-mix()

### Do you have any supporting links, references, or citations?

The article itself can be used as proof to create a print of the article, to show that color-mix() will not show up in print

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/color_value/color-mix`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/color-mix/index.md
* Last commit: https://github.com/mdn/content/commit/c754ecfaf2d24aa9e130efde70c743f03421db40
* Document last modified: 2023-06-12T14:59:25.000Z

</details>

**Comment by Josh-Cena** [comment]
This looks like a content issue. I can reproduce with a bare-metal HTML file on all three browsers. I can't find any relevant info in the spec, though.

**Comment by caugner** [comment]
@alolalo Thank you for reporting this issue.

I checked the printing preview of [the article](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix) in Firefox 120 (Nightly), Chrome 117 and Safari 17:

- **Firefox** correctly displayed the colors with the "Print backgrounds" option enabled:
    <img width="809" alt="image" src="https://github.com/mdn/yari/assets/495429/532b7d96-57f8-49ab-8af4-cf4efb21bd98">
- **Chrome** ignored the colores, even with the "Background graphics" option enabled:
    <img width="835" alt="image" src="https://github.com/mdn/yari/assets/495429/1fa75b21-05f8-4822-8a46-d5f1594be6d5">
- **Safari** displayed the colors with the "Print backgrounds" option enabled (black and white for me, because I don't have a color printer, but the PDF had the correct colors):
    <img width="758" alt="image" src="https://github.com/mdn/yari/assets/495429/d2e9704e-f543-4f62-9f17-5296c4844ff0">

My conclusion is that this isn't an MDN issue, but a Chrome issue, so I would recommend filing an issue in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list).
