### ISSUE TITLE
Add line numbers to code snippets

### ISSUE THREAD

**Issue by izh1979** [mdn/yari#9671]
### Summary

Currently many MDN articles refer to particular line numbers in the code. E.g., "Line 16 actually initiates the request." However, the code snippets do not have the line numbers. So, it is inconvenient to find the corresponding line.
Having lines numbered could be better.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

### Reproduction steps

1. Open any article with the code snippets.
2. The lines are not numbered.

### Expected behavior

The lines are numbered.

### Actual behavior

The lines of the codes snippets are not numbered.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by s-sood** [comment]
Hi @izh1979, We had line numbers in the past for the code snippets and we decided to remove them, some of the discussion about this decision is mentioned in [this](https://github.com/mdn/yari/pull/6372) issue. 

The main reason is that line numbers in code can help but when we start referencing those line numbers in text, it can be a maintenance overhead to keep the reference in text in sync with any updates to code.

**Comment by janbrasna** [comment]
What is the consensus to do with similar occurrences like the one reported: [XMLHttpRequest/Synchronous_and_Asynchronous_Requests](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests) — should all the references to line numbers in text be considered a bug, reported for improvement, and potentially rewritten somehow more contextually?

I remember lines & highlighting not being brought over to the new system https://github.com/mdn/content/issues/3512#issuecomment-807933061, but not sure what to do with pages that rely heavily on that in text. (Any ideas @wbamberg @chrisdavidmills 👋 what should be done in such cases?)

**Comment by wbamberg** [comment]
If we're committed to not having line numbers in code samples then we should update pages that don't make a lot of sense without them. I don't think there are that many of these.

In documentation like https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Synchronous_and_Asynchronous_Requests, _even if we had line numbers_, the documentation would still be hard to use because the text is quite far from the code, so I have to keep scrolling up and down to see which line is referred to.

It's also unclear which of the 2 code blocks the line numbers are referring to.

Perhaps comments might work better? Although I'm not that keen on documentation-in-comments either.

If it were me, for example in this case, I would try to split up the example into 3 separate code blocks and discuss each one separately. And instead of "Line 15 specifies true for its third parameter...", for example, I might say something like: We pass `true` as the value of the `async` parameter to [`xhr.open()`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open)..."

**Comment by chrisdavidmills** [comment]
Hi @janbrasna! It's been a long time since I heard from you; hope you are well ;-)

Totally agree with @wbamberg on this one — we made the decision a long time ago not to have line numbers because of the maintenance nightmare they created (code examples going out of sync with text explanations and associated example repos), and it is better to split up snippets into smaller pieces and explain them contextually in different ways.

So yes, these should be removed/rewritten.

We really shouldn't be showing large code blocks on pages. If we do need to refer to huge code blocks, they should be in a repo somewhere and linked to.
