### ISSUE TITLE
Docs/Web/CSS sidebar contains inconsistent spacing between sections

### ISSUE THREAD

**Issue by zfox23** [mdn/yari#9917]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS

### What information was incorrect, unhelpful, or incomplete?

On the CSS pages, the vertical spacing between section headers (e.g. "Tutorials", "Reference", "Guides", "Layout cookbook", and "Tools") is different, so some sections (mostly "Guides") are hard to differentiate.

### What did you expect to see?

Consistent spacing between section headers.

### Do you have anything more you want to share?

This _might_ be as-designed.

**Comment by caugner** [comment]
Here's a screenshot to illustrate the reported issue:

<img width="305" alt="image" src="https://github.com/mdn/yari/assets/495429/7e7b30e0-e306-40e6-887f-b98b936db7de">

The reason is that "Guides" (and "Tools) is not a link, whereas the other sections are links and it looks like the `display: inline-flex` property of these links causes them to have more spacing.
